// Named ggdef corpus membership census. Included from tests/lints.rs.
// Generated as data; the lint parses prefixes / EXCLUDE from SOURCE and
// checks this table against disk. Do not add combinator_ to the b1 census.

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum GgdefCorpusDisp {
    Exclude,
    Match,
    ReportOnly,
    Equip,
}

use GgdefCorpusDisp::*;

/// Every `tests/fixtures/*.gg` whose name matches a `starts_with` parsed from
/// `spec/ggdef/tests/corpus_b.rs::gate_fixtures`, each with an explicit
/// EXCLUDE | MATCH | REPORT-ONLY disposition.
pub const GGDEF_CORPUS_B_CENSUS: &[(&str, GgdefCorpusDisp)] = &[
    ("combinator_and_then_money_field.gg", Exclude),
    ("combinator_and_then_money_local.gg", Exclude),
    ("combinator_and_then_money_param.gg", Exclude),
    ("combinator_and_then_string_to_int_param.gg", Exclude),
    ("combinator_callable_param_cross_type.gg", Exclude),
    ("combinator_callable_param_same_type.gg", Exclude),
    ("combinator_chain_map_filter.gg", Exclude),
    ("combinator_filter_money_field.gg", Exclude),
    ("combinator_filter_money_param.gg", Exclude),
    ("combinator_flat_map_money_field.gg", Exclude),
    ("combinator_flat_map_money_local.gg", Exclude),
    ("combinator_flat_map_money_param.gg", Exclude),
    ("combinator_flat_map_string_to_int_param.gg", Exclude),
    ("combinator_map_err_money_local.gg", Exclude),
    ("combinator_map_err_money_param.gg", Exclude),
    ("combinator_map_money_param_and_field.gg", Exclude),
    ("combinator_map_string_to_int_field.gg", Exclude),
    ("combinator_map_string_to_int_local.gg", Exclude),
    ("combinator_map_string_to_int_param.gg", Exclude),
    ("combinator_map_string_to_string_param.gg", Exclude),
    ("combinator_option_is_error_rejected.gg", Match),
    ("combinator_option_is_ok_rejected.gg", Match),
    ("combinator_option_map_err_rejected.gg", Match),
    ("combinator_option_or_else_cross_type_reject.gg", Match),
    ("combinator_option_unwrap_error_rejected.gg", Match),
    ("combinator_or_else_money_field.gg", Exclude),
    ("combinator_or_else_money_param.gg", Exclude),
    ("combinator_result_and_then_error_cross_type_reject.gg", Match),
    ("combinator_result_and_then_money_passthrough.gg", Exclude),
    ("combinator_result_filter_rejected.gg", Match),
    ("combinator_result_flat_map_rejected.gg", Match),
    ("combinator_result_flatten_rejected.gg", Exclude),
    ("combinator_result_is_none_rejected.gg", Match),
    ("combinator_result_is_some_rejected.gg", Match),
    ("combinator_result_map_err_money_passthrough.gg", Exclude),
    ("combinator_result_map_money_passthrough.gg", Exclude),
    ("combinator_result_ok_money_map.gg", Exclude),
    ("combinator_result_ok_string_and_then_to_int_param.gg", Exclude),
    ("combinator_result_ok_string_map_to_int_param.gg", Exclude),
    ("combinator_result_or_else_error_axis_sbo.gg", Exclude),
    ("combinator_result_or_else_error_cross_type.gg", Exclude),
    ("combinator_result_or_else_money_passthrough.gg", Exclude),
    ("combinator_result_or_else_ok_cross_type_reject.gg", Match),
    ("combinator_unwrap_or_else_money_field.gg", Exclude),
    ("combinator_unwrap_or_else_money_local.gg", Match),
    ("combinator_unwrap_or_else_money_param.gg", Match),
    ("combinator_unwrap_or_else_str.gg", Exclude),
    ("cow_alias_severed_by_root_reassign_then_view.gg", Match),
    ("cow_alias_spelled_element_field_borrow.gg", Match),
    ("cow_alias_spelled_view_literal_payload.gg", Match),
    ("cow_alias_spelled_view_survives_root_growth.gg", Match),
    ("cow_alias_spelled_view_via_first_getter.gg", Exclude),
    ("cow_alias_view_spelling_invariance.gg", Match),
    ("cow_amp_bare_alias_arg.gg", Match),
    ("cow_amp_bare_param_arg.gg", Match),
    ("cow_amp_bind_ref.gg", Match),
    ("cow_amp_bind_ref_field.gg", Match),
    ("cow_amp_compound_writethrough.gg", Match),
    ("cow_amp_deref_box_projection.gg", Exclude),
    ("cow_amp_field_arg.gg", Match),
    ("cow_amp_index_side_effect_once.gg", Match),
    ("cow_amp_index_vs_getchain_differential.gg", Match),
    ("cow_amp_live_alias.gg", Match),
    ("cow_amp_method_arg_bare.gg", Match),
    ("cow_amp_owned_writethrough.gg", Match),
    ("cow_amp_projection_autoprop_arg.gg", Exclude),
    ("cow_amp_projection_autoprop_objects.gg", Exclude),
    ("cow_amp_projection_base_shapes.gg", Exclude),
    ("cow_amp_projection_indirect_call_arg.gg", Exclude),
    ("cow_amp_projection_resource_value_split.gg", Match),
    ("cow_amp_projection_type_axis.gg", Exclude),
    ("cow_amp_ref_field_forward.gg", Match),
    ("cow_assign_target_chain.gg", Match),
    ("cow_assign_target_named_control.gg", Match),
    ("cow_bare_param_compound_materialize.gg", Match),
    ("cow_bench_body_view_survives_realloc.gg", Exclude),
    ("cow_borrow_basic.gg", Match),
    ("cow_borrow_field_access.gg", Match),
    ("cow_borrow_outlives_push.gg", Match),
    ("cow_closure_body_view_survives_realloc.gg", Exclude),
    ("cow_closure_capture.gg", Match),
    ("cow_closure_deferred_mutate.gg", ReportOnly),
    ("cow_closure_ptr_capture.gg", Match),
    ("cow_collection_element_mutate.gg", Match),
    ("cow_compound_getref_writethrough.gg", Match),
    ("cow_comprehension_amp_projection_source.gg", Exclude),
    ("cow_comprehension_amp_source.gg", Exclude),
    ("cow_comprehension_fresh_mint_control.gg", Exclude),
    ("cow_comprehension_invariant_dict_value.gg", Exclude),
    ("cow_comprehension_invariant_filter_arm.gg", Exclude),
    ("cow_comprehension_invariant_in_condition.gg", Exclude),
    ("cow_comprehension_invariant_nested.gg", Exclude),
    ("cow_comprehension_invariant_owned_name.gg", Exclude),
    ("cow_comprehension_invariant_struct_payload.gg", Exclude),
    ("cow_comprehension_invariant_vector_source.gg", Exclude),
    ("cow_dead_branch_alias_bind.gg", Match),
    ("cow_dict_index_field_single_eval.gg", Exclude),
    ("cow_dict_index_field_writethrough.gg", Exclude),
    ("cow_direct_for_element_resource_struct.gg", Match),
    ("cow_element_borrow_alias_mutate.gg", Exclude),
    ("cow_element_borrow_source_mutate_with.gg", Match),
    ("cow_enum_bare_assign.gg", Match),
    ("cow_escape_boundaries.gg", Match),
    ("cow_field_of_element_read.gg", Match),
    ("cow_field_of_for_element_read.gg", Match),
    ("cow_fieldpath_double_fire.gg", Match),
    ("cow_fieldpath_method_caller_untouched.gg", Match),
    ("cow_fieldpath_mut_writethrough.gg", Match),
    ("cow_fieldpath_nested_assign_caller_untouched.gg", Match),
    ("cow_flow_sensitive_alias.gg", Match),
    ("cow_for_amp_resource_elem_writethrough.gg", Exclude),
    ("cow_for_amp_vector_alias_root.gg", Exclude),
    ("cow_for_amp_vector_field_writethrough.gg", Exclude),
    ("cow_for_bare_resource_elem_materialize.gg", Match),
    ("cow_for_bare_vector_control.gg", Match),
    ("cow_for_enumerate_amp_alias_root.gg", Exclude),
    ("cow_for_enumerate_amp_recv_wrap.gg", Exclude),
    ("cow_for_enumerate_amp_writethrough.gg", Exclude),
    ("cow_for_enumerate_bare_resource_materialize.gg", Exclude),
    ("cow_for_zero_trip_body_kill_control.gg", Match),
    ("cow_generic_equip_mutator_view_uaf.gg", Match),
    ("cow_generic_equip_named_recv.gg", Exclude),
    ("cow_getref_dict_writethrough.gg", Exclude),
    ("cow_getref_writethrough_resource.gg", Match),
    ("cow_index_field_assign_loop_push.gg", Match),
    ("cow_index_nested_assign_loop_push.gg", Match),
    ("cow_index_proj_alias.gg", Match),
    ("cow_index_proj_caller_untouched.gg", Match),
    ("cow_index_proj_mut_writethrough.gg", Match),
    ("cow_index_proj_rebind.gg", Match),
    ("cow_indexed_element_survives_root_growth.gg", Match),
    ("cow_lazy_compound.gg", Match),
    ("cow_lazy_d1_alias.gg", Match),
    ("cow_lazy_d1_alias_deadpath.gg", Match),
    ("cow_lazy_d1_alias_takenpath.gg", Match),
    ("cow_lazy_d1_movesteal.gg", Match),
    ("cow_lazy_escape_return.gg", Match),
    ("cow_lazy_fieldpath_excluded.gg", Match),
    ("cow_lazy_index_slice_join.gg", Match),
    ("cow_lazy_method_arg.gg", Match),
    ("cow_lazy_move_bind.gg", Match),
    ("cow_lazy_move_consume.gg", Match),
    ("cow_lazy_move_reassign.gg", Match),
    ("cow_lazy_multisite.gg", Match),
    ("cow_lazy_mut_borrow_write.gg", Match),
    ("cow_lazy_reassign_source.gg", Match),
    ("cow_lazy_selfref_concat_poke.gg", Match),
    ("cow_lazy_severorder.gg", Match),
    ("cow_lazy_staletag.gg", Match),
    ("cow_lazy_substring_named_bind.gg", Match),
    ("cow_lazy_w3b_arg_temp.gg", Match),
    ("cow_lazy_w3b_concat_temp.gg", Match),
    ("cow_lazy_w3c_arg_temp.gg", Match),
    ("cow_lazy_w3c_named_bind.gg", Match),
    ("cow_lazy_w3d_for_string.gg", Match),
    ("cow_loop_bare_param_comprehension.gg", Exclude),
    ("cow_loop_bare_param_comprehension_matrix.gg", Exclude),
    ("cow_loop_bare_param_for_else.gg", Exclude),
    ("cow_loop_bare_param_if_branch.gg", Match),
    ("cow_loop_bare_param_index_assign.gg", Match),
    ("cow_loop_bare_param_match_scrutinee.gg", Match),
    ("cow_loop_bare_param_materialize.gg", Match),
    ("cow_loop_bare_param_push_char.gg", Exclude),
    ("cow_loop_bare_param_tuple_receiver.gg", Match),
    ("cow_loop_bare_param_while_cond.gg", Match),
    ("cow_loop_body_local_move.gg", Match),
    ("cow_loop_borrow_propagation.gg", Match),
    ("cow_loop_invariant_owned_name_push_control.gg", Exclude),
    ("cow_materialization_points.gg", Match),
    ("cow_meta_for_zero_trip_body_kill.gg", Exclude),
    ("cow_meta_while_false_guard_body_kill.gg", Exclude),
    ("cow_method_arg_builtin_push.gg", Match),
    ("cow_method_arg_named_recv_same_coll.gg", Match),
    ("cow_method_arg_same_coll.gg", Match),
    ("cow_move_bind_element_borrow.gg", Match),
    ("cow_move_clear_element_borrow.gg", Match),
    ("cow_move_realloc_element_borrow.gg", Match),
    ("cow_move_reassign_element_borrow.gg", Match),
    ("cow_multilevel_3level_index_field.gg", Match),
    ("cow_multilevel_fieldpath_root.gg", Match),
    ("cow_multilevel_index_field_assign.gg", Match),
    ("cow_multilevel_triple_index_assign.gg", Match),
    ("cow_named_recv_gate_name_collision.gg", Match),
    ("cow_named_recv_gate_projected_name_collision.gg", Match),
    ("cow_named_recv_mutator.gg", Match),
    ("cow_named_recv_readonly.gg", Match),
    ("cow_named_recv_transitive_mutator.gg", Match),
    ("cow_nested_field_mutation.gg", Match),
    ("cow_nested_projection.gg", Match),
    ("cow_p3_alias_chain_mutate.gg", Exclude),
    ("cow_p3_cond_nested_mutate.gg", ReportOnly),
    ("cow_p3_field_path_mutate.gg", ReportOnly),
    ("cow_p3_index_mutate.gg", Exclude),
    ("cow_p3_match_nested_mutate.gg", ReportOnly),
    ("cow_p3_readonly_borrow.gg", ReportOnly),
    ("cow_param_alias_reassign.gg", Match),
    ("cow_rescue_mutation_in_container_literal.gg", Exclude),
    ("cow_rescue_mutation_in_control_flow_expr.gg", Exclude),
    ("cow_rescue_mutation_in_operand_position.gg", Exclude),
    ("cow_rescue_mutation_inside_assert.gg", Exclude),
    ("cow_rescue_mutation_through_getchain_receiver.gg", Exclude),
    ("cow_rhs_index_assign.gg", Match),
    ("cow_rhs_same_coll_nested.gg", Match),
    ("cow_rhs_same_coll_single.gg", Match),
    ("cow_rhs_self_row.gg", Match),
    ("cow_scope_bare_param_amp_guard.gg", Match),
    ("cow_scope_bare_param_elif_cond.gg", Match),
    ("cow_scope_bare_param_elif_cond_then.gg", Match),
    ("cow_scope_bare_param_if_both.gg", Match),
    ("cow_scope_bare_param_if_elif.gg", Match),
    ("cow_scope_bare_param_if_else.gg", Match),
    ("cow_scope_bare_param_match_arm.gg", Match),
    ("cow_scope_bare_param_nested_if_loop.gg", Match),
    ("cow_scope_exit_alias.gg", Match),
    ("cow_self_generic_materialize.gg", Match),
    ("cow_self_scratch_fstring.gg", Match),
    ("cow_self_scratch_read.gg", Match),
    ("cow_self_value_field_materialize.gg", Match),
    ("cow_self_value_push_materialize.gg", Match),
    ("cow_set_comprehension_invariant_in_condition.gg", Exclude),
    ("cow_set_string_clone.gg", Match),
    ("cow_struct_bare_assign.gg", Match),
    ("cow_struct_sever_on_mutation.gg", Match),
    ("cow_taint_compound_projected.gg", Match),
    ("cow_taint_formation_param.gg", Match),
    ("cow_taint_formation_self.gg", Match),
    ("cow_taint_getchain_compound.gg", Match),
    ("cow_taint_getchain_firstlast.gg", Match),
    ("cow_taint_getchain_formation.gg", Match),
    ("cow_taint_getchain_receiver.gg", Match),
    ("cow_taint_getchain_user_get_ok.gg", Exclude),
    ("cow_taint_getchain_vector.gg", Match),
    ("cow_taint_pop_value_pos.gg", Match),
    ("cow_taint_self_builtin.gg", Match),
    ("cow_taint_self_field_write.gg", Match),
    ("cow_taint_underscore_param.gg", Match),
    ("cow_taint_whole_amp_param.gg", Match),
    ("cow_taint_whole_amp_self.gg", Match),
    ("cow_test_body_view_survives_realloc.gg", Exclude),
    ("cow_trait_amp_self_field_writethrough.gg", Exclude),
    ("cow_trait_default_view_survives_realloc.gg", Exclude),
    ("cow_trait_plain_self_collection_materialize.gg", Exclude),
    ("cow_trait_plain_self_field_materialize.gg", Exclude),
    ("cow_transitive_alias.gg", Match),
    ("cow_typed_binding_borrow.gg", Match),
    ("cow_user_mutator_fstring_interpolation.gg", Match),
    ("cow_user_mutator_meta_generated_arm.gg", Exclude),
    ("cow_user_mutator_rename_invariance.gg", Match),
    ("cow_user_mutator_two_types_same_name.gg", Match),
    ("cow_value_index_bare_mut_recv_writethrough.gg", Match),
    ("cow_value_index_field_writethrough.gg", Exclude),
    ("cow_value_index_nested_field_store.gg", Match),
    ("cow_value_index_nested_mut_recv_writethrough.gg", Match),
    ("cow_view_into_owned_collection_survives_growth.gg", Match),
    ("deadwrite_build_lock.gg", ReportOnly),
    ("deadwrite_ok_atomic_add.gg", Exclude),
    ("deadwrite_ok_branch_sibling_read.gg", ReportOnly),
    ("deadwrite_ok_copy_struct.gg", ReportOnly),
    ("deadwrite_ok_fstring_read.gg", ReportOnly),
    ("deadwrite_ok_loop_read_before_write.gg", Match),
    ("deadwrite_ok_match_scrutinee.gg", ReportOnly),
    ("deadwrite_ok_mut_param.gg", ReportOnly),
    ("deadwrite_ok_read_only.gg", ReportOnly),
    ("deadwrite_ok_rebind.gg", Match),
    ("deadwrite_ok_scratch_read.gg", ReportOnly),
    ("deadwrite_ok_underscore.gg", ReportOnly),
    ("deadwrite_ok_value_pop.gg", ReportOnly),
    ("deadwrite_ok_while_drain.gg", Match),
    ("deadwrite_warn_branch_read_then_write.gg", ReportOnly),
    ("deadwrite_warn_chained_stmt.gg", ReportOnly),
    ("deadwrite_warn_compound.gg", Match),
    ("deadwrite_warn_early_return.gg", ReportOnly),
    ("deadwrite_warn_field_assign.gg", ReportOnly),
    ("deadwrite_warn_index_assign.gg", ReportOnly),
    ("deadwrite_warn_loop_write.gg", ReportOnly),
    ("deadwrite_warn_nested_field.gg", ReportOnly),
    ("deadwrite_warn_push.gg", ReportOnly),
    ("deadwrite_warn_self.gg", ReportOnly),
    ("deadwrite_warn_string_push.gg", ReportOnly),
    ("deadwrite_warn_user_method.gg", ReportOnly),
];

/// REPORT-ONLY subset of corpus_b (no run_gg / check_gg_fails / self-host pair).
/// Exact-pin: a new fixture cannot land green-and-unwitnessed here.
pub const GGDEF_CORPUS_B_REPORT_ONLY: &[&str] = &[
    "cow_closure_deferred_mutate.gg",
    "cow_p3_cond_nested_mutate.gg",
    "cow_p3_field_path_mutate.gg",
    "cow_p3_match_nested_mutate.gg",
    "cow_p3_readonly_borrow.gg",
    "deadwrite_build_lock.gg",
    "deadwrite_ok_branch_sibling_read.gg",
    "deadwrite_ok_copy_struct.gg",
    "deadwrite_ok_fstring_read.gg",
    "deadwrite_ok_match_scrutinee.gg",
    "deadwrite_ok_mut_param.gg",
    "deadwrite_ok_read_only.gg",
    "deadwrite_ok_scratch_read.gg",
    "deadwrite_ok_underscore.gg",
    "deadwrite_ok_value_pop.gg",
    "deadwrite_warn_branch_read_then_write.gg",
    "deadwrite_warn_chained_stmt.gg",
    "deadwrite_warn_early_return.gg",
    "deadwrite_warn_field_assign.gg",
    "deadwrite_warn_index_assign.gg",
    "deadwrite_warn_loop_write.gg",
    "deadwrite_warn_nested_field.gg",
    "deadwrite_warn_push.gg",
    "deadwrite_warn_self.gg",
    "deadwrite_warn_string_push.gg",
    "deadwrite_warn_user_method.gg",
];

/// The 15 `liveness_*` rows in EXCLUDE. `gate_fixtures`' prefix filter cannot
/// reach them; they are inert. Exact-pin: explain, do not delete, do not
/// silently grow.
pub const GGDEF_CORPUS_B_INERT_LIVENESS: &[&str] = &[
    "liveness_use_inside_loop.gg",
    "liveness_on_error_in_match_arm_do.gg",
    "liveness_on_error_inside_do_block.gg",
    "liveness_on_error_seed_kill_leak.gg",
    "liveness_on_error_nested_registration.gg",
    "liveness_for_zero_iteration_kill.gg",
    "liveness_loop_break_skips_kill.gg",
    "liveness_on_error_after_registration.gg",
    "liveness_loop_body_kill_leak.gg",
    "liveness_metafor_match_arm.gg",
    "liveness_on_error_assign_kill.gg",
    "liveness_on_error_vardecl_kill.gg",
    "liveness_use_inside_named_scope.gg",
    "liveness_use_inside_with_block.gg",
    "liveness_use_inside_assert_return.gg",
];

/// corpus_b1 sibling: cow_/deadwrite_ only (prefixes parsed from its
/// `gate_fixtures`). Equip-filtered files are `Equip`, not silent omissions.
pub const GGDEF_CORPUS_B1_CENSUS: &[(&str, GgdefCorpusDisp)] = &[
    ("cow_alias_severed_by_root_reassign_then_view.gg", Match),
    ("cow_alias_spelled_element_field_borrow.gg", Match),
    ("cow_alias_spelled_view_literal_payload.gg", Match),
    ("cow_alias_spelled_view_survives_root_growth.gg", Match),
    ("cow_alias_spelled_view_via_first_getter.gg", Exclude),
    ("cow_alias_view_spelling_invariance.gg", Match),
    ("cow_amp_bare_alias_arg.gg", Match),
    ("cow_amp_bare_param_arg.gg", Match),
    ("cow_amp_bind_ref.gg", Match),
    ("cow_amp_bind_ref_field.gg", Match),
    ("cow_amp_compound_writethrough.gg", Match),
    ("cow_amp_deref_box_projection.gg", Exclude),
    ("cow_amp_field_arg.gg", Match),
    ("cow_amp_index_side_effect_once.gg", Match),
    ("cow_amp_index_vs_getchain_differential.gg", Match),
    ("cow_amp_live_alias.gg", Match),
    ("cow_amp_method_arg_bare.gg", Equip),
    ("cow_amp_owned_writethrough.gg", Match),
    ("cow_amp_projection_autoprop_arg.gg", Exclude),
    ("cow_amp_projection_autoprop_objects.gg", Exclude),
    ("cow_amp_projection_base_shapes.gg", Exclude),
    ("cow_amp_projection_indirect_call_arg.gg", Exclude),
    ("cow_amp_projection_resource_value_split.gg", Match),
    ("cow_amp_projection_type_axis.gg", Exclude),
    ("cow_amp_ref_field_forward.gg", Match),
    ("cow_assign_target_chain.gg", Match),
    ("cow_assign_target_named_control.gg", Match),
    ("cow_bare_param_compound_materialize.gg", Match),
    ("cow_bench_body_view_survives_realloc.gg", Exclude),
    ("cow_borrow_basic.gg", Match),
    ("cow_borrow_field_access.gg", Match),
    ("cow_borrow_outlives_push.gg", Match),
    ("cow_closure_body_view_survives_realloc.gg", Exclude),
    ("cow_closure_capture.gg", Match),
    ("cow_closure_deferred_mutate.gg", ReportOnly),
    ("cow_closure_ptr_capture.gg", Match),
    ("cow_collection_element_mutate.gg", Match),
    ("cow_compound_getref_writethrough.gg", Match),
    ("cow_comprehension_amp_projection_source.gg", Exclude),
    ("cow_comprehension_amp_source.gg", Exclude),
    ("cow_comprehension_fresh_mint_control.gg", Exclude),
    ("cow_comprehension_invariant_dict_value.gg", Exclude),
    ("cow_comprehension_invariant_filter_arm.gg", Exclude),
    ("cow_comprehension_invariant_in_condition.gg", Exclude),
    ("cow_comprehension_invariant_nested.gg", Exclude),
    ("cow_comprehension_invariant_owned_name.gg", Exclude),
    ("cow_comprehension_invariant_struct_payload.gg", Exclude),
    ("cow_comprehension_invariant_vector_source.gg", Exclude),
    ("cow_dead_branch_alias_bind.gg", Match),
    ("cow_dict_index_field_single_eval.gg", Exclude),
    ("cow_dict_index_field_writethrough.gg", Exclude),
    ("cow_direct_for_element_resource_struct.gg", Match),
    ("cow_element_borrow_alias_mutate.gg", Equip),
    ("cow_element_borrow_source_mutate_with.gg", Equip),
    ("cow_enum_bare_assign.gg", Match),
    ("cow_escape_boundaries.gg", Match),
    ("cow_field_of_element_read.gg", Match),
    ("cow_field_of_for_element_read.gg", Match),
    ("cow_fieldpath_double_fire.gg", Match),
    ("cow_fieldpath_method_caller_untouched.gg", Match),
    ("cow_fieldpath_mut_writethrough.gg", Match),
    ("cow_fieldpath_nested_assign_caller_untouched.gg", Match),
    ("cow_flow_sensitive_alias.gg", Match),
    ("cow_for_amp_resource_elem_writethrough.gg", Exclude),
    ("cow_for_amp_vector_alias_root.gg", Exclude),
    ("cow_for_amp_vector_field_writethrough.gg", Exclude),
    ("cow_for_bare_resource_elem_materialize.gg", Match),
    ("cow_for_bare_vector_control.gg", Match),
    ("cow_for_enumerate_amp_alias_root.gg", Exclude),
    ("cow_for_enumerate_amp_recv_wrap.gg", Exclude),
    ("cow_for_enumerate_amp_writethrough.gg", Exclude),
    ("cow_for_enumerate_bare_resource_materialize.gg", Exclude),
    ("cow_for_zero_trip_body_kill_control.gg", Match),
    ("cow_generic_equip_mutator_view_uaf.gg", Equip),
    ("cow_generic_equip_named_recv.gg", Equip),
    ("cow_getref_dict_writethrough.gg", Exclude),
    ("cow_getref_writethrough_resource.gg", Match),
    ("cow_index_field_assign_loop_push.gg", Match),
    ("cow_index_nested_assign_loop_push.gg", Match),
    ("cow_index_proj_alias.gg", Match),
    ("cow_index_proj_caller_untouched.gg", Equip),
    ("cow_index_proj_mut_writethrough.gg", Equip),
    ("cow_index_proj_rebind.gg", Match),
    ("cow_indexed_element_survives_root_growth.gg", Match),
    ("cow_lazy_compound.gg", Match),
    ("cow_lazy_d1_alias.gg", Match),
    ("cow_lazy_d1_alias_deadpath.gg", Match),
    ("cow_lazy_d1_alias_takenpath.gg", Match),
    ("cow_lazy_d1_movesteal.gg", Match),
    ("cow_lazy_escape_return.gg", Match),
    ("cow_lazy_fieldpath_excluded.gg", Match),
    ("cow_lazy_index_slice_join.gg", Match),
    ("cow_lazy_method_arg.gg", Equip),
    ("cow_lazy_move_bind.gg", Match),
    ("cow_lazy_move_consume.gg", Match),
    ("cow_lazy_move_reassign.gg", Match),
    ("cow_lazy_multisite.gg", Match),
    ("cow_lazy_mut_borrow_write.gg", Match),
    ("cow_lazy_reassign_source.gg", Match),
    ("cow_lazy_selfref_concat_poke.gg", Match),
    ("cow_lazy_severorder.gg", Match),
    ("cow_lazy_staletag.gg", Match),
    ("cow_lazy_substring_named_bind.gg", Match),
    ("cow_lazy_w3b_arg_temp.gg", Match),
    ("cow_lazy_w3b_concat_temp.gg", Match),
    ("cow_lazy_w3c_arg_temp.gg", Match),
    ("cow_lazy_w3c_named_bind.gg", Match),
    ("cow_lazy_w3d_for_string.gg", Match),
    ("cow_loop_bare_param_comprehension.gg", Exclude),
    ("cow_loop_bare_param_comprehension_matrix.gg", Exclude),
    ("cow_loop_bare_param_for_else.gg", Exclude),
    ("cow_loop_bare_param_if_branch.gg", Match),
    ("cow_loop_bare_param_index_assign.gg", Match),
    ("cow_loop_bare_param_match_scrutinee.gg", Match),
    ("cow_loop_bare_param_materialize.gg", Match),
    ("cow_loop_bare_param_push_char.gg", Exclude),
    ("cow_loop_bare_param_tuple_receiver.gg", Match),
    ("cow_loop_bare_param_while_cond.gg", Match),
    ("cow_loop_body_local_move.gg", Match),
    ("cow_loop_borrow_propagation.gg", Match),
    ("cow_loop_invariant_owned_name_push_control.gg", Exclude),
    ("cow_materialization_points.gg", Match),
    ("cow_meta_for_zero_trip_body_kill.gg", Exclude),
    ("cow_meta_while_false_guard_body_kill.gg", Exclude),
    ("cow_method_arg_builtin_push.gg", Match),
    ("cow_method_arg_named_recv_same_coll.gg", Match),
    ("cow_method_arg_same_coll.gg", Equip),
    ("cow_move_bind_element_borrow.gg", Match),
    ("cow_move_clear_element_borrow.gg", Match),
    ("cow_move_realloc_element_borrow.gg", Match),
    ("cow_move_reassign_element_borrow.gg", Match),
    ("cow_multilevel_3level_index_field.gg", Match),
    ("cow_multilevel_fieldpath_root.gg", Match),
    ("cow_multilevel_index_field_assign.gg", Match),
    ("cow_multilevel_triple_index_assign.gg", Match),
    ("cow_named_recv_gate_name_collision.gg", Equip),
    ("cow_named_recv_gate_projected_name_collision.gg", Equip),
    ("cow_named_recv_mutator.gg", Equip),
    ("cow_named_recv_readonly.gg", Equip),
    ("cow_named_recv_transitive_mutator.gg", Equip),
    ("cow_nested_field_mutation.gg", Match),
    ("cow_nested_projection.gg", Equip),
    ("cow_p3_alias_chain_mutate.gg", Equip),
    ("cow_p3_cond_nested_mutate.gg", ReportOnly),
    ("cow_p3_field_path_mutate.gg", ReportOnly),
    ("cow_p3_index_mutate.gg", Equip),
    ("cow_p3_match_nested_mutate.gg", ReportOnly),
    ("cow_p3_readonly_borrow.gg", ReportOnly),
    ("cow_param_alias_reassign.gg", Match),
    ("cow_rescue_mutation_in_container_literal.gg", Exclude),
    ("cow_rescue_mutation_in_control_flow_expr.gg", Exclude),
    ("cow_rescue_mutation_in_operand_position.gg", Exclude),
    ("cow_rescue_mutation_inside_assert.gg", Exclude),
    ("cow_rescue_mutation_through_getchain_receiver.gg", Exclude),
    ("cow_rhs_index_assign.gg", Match),
    ("cow_rhs_same_coll_nested.gg", Match),
    ("cow_rhs_same_coll_single.gg", Match),
    ("cow_rhs_self_row.gg", Match),
    ("cow_scope_bare_param_amp_guard.gg", Match),
    ("cow_scope_bare_param_elif_cond.gg", Match),
    ("cow_scope_bare_param_elif_cond_then.gg", Match),
    ("cow_scope_bare_param_if_both.gg", Match),
    ("cow_scope_bare_param_if_elif.gg", Match),
    ("cow_scope_bare_param_if_else.gg", Match),
    ("cow_scope_bare_param_match_arm.gg", Match),
    ("cow_scope_bare_param_nested_if_loop.gg", Match),
    ("cow_scope_exit_alias.gg", Match),
    ("cow_self_generic_materialize.gg", Equip),
    ("cow_self_scratch_fstring.gg", Equip),
    ("cow_self_scratch_read.gg", Equip),
    ("cow_self_value_field_materialize.gg", Equip),
    ("cow_self_value_push_materialize.gg", Equip),
    ("cow_set_comprehension_invariant_in_condition.gg", Exclude),
    ("cow_set_string_clone.gg", Match),
    ("cow_struct_bare_assign.gg", Match),
    ("cow_struct_sever_on_mutation.gg", Match),
    ("cow_taint_compound_projected.gg", Equip),
    ("cow_taint_formation_param.gg", Equip),
    ("cow_taint_formation_self.gg", Equip),
    ("cow_taint_getchain_compound.gg", Equip),
    ("cow_taint_getchain_firstlast.gg", Equip),
    ("cow_taint_getchain_formation.gg", Equip),
    ("cow_taint_getchain_receiver.gg", Equip),
    ("cow_taint_getchain_user_get_ok.gg", Equip),
    ("cow_taint_getchain_vector.gg", Equip),
    ("cow_taint_pop_value_pos.gg", Equip),
    ("cow_taint_self_builtin.gg", Equip),
    ("cow_taint_self_field_write.gg", Equip),
    ("cow_taint_underscore_param.gg", Equip),
    ("cow_taint_whole_amp_param.gg", Equip),
    ("cow_taint_whole_amp_self.gg", Equip),
    ("cow_test_body_view_survives_realloc.gg", Exclude),
    ("cow_trait_amp_self_field_writethrough.gg", Equip),
    ("cow_trait_default_view_survives_realloc.gg", Equip),
    ("cow_trait_plain_self_collection_materialize.gg", Equip),
    ("cow_trait_plain_self_field_materialize.gg", Equip),
    ("cow_transitive_alias.gg", Match),
    ("cow_typed_binding_borrow.gg", Match),
    ("cow_user_mutator_fstring_interpolation.gg", Equip),
    ("cow_user_mutator_meta_generated_arm.gg", Equip),
    ("cow_user_mutator_rename_invariance.gg", Equip),
    ("cow_user_mutator_two_types_same_name.gg", Equip),
    ("cow_value_index_bare_mut_recv_writethrough.gg", Equip),
    ("cow_value_index_field_writethrough.gg", Exclude),
    ("cow_value_index_nested_field_store.gg", Match),
    ("cow_value_index_nested_mut_recv_writethrough.gg", Equip),
    ("cow_view_into_owned_collection_survives_growth.gg", Match),
    ("deadwrite_build_lock.gg", ReportOnly),
    ("deadwrite_ok_atomic_add.gg", Exclude),
    ("deadwrite_ok_branch_sibling_read.gg", ReportOnly),
    ("deadwrite_ok_copy_struct.gg", ReportOnly),
    ("deadwrite_ok_fstring_read.gg", ReportOnly),
    ("deadwrite_ok_loop_read_before_write.gg", Match),
    ("deadwrite_ok_match_scrutinee.gg", ReportOnly),
    ("deadwrite_ok_mut_param.gg", ReportOnly),
    ("deadwrite_ok_read_only.gg", ReportOnly),
    ("deadwrite_ok_rebind.gg", Match),
    ("deadwrite_ok_scratch_read.gg", ReportOnly),
    ("deadwrite_ok_underscore.gg", ReportOnly),
    ("deadwrite_ok_value_pop.gg", ReportOnly),
    ("deadwrite_ok_while_drain.gg", Match),
    ("deadwrite_warn_branch_read_then_write.gg", ReportOnly),
    ("deadwrite_warn_chained_stmt.gg", ReportOnly),
    ("deadwrite_warn_compound.gg", Match),
    ("deadwrite_warn_early_return.gg", ReportOnly),
    ("deadwrite_warn_field_assign.gg", ReportOnly),
    ("deadwrite_warn_index_assign.gg", ReportOnly),
    ("deadwrite_warn_loop_write.gg", ReportOnly),
    ("deadwrite_warn_nested_field.gg", ReportOnly),
    ("deadwrite_warn_push.gg", ReportOnly),
    ("deadwrite_warn_self.gg", Equip),
    ("deadwrite_warn_string_push.gg", ReportOnly),
    ("deadwrite_warn_user_method.gg", Equip),
];

/// REPORT-ONLY subset of corpus_b1.
pub const GGDEF_CORPUS_B1_REPORT_ONLY: &[&str] = &[
    "cow_closure_deferred_mutate.gg",
    "cow_p3_cond_nested_mutate.gg",
    "cow_p3_field_path_mutate.gg",
    "cow_p3_match_nested_mutate.gg",
    "cow_p3_readonly_borrow.gg",
    "deadwrite_build_lock.gg",
    "deadwrite_ok_branch_sibling_read.gg",
    "deadwrite_ok_copy_struct.gg",
    "deadwrite_ok_fstring_read.gg",
    "deadwrite_ok_match_scrutinee.gg",
    "deadwrite_ok_mut_param.gg",
    "deadwrite_ok_read_only.gg",
    "deadwrite_ok_scratch_read.gg",
    "deadwrite_ok_underscore.gg",
    "deadwrite_ok_value_pop.gg",
    "deadwrite_warn_branch_read_then_write.gg",
    "deadwrite_warn_chained_stmt.gg",
    "deadwrite_warn_early_return.gg",
    "deadwrite_warn_field_assign.gg",
    "deadwrite_warn_index_assign.gg",
    "deadwrite_warn_loop_write.gg",
    "deadwrite_warn_nested_field.gg",
    "deadwrite_warn_push.gg",
    "deadwrite_warn_string_push.gg",
];
