use std::fmt::Write;

use crate::ir::instructions::*;
use crate::ir::types::*;
use crate::ir::{Function, Module};

/// Minimal C preamble for the GIR pipeline.
/// Only includes what Phase 1 needs (no collections, no ownership, no async).
const GIR_PREAMBLE: &str = r#"// Generated by Gorget compiler (GIR pipeline)
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
"#;

/// C reserved words and type names that cannot be used as identifiers.
const C_RESERVED: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if",
    "inline", "int", "long", "register", "restrict", "return", "short",
    "signed", "sizeof", "static", "struct", "switch", "typedef", "union",
    "unsigned", "void", "volatile", "while", "_Bool", "_Complex", "_Imaginary",
    // Common types from stdint/stdbool
    "bool", "true", "false", "int8_t", "int16_t", "int32_t", "int64_t",
    "uint8_t", "uint16_t", "uint32_t", "uint64_t",
];

/// Mangle a function name to avoid C keyword conflicts.
fn mangle_name(name: &str) -> String {
    if name == "main" {
        return name.to_string();
    }
    if C_RESERVED.contains(&name) {
        format!("gg_{name}")
    } else {
        name.to_string()
    }
}

/// Translate a GIR Module into a compilable C string.
pub fn generate_c(module: &Module) -> String {
    let mut out = String::with_capacity(4096);

    // Preamble
    out.push_str(GIR_PREAMBLE);
    out.push('\n');

    // Forward declarations for all functions
    for func in &module.functions {
        emit_forward_decl(&mut out, func, &module.type_registry);
    }
    out.push('\n');

    // Function definitions
    for func in &module.functions {
        emit_function(&mut out, func, &module.type_registry);
        out.push('\n');
    }

    out
}

/// Emit a forward declaration for a function.
fn emit_forward_decl(out: &mut String, func: &Function, registry: &TypeRegistry) {
    if func.name == "main" {
        return; // main doesn't need a forward decl
    }

    let c_name = mangle_name(&func.name);
    let ret_type = format_type(func.return_type, registry);
    let _ = write!(out, "{ret_type} {c_name}(");

    if func.params.is_empty() {
        out.push_str("void");
    } else {
        for (i, &param_type) in func.params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let c_type = format_type(param_type, registry);
            // Use _N naming so body instructions can reference them
            let _ = write!(out, "{c_type} _{}", i + 1);
        }
    }

    out.push_str(");\n");
}

/// Emit a complete function definition.
fn emit_function(out: &mut String, func: &Function, registry: &TypeRegistry) {
    let is_main = func.name == "main";

    // Function signature
    if is_main {
        out.push_str("int main(int argc, char** argv) {\n");
    } else {
        let c_name = mangle_name(&func.name);
        let ret_type = format_type(func.return_type, registry);
        let _ = write!(out, "{ret_type} {c_name}(");

        if func.params.is_empty() {
            out.push_str("void");
        } else {
            for (i, &param_type) in func.params.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let c_type = format_type(param_type, registry);
                // Use _N naming to match GIR local references
                let _ = write!(out, "{c_type} _{}", i + 1);
            }
        }

        out.push_str(") {\n");
    }

    // Local variable declarations (skip _0 for void, skip params)
    let num_params = func.params.len();
    let return_is_void = func.return_type == UNIT_TYPE && !is_main;

    for (i, local) in func.locals.iter().enumerate() {
        let local_id = i;

        // Skip param locals (they're the function parameters)
        if local_id >= 1 && local_id <= num_params {
            continue;
        }

        // Skip return place for void functions
        if local_id == 0 && return_is_void {
            continue;
        }

        // Skip Unit-typed locals
        if local.type_id == UNIT_TYPE {
            continue;
        }

        let c_type = format_type(local.type_id, registry);
        if let Some(ref hint) = local.name_hint {
            let _ = writeln!(out, "    {c_type} _{local_id}; /* {hint} */");
        } else {
            let _ = writeln!(out, "    {c_type} _{local_id};");
        }
    }

    // Emit `goto bb0;` to start
    if !func.blocks.is_empty() {
        out.push_str("    goto bb0;\n");
    }

    // Emit basic blocks
    for (i, block) in func.blocks.iter().enumerate() {
        let _ = writeln!(out, "    bb{i}: {{");

        for inst in &block.instructions {
            emit_instruction(out, inst, func, registry);
        }

        if let Some(ref term) = block.terminator {
            emit_terminator(out, term, func, registry);
        }

        out.push_str("    }\n");
    }

    out.push_str("}\n");
}

/// Emit a single instruction as C code.
fn emit_instruction(out: &mut String, inst: &Instruction, func: &Function, registry: &TypeRegistry) {
    match inst {
        Instruction::Assign { dst, value } => {
            let dst_str = format_place(dst);
            let val_str = format_operand(value, func, registry);
            let _ = writeln!(out, "        {dst_str} = {val_str};");
        }

        Instruction::BinOp { dst, op, type_id, lhs, rhs } => {
            let c_type = format_type(*type_id, registry);
            let op_str = format_binop(*op);
            let lhs_str = format_operand(lhs, func, registry);
            let rhs_str = format_operand(rhs, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {lhs_str} {op_str} {rhs_str};", id = dst.0);
        }

        Instruction::UnOp { dst, op, type_id, operand } => {
            let c_type = format_type(*type_id, registry);
            let op_str = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
                UnOp::BitNot => "~",
            };
            let val_str = format_operand(operand, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {op_str}{val_str};", id = dst.0);
        }

        Instruction::Cmp { dst, op, lhs, rhs, .. } => {
            let op_str = format_cmpop(*op);
            let lhs_str = format_operand(lhs, func, registry);
            let rhs_str = format_operand(rhs, func, registry);
            let _ = writeln!(out, "        bool _{id} = {lhs_str} {op_str} {rhs_str};", id = dst.0);
        }

        Instruction::Call { dst, func: func_name, args } => {
            let c_name = mangle_name(func_name);
            let args_str = format_args(args, func, registry);
            if let Some(dst_id) = dst {
                let c_type = format_local_type(func, dst_id.0 as usize, registry);
                let _ = writeln!(out, "        {c_type} _{id} = {c_name}({args_str});", id = dst_id.0);
            } else {
                let _ = writeln!(out, "        {c_name}({args_str});");
            }
        }

        Instruction::CallExtern { dst, func: func_name, args } => {
            let args_str = format_args(args, func, registry);
            if let Some(dst_id) = dst {
                let c_type = format_local_type(func, dst_id.0 as usize, registry);
                let _ = writeln!(out, "        {c_type} _{id} = {func_name}({args_str});", id = dst_id.0);
            } else {
                let _ = writeln!(out, "        {func_name}({args_str});");
            }
        }

        Instruction::Nop => {
            out.push_str("        /* nop */\n");
        }

        // Phase 1: skip ownership, heap, aggregate, cast instructions
        _ => {
            out.push_str("        /* unhandled instruction */\n");
        }
    }
}

/// Emit a terminator as C code.
fn emit_terminator(out: &mut String, term: &Terminator, func: &Function, registry: &TypeRegistry) {
    match term {
        Terminator::Return(value) => {
            let is_main = func.name == "main";
            let return_is_void = func.return_type == UNIT_TYPE && !is_main;

            if return_is_void {
                out.push_str("        return;\n");
            } else if is_main {
                // For main, return _0
                out.push_str("        return _0;\n");
            } else {
                match value {
                    Operand::Constant(Constant::Unit) => {
                        out.push_str("        return;\n");
                    }
                    _ => {
                        let val_str = format_operand(value, func, registry);
                        let _ = writeln!(out, "        return {val_str};");
                    }
                }
            }
        }

        Terminator::Jump(target) => {
            let _ = writeln!(out, "        goto bb{};", target.0);
        }

        Terminator::Branch { cond, then_block, else_block } => {
            let cond_str = format_operand(cond, func, registry);
            let _ = writeln!(
                out,
                "        if ({cond_str}) goto bb{}; else goto bb{};",
                then_block.0, else_block.0
            );
        }

        Terminator::Switch { value, cases, default } => {
            let val_str = format_operand(value, func, registry);
            let _ = writeln!(out, "        switch ({val_str}) {{");
            for (val, target) in cases {
                let _ = writeln!(out, "            case {val}: goto bb{};", target.0);
            }
            let _ = writeln!(out, "            default: goto bb{};", default.0);
            out.push_str("        }\n");
        }

        Terminator::Unreachable => {
            out.push_str("        __builtin_unreachable();\n");
        }

        Terminator::Invoke { .. } => {
            out.push_str("        /* unhandled invoke */\n");
        }
    }
}

/// Format a GIR type as a C type string.
fn format_type(type_id: TypeId, registry: &TypeRegistry) -> String {
    if type_id == BOOL_TYPE {
        return "bool".to_string();
    }
    if type_id == I8_TYPE {
        return "int8_t".to_string();
    }
    if type_id == I16_TYPE {
        return "int16_t".to_string();
    }
    if type_id == I32_TYPE {
        return "int32_t".to_string();
    }
    if type_id == I64_TYPE {
        return "int64_t".to_string();
    }
    if type_id == U8_TYPE {
        return "uint8_t".to_string();
    }
    if type_id == U16_TYPE {
        return "uint16_t".to_string();
    }
    if type_id == U32_TYPE {
        return "uint32_t".to_string();
    }
    if type_id == U64_TYPE {
        return "uint64_t".to_string();
    }
    if type_id == F32_TYPE {
        return "float".to_string();
    }
    if type_id == F64_TYPE {
        return "double".to_string();
    }
    if type_id == UNIT_TYPE {
        return "void".to_string();
    }

    // Non-primitive: look up in registry
    if let Some(gir_type) = registry.get(type_id) {
        match gir_type {
            GirType::Ptr(inner) => {
                if *inner == U8_TYPE {
                    return "const char*".to_string();
                }
                format!("const {}*", format_type(*inner, registry))
            }
            GirType::MutPtr(inner) => {
                format!("{}*", format_type(*inner, registry))
            }
            GirType::Named(name) => name.clone(),
            _ => "int64_t".to_string(), // fallback
        }
    } else {
        "int64_t".to_string() // fallback
    }
}

/// Format an operand as a C expression.
fn format_operand(operand: &Operand, func: &Function, registry: &TypeRegistry) -> String {
    match operand {
        Operand::Copy(place) | Operand::Move(place) => format_place(place),

        Operand::Constant(constant) => format_constant(constant, func, registry),
    }
}

/// Format a place as a C lvalue.
fn format_place(place: &Place) -> String {
    let mut s = format!("_{}", place.local.0);
    for proj in &place.projections {
        match proj {
            Projection::Field(idx) => {
                let _ = write!(s, ".f{idx}");
            }
            Projection::Index(local) => {
                let _ = write!(s, "[_{}]", local.0);
            }
            Projection::Deref => {
                s = format!("(*{s})");
            }
        }
    }
    s
}

/// Format a constant as a C literal.
fn format_constant(constant: &Constant, _func: &Function, _registry: &TypeRegistry) -> String {
    match constant {
        Constant::Bool(b) => {
            // For bool in printf context, we need "true"/"false"
            // But as a general constant, just use true/false
            if *b { "true".to_string() } else { "false".to_string() }
        }
        Constant::I8(n) => format!("(int8_t){n}"),
        Constant::I16(n) => format!("(int16_t){n}"),
        Constant::I32(n) => format!("{n}"),
        Constant::I64(n) => {
            if *n > i32::MAX as i64 || *n < i32::MIN as i64 {
                format!("{n}LL")
            } else {
                format!("{n}")
            }
        }
        Constant::U8(n) => format!("(uint8_t){n}"),
        Constant::U16(n) => format!("(uint16_t){n}"),
        Constant::U32(n) => format!("{n}u"),
        Constant::U64(n) => format!("{n}ULL"),
        Constant::F32(n) => format_float(*n as f64),
        Constant::F64(n) => format_float(*n),
        Constant::Str(s) => format!("\"{}\"", escape_c_string(s)),
        Constant::Null => "NULL".to_string(),
        Constant::Unit => "/* unit */".to_string(),
    }
}

/// Format a float with a guaranteed decimal point.
fn format_float(n: f64) -> String {
    let s = format!("{n}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

/// Escape a string for C string literal context.
fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c => out.push(c),
        }
    }
    out
}

/// Format function call arguments.
fn format_args(args: &[Operand], func: &Function, registry: &TypeRegistry) -> String {
    let mut parts = Vec::new();
    for (i, arg) in args.iter().enumerate() {
        let mut arg_str = format_operand(arg, func, registry);

        // Special handling for bool args in printf: need "true"/"false" conversion
        // Check if this is a printf call arg (not the format string) and the arg is a bool local
        if i > 0 {
            if let Operand::Copy(place) | Operand::Move(place) = arg {
                let local_idx = place.local.0 as usize;
                if local_idx < func.locals.len() && func.locals[local_idx].type_id == BOOL_TYPE {
                    arg_str = format!("({arg_str} ? \"true\" : \"false\")");
                }
            }
        }

        parts.push(arg_str);
    }
    parts.join(", ")
}

/// Look up a local's type and format it.
fn format_local_type(func: &Function, local_idx: usize, registry: &TypeRegistry) -> String {
    if local_idx < func.locals.len() {
        format_type(func.locals[local_idx].type_id, registry)
    } else {
        "int64_t".to_string()
    }
}

/// Format a binary operator as its C symbol.
fn format_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Pow => "/* pow */",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

/// Format a comparison operator as its C symbol.
fn format_cmpop(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Ne => "!=",
        CmpOp::Lt => "<",
        CmpOp::Le => "<=",
        CmpOp::Gt => ">",
        CmpOp::Ge => ">=",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::builder::FunctionBuilder;

    #[test]
    fn emit_empty_main() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new("main", I32_TYPE, &[]);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::const_i32(0));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("int main(int argc, char** argv)"));
        assert!(c_code.contains("return _0;"));
    }

    #[test]
    fn emit_arithmetic() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new(
            "add",
            I64_TYPE,
            &[(I64_TYPE, Some("a")), (I64_TYPE, Some("b"))],
        );
        let sum = b.bin_op(
            BinOp::Add,
            I64_TYPE,
            FunctionBuilder::copy(LocalId(1)),
            FunctionBuilder::copy(LocalId(2)),
        );
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(sum));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("int64_t add(int64_t _1, int64_t _2)"));
        assert!(c_code.contains("+"));
        assert!(c_code.contains("return _0;"));
    }

    #[test]
    fn emit_basic_blocks() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new(
            "f",
            I64_TYPE,
            &[(I64_TYPE, Some("x"))],
        );

        let then_bb = b.new_block();
        let else_bb = b.new_block();
        let merge_bb = b.new_block();

        let cond = b.cmp(
            CmpOp::Gt,
            I64_TYPE,
            FunctionBuilder::copy(LocalId(1)),
            FunctionBuilder::const_i64(0),
        );
        b.branch(FunctionBuilder::copy(cond), then_bb, else_bb);

        b.switch_to(then_bb);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(LocalId(1)));
        b.jump(merge_bb);

        b.switch_to(else_bb);
        let neg = b.un_op(UnOp::Neg, I64_TYPE, FunctionBuilder::copy(LocalId(1)));
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(neg));
        b.jump(merge_bb);

        b.switch_to(merge_bb);
        b.ret(FunctionBuilder::copy(LocalId(0)));

        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("bb0:"));
        assert!(c_code.contains("bb1:"));
        assert!(c_code.contains("bb2:"));
        assert!(c_code.contains("bb3:"));
        assert!(c_code.contains("goto bb"));
        assert!(c_code.contains("if ("));
    }
}
