use std::fmt::Write;

use crate::ir::instructions::*;
use crate::ir::types::*;
use crate::ir::{Function, Global, GlobalInit, Module};

/// Minimal C preamble for the GIR pipeline.
/// Only includes what Phase 1 needs (no collections, no ownership, no async).
const GIR_PREAMBLE: &str = r#"// Generated by Gorget compiler (GIR pipeline)
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
"#;

/// C reserved words and type names that cannot be used as identifiers.
const C_RESERVED: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if",
    "inline", "int", "long", "register", "restrict", "return", "short",
    "signed", "sizeof", "static", "struct", "switch", "typedef", "union",
    "unsigned", "void", "volatile", "while", "_Bool", "_Complex", "_Imaginary",
    // Common types from stdint/stdbool
    "bool", "true", "false", "int8_t", "int16_t", "int32_t", "int64_t",
    "uint8_t", "uint16_t", "uint32_t", "uint64_t",
];

/// Mangle a function name to avoid C keyword conflicts.
fn mangle_name(name: &str) -> String {
    if name == "main" {
        return name.to_string();
    }
    if C_RESERVED.contains(&name) {
        format!("gg_{name}")
    } else {
        name.to_string()
    }
}

/// Translate a GIR Module into a compilable C string.
pub fn generate_c(module: &Module) -> String {
    let mut out = String::with_capacity(4096);

    // Preamble
    out.push_str(GIR_PREAMBLE);
    out.push('\n');

    // Type definitions (structs and enums)
    emit_type_definitions(&mut out, module);

    // Global constants
    emit_globals(&mut out, module);

    // Forward declarations for all functions
    for func in &module.functions {
        emit_forward_decl(&mut out, func, &module.type_registry);
    }
    out.push('\n');

    // Function definitions
    for func in &module.functions {
        emit_function(&mut out, func, &module.type_registry);
        out.push('\n');
    }

    out
}

/// Emit type definitions (struct typedefs and enum tagged unions).
fn emit_type_definitions(out: &mut String, module: &Module) {
    let type_defs = module.type_registry.type_defs();
    if type_defs.is_empty() {
        return;
    }

    // Forward declare all struct types first (for mutual references)
    for def in type_defs {
        match &def.kind {
            TypeDefKind::Struct(_) => {
                let _ = writeln!(out, "typedef struct {name} {name};", name = def.name);
            }
            TypeDefKind::Enum(_) => {
                let _ = writeln!(out, "typedef struct {name} {name};", name = def.name);
            }
            TypeDefKind::Alias(_) => {}
        }
    }
    out.push('\n');

    // Emit full struct definitions
    for def in type_defs {
        match &def.kind {
            TypeDefKind::Struct(s) => {
                let _ = writeln!(out, "struct {name} {{", name = def.name);
                for field in &s.fields {
                    let decl = format_field_decl(field.type_id, &field.name, &module.type_registry);
                    let _ = writeln!(out, "    {decl};");
                }
                out.push_str("};\n\n");
            }
            TypeDefKind::Enum(e) => {
                let _ = writeln!(out, "struct {name} {{", name = def.name);
                out.push_str("    int tag;\n");
                out.push_str("    union {\n");
                for variant in &e.variants {
                    if variant.fields.is_empty() {
                        // Unit variant — no data
                        continue;
                    }
                    let _ = writeln!(out, "        struct {{");
                    for field in &variant.fields {
                        let c_type = format_type(field.type_id, &module.type_registry);
                        let _ = writeln!(out, "            {c_type} {name};", name = field.name);
                    }
                    let _ = writeln!(out, "        }} {name};", name = variant.name);
                }
                out.push_str("    } data;\n");
                out.push_str("};\n\n");
            }
            TypeDefKind::Alias(target) => {
                let c_type = format_type(*target, &module.type_registry);
                let _ = writeln!(out, "typedef {c_type} {name};\n", name = def.name);
            }
        }
    }
}

/// Emit global constant/variable definitions.
fn emit_globals(out: &mut String, module: &Module) {
    for global in &module.globals {
        emit_global(out, global, &module.type_registry);
    }
    if !module.globals.is_empty() {
        out.push('\n');
    }
}

/// Emit a single global variable/constant.
fn emit_global(out: &mut String, global: &Global, registry: &TypeRegistry) {
    let c_type = format_type(global.type_id, registry);
    match &global.init {
        GlobalInit::Zeroed => {
            let _ = writeln!(out, "static {c_type} {name} = {{0}};", name = global.name);
        }
        GlobalInit::Struct { type_name, fields } => {
            let _ = write!(out, "static const {c_type} {name} = ({type_name}){{", name = global.name);
            for (i, (fname, init)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let _ = write!(out, ".{fname} = ");
                emit_global_init(out, init);
            }
            out.push_str("};\n");
        }
        GlobalInit::FnRef(fn_name) => {
            let mangled = mangle_name(fn_name);
            let _ = writeln!(out, "static const {c_type} {name} = &{mangled};", name = global.name);
        }
        GlobalInit::Bytes(bytes) => {
            let _ = write!(out, "static const uint8_t {name}[] = {{", name = global.name);
            for (i, b) in bytes.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let _ = write!(out, "0x{b:02x}");
            }
            out.push_str("};\n");
        }
    }
}

/// Emit a global initializer expression.
fn emit_global_init(out: &mut String, init: &GlobalInit) {
    match init {
        GlobalInit::Zeroed => out.push_str("{0}"),
        GlobalInit::FnRef(fn_name) => {
            let mangled = mangle_name(fn_name);
            let _ = write!(out, "&{mangled}");
        }
        GlobalInit::Struct { type_name, fields } => {
            let _ = write!(out, "({type_name}){{");
            for (i, (fname, sub_init)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let _ = write!(out, ".{fname} = ");
                emit_global_init(out, sub_init);
            }
            out.push('}');
        }
        GlobalInit::Bytes(_) => out.push_str("/* bytes */"),
    }
}

/// Emit a forward declaration for a function.
fn emit_forward_decl(out: &mut String, func: &Function, registry: &TypeRegistry) {
    if func.name == "main" {
        return; // main doesn't need a forward decl
    }

    let c_name = mangle_name(&func.name);
    let ret_type = format_type(func.return_type, registry);
    let _ = write!(out, "{ret_type} {c_name}(");

    if func.params.is_empty() {
        out.push_str("void");
    } else {
        for (i, &param_type) in func.params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let c_type = format_type(param_type, registry);
            // Use _N naming so body instructions can reference them
            let _ = write!(out, "{c_type} _{}", i + 1);
        }
    }

    out.push_str(");\n");
}

/// Emit a complete function definition.
fn emit_function(out: &mut String, func: &Function, registry: &TypeRegistry) {
    let is_main = func.name == "main";

    // Function signature
    if is_main {
        out.push_str("int main(int argc, char** argv) {\n");
    } else {
        let c_name = mangle_name(&func.name);
        let ret_type = format_type(func.return_type, registry);
        let _ = write!(out, "{ret_type} {c_name}(");

        if func.params.is_empty() {
            out.push_str("void");
        } else {
            for (i, &param_type) in func.params.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let c_type = format_type(param_type, registry);
                // Use _N naming to match GIR local references
                let _ = write!(out, "{c_type} _{}", i + 1);
            }
        }

        out.push_str(") {\n");
    }

    // Local variable declarations (skip _0 for void, skip params)
    let num_params = func.params.len();
    let return_is_void = func.return_type == UNIT_TYPE && !is_main;

    for (i, local) in func.locals.iter().enumerate() {
        let local_id = i;

        // Skip param locals (they're the function parameters)
        if local_id >= 1 && local_id <= num_params {
            continue;
        }

        // Skip return place for void functions
        if local_id == 0 && return_is_void {
            continue;
        }

        // Skip Unit-typed locals
        if local.type_id == UNIT_TYPE {
            continue;
        }

        let c_type = format_type(local.type_id, registry);
        if let Some(ref hint) = local.name_hint {
            let _ = writeln!(out, "    {c_type} _{local_id}; /* {hint} */");
        } else {
            let _ = writeln!(out, "    {c_type} _{local_id};");
        }
    }

    // Emit `goto bb0;` to start
    if !func.blocks.is_empty() {
        out.push_str("    goto bb0;\n");
    }

    // Emit basic blocks
    for (i, block) in func.blocks.iter().enumerate() {
        let _ = writeln!(out, "    bb{i}: {{");

        for inst in &block.instructions {
            emit_instruction(out, inst, func, registry);
        }

        if let Some(ref term) = block.terminator {
            emit_terminator(out, term, func, registry);
        }

        out.push_str("    }\n");
    }

    out.push_str("}\n");
}

/// Emit a single instruction as C code.
fn emit_instruction(out: &mut String, inst: &Instruction, func: &Function, registry: &TypeRegistry) {
    match inst {
        Instruction::Assign { dst, value } => {
            let dst_str = format_place(dst, registry);
            let val_str = format_operand(value, func, registry);
            let _ = writeln!(out, "        {dst_str} = {val_str};");
        }

        Instruction::BinOp { dst, op, type_id, lhs, rhs } => {
            let c_type = format_type(*type_id, registry);
            let op_str = format_binop(*op);
            let lhs_str = format_operand(lhs, func, registry);
            let rhs_str = format_operand(rhs, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {lhs_str} {op_str} {rhs_str};", id = dst.0);
        }

        Instruction::UnOp { dst, op, type_id, operand } => {
            let c_type = format_type(*type_id, registry);
            let op_str = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
                UnOp::BitNot => "~",
            };
            let val_str = format_operand(operand, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {op_str}{val_str};", id = dst.0);
        }

        Instruction::Cmp { dst, op, lhs, rhs, .. } => {
            let op_str = format_cmpop(*op);
            let lhs_str = format_operand(lhs, func, registry);
            let rhs_str = format_operand(rhs, func, registry);
            let _ = writeln!(out, "        bool _{id} = {lhs_str} {op_str} {rhs_str};", id = dst.0);
        }

        Instruction::Call { dst, func: func_name, args } => {
            let c_name = mangle_name(func_name);
            let args_str = format_args(args, func, registry);
            if let Some(dst_id) = dst {
                let c_type = format_local_type(func, dst_id.0 as usize, registry);
                let _ = writeln!(out, "        {c_type} _{id} = {c_name}({args_str});", id = dst_id.0);
            } else {
                let _ = writeln!(out, "        {c_name}({args_str});");
            }
        }

        Instruction::CallExtern { dst, func: func_name, args } => {
            let args_str = format_args(args, func, registry);
            if let Some(dst_id) = dst {
                let c_type = format_local_type(func, dst_id.0 as usize, registry);
                let _ = writeln!(out, "        {c_type} _{id} = {func_name}({args_str});", id = dst_id.0);
            } else {
                let _ = writeln!(out, "        {func_name}({args_str});");
            }
        }

        // -- Aggregates (P2.0/P2.1) --
        Instruction::StructInit { dst, type_name, fields } => {
            let type_def = registry.get_type_def(type_name);
            let _ = write!(out, "        {type_name} _{id} = ({type_name}){{", id = dst.0);
            if let Some(def) = type_def {
                if let TypeDefKind::Struct(ref s) = def.kind {
                    for (i, (field_val, field_def)) in fields.iter().zip(s.fields.iter()).enumerate() {
                        if i > 0 {
                            out.push_str(", ");
                        }
                        let val = format_operand(field_val, func, registry);
                        let _ = write!(out, ".{name} = {val}", name = field_def.name);
                    }
                }
            } else {
                // Fallback: positional
                for (i, field_val) in fields.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    let val = format_operand(field_val, func, registry);
                    let _ = write!(out, "{val}");
                }
            }
            out.push_str("};\n");
        }

        Instruction::EnumInit { dst, type_name, variant, fields } => {
            let type_def = registry.get_type_def(type_name);
            let tag = if let Some(def) = type_def {
                if let TypeDefKind::Enum(ref e) = def.kind {
                    e.variants.iter().position(|v| v.name == *variant).unwrap_or(0)
                } else { 0 }
            } else { 0 };

            let _ = write!(out, "        {type_name} _{id} = ({type_name}){{.tag = {tag}", id = dst.0);
            if !fields.is_empty() {
                let _ = write!(out, ", .data.{variant} = {{");
                for (i, field_val) in fields.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    let val = format_operand(field_val, func, registry);
                    let _ = write!(out, "{val}");
                }
                out.push('}');
            }
            out.push_str("};\n");
        }

        Instruction::TupleInit { dst, elements } => {
            // Determine tuple type name from the local's type
            let local_type = if (dst.0 as usize) < func.locals.len() {
                format_type(func.locals[dst.0 as usize].type_id, registry)
            } else {
                "void".to_string()
            };
            let _ = write!(out, "        {local_type} _{id} = ({local_type}){{", id = dst.0);
            for (i, elem) in elements.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                let val = format_operand(elem, func, registry);
                let _ = write!(out, "._{i} = {val}");
            }
            out.push_str("};\n");
        }

        Instruction::TagOf { dst, operand } => {
            let val = format_operand(operand, func, registry);
            let _ = writeln!(out, "        int _{id} = {val}.tag;", id = dst.0);
        }

        Instruction::EnumFieldLoad { dst, base, variant, field } => {
            let base_str = format_place(base, registry);
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(
                out,
                "        {c_type} _{id} = {base_str}.data.{variant}._{field};",
                id = dst.0
            );
        }

        Instruction::FieldLoad { dst, base, field } => {
            let base_str = format_place(base, registry);
            // Look up field name from type def
            let field_name = resolve_field_name(func, base, *field, registry);
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {base_str}.{field_name};", id = dst.0);
        }

        Instruction::IndexLoad { dst, base, index } => {
            let base_str = format_place(base, registry);
            let idx_str = format_operand(index, func, registry);
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {base_str}[{idx_str}];", id = dst.0);
        }

        // -- Type conversions --
        Instruction::Cast { dst, target_type, value } => {
            let c_type = format_type(*target_type, registry);
            let val = format_operand(value, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = ({c_type}){val};", id = dst.0);
        }

        Instruction::BitCast { dst, target_type, value } => {
            let c_type = format_type(*target_type, registry);
            let val = format_operand(value, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = ({c_type}){val};", id = dst.0);
        }

        Instruction::PtrCast { dst, target_type, value } => {
            let c_type = format_type(*target_type, registry);
            let val = format_operand(value, func, registry);
            let _ = writeln!(out, "        {c_type} _{id} = ({c_type}){val};", id = dst.0);
        }

        // -- Ownership (P2.6) --
        Instruction::Borrow { dst, place } => {
            let place_str = format_place(place, registry);
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(out, "        {c_type} _{id} = &{place_str};", id = dst.0);
        }

        Instruction::BorrowMut { dst, place } => {
            let place_str = format_place(place, registry);
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(out, "        {c_type} _{id} = &{place_str};", id = dst.0);
        }

        Instruction::Drop { place } => {
            let place_str = format_place(place, registry);
            // Look up drop strategy from TypeDef
            let local_type = func.locals[place.local.0 as usize].type_id;
            let strategy = lookup_drop_strategy(local_type, registry);
            match strategy {
                DropStrategy::None => {
                    // No-op
                }
                DropStrategy::Trivial(ref fn_name) => {
                    let _ = writeln!(out, "        {fn_name}(&{place_str});");
                }
                DropStrategy::Custom(ref fn_name) => {
                    let _ = writeln!(out, "        {fn_name}(&{place_str});");
                }
                DropStrategy::Recursive => {
                    let _ = writeln!(out, "        /* recursive drop of {place_str} */");
                }
            }
        }

        Instruction::DropIfAlive { place } => {
            let place_str = format_place(place, registry);
            let local_type = func.locals[place.local.0 as usize].type_id;
            let type_name = format_type(local_type, registry);
            let strategy = lookup_drop_strategy(local_type, registry);
            match strategy {
                DropStrategy::None => {}
                DropStrategy::Trivial(ref fn_name) | DropStrategy::Custom(ref fn_name) => {
                    let _ = writeln!(out, "        if (memcmp(&{place_str}, &({type_name}){{0}}, sizeof({type_name})) != 0) {{");
                    let _ = writeln!(out, "            {fn_name}(&{place_str});");
                    out.push_str("        }\n");
                }
                DropStrategy::Recursive => {
                    let _ = writeln!(out, "        /* conditional recursive drop of {place_str} */");
                }
            }
        }

        Instruction::MoveZero { place } => {
            let place_str = format_place(place, registry);
            let local_type = func.locals[place.local.0 as usize].type_id;
            let type_name = format_type(local_type, registry);
            let _ = writeln!(out, "        memset(&{place_str}, 0, sizeof({type_name}));");
        }

        // -- Calls (P2.4) --
        Instruction::CallIndirect { dst, callee, args } => {
            let callee_str = format_operand(callee, func, registry);
            let args_str = format_args(args, func, registry);
            if let Some(dst_id) = dst {
                let c_type = format_local_type(func, dst_id.0 as usize, registry);
                let _ = writeln!(out, "        {c_type} _{id} = {callee_str}({args_str});", id = dst_id.0);
            } else {
                let _ = writeln!(out, "        {callee_str}({args_str});");
            }
        }

        // -- Heap --
        Instruction::HeapAlloc { dst, type_id, .. } => {
            let c_type = format_type(*type_id, registry);
            let _ = writeln!(out, "        {c_type}* _{id} = ({c_type}*)malloc(sizeof({c_type}));", id = dst.0);
        }

        Instruction::HeapAllocArray { dst, type_id, count, .. } => {
            let c_type = format_type(*type_id, registry);
            let count_str = format_operand(count, func, registry);
            let _ = writeln!(out, "        {c_type}* _{id} = ({c_type}*)malloc(sizeof({c_type}) * {count_str});", id = dst.0);
        }

        Instruction::Dealloc { ptr, .. } => {
            let ptr_str = format_operand(ptr, func, registry);
            let _ = writeln!(out, "        free({ptr_str});");
        }

        // -- Allocator --
        Instruction::LoadThreadLocal { dst, name } => {
            let c_type = format_local_type(func, dst.0 as usize, registry);
            let _ = writeln!(out, "        {c_type} _{id} = {name};", id = dst.0);
        }

        Instruction::PushAllocator { .. } => {
            out.push_str("        /* push allocator */\n");
        }

        Instruction::PopAllocator => {
            out.push_str("        /* pop allocator */\n");
        }

        Instruction::Nop => {
            out.push_str("        /* nop */\n");
        }
    }
}

/// Emit a terminator as C code.
fn emit_terminator(out: &mut String, term: &Terminator, func: &Function, registry: &TypeRegistry) {
    match term {
        Terminator::Return(value) => {
            let is_main = func.name == "main";
            let return_is_void = func.return_type == UNIT_TYPE && !is_main;

            if return_is_void {
                out.push_str("        return;\n");
            } else if is_main {
                // For main, return _0
                out.push_str("        return _0;\n");
            } else {
                match value {
                    Operand::Constant(Constant::Unit) => {
                        out.push_str("        return;\n");
                    }
                    _ => {
                        let val_str = format_operand(value, func, registry);
                        let _ = writeln!(out, "        return {val_str};");
                    }
                }
            }
        }

        Terminator::Jump(target) => {
            let _ = writeln!(out, "        goto bb{};", target.0);
        }

        Terminator::Branch { cond, then_block, else_block } => {
            let cond_str = format_operand(cond, func, registry);
            let _ = writeln!(
                out,
                "        if ({cond_str}) goto bb{}; else goto bb{};",
                then_block.0, else_block.0
            );
        }

        Terminator::Switch { value, cases, default } => {
            let val_str = format_operand(value, func, registry);
            let _ = writeln!(out, "        switch ({val_str}) {{");
            for (val, target) in cases {
                let _ = writeln!(out, "            case {val}: goto bb{};", target.0);
            }
            let _ = writeln!(out, "            default: goto bb{};", default.0);
            out.push_str("        }\n");
        }

        Terminator::Unreachable => {
            out.push_str("        __builtin_unreachable();\n");
        }

        Terminator::Invoke { .. } => {
            out.push_str("        /* unhandled invoke */\n");
        }
    }
}

/// Format a GIR type as a C type string.
fn format_type(type_id: TypeId, registry: &TypeRegistry) -> String {
    if type_id == BOOL_TYPE {
        return "bool".to_string();
    }
    if type_id == I8_TYPE {
        return "int8_t".to_string();
    }
    if type_id == I16_TYPE {
        return "int16_t".to_string();
    }
    if type_id == I32_TYPE {
        return "int32_t".to_string();
    }
    if type_id == I64_TYPE {
        return "int64_t".to_string();
    }
    if type_id == U8_TYPE {
        return "uint8_t".to_string();
    }
    if type_id == U16_TYPE {
        return "uint16_t".to_string();
    }
    if type_id == U32_TYPE {
        return "uint32_t".to_string();
    }
    if type_id == U64_TYPE {
        return "uint64_t".to_string();
    }
    if type_id == F32_TYPE {
        return "float".to_string();
    }
    if type_id == F64_TYPE {
        return "double".to_string();
    }
    if type_id == UNIT_TYPE {
        return "void".to_string();
    }

    // Non-primitive: look up in registry
    if let Some(gir_type) = registry.get(type_id) {
        match gir_type {
            GirType::Ptr(inner) => {
                if *inner == U8_TYPE {
                    return "const char*".to_string();
                }
                format!("const {}*", format_type(*inner, registry))
            }
            GirType::MutPtr(inner) => {
                format!("{}*", format_type(*inner, registry))
            }
            GirType::Named(name) => name.clone(),
            GirType::FnPtr { params, return_type } => {
                let ret = format_type(*return_type, registry);
                let params_str: Vec<String> = params.iter()
                    .map(|p| format_type(*p, registry))
                    .collect();
                format!("{ret}(*)({})", params_str.join(", "))
            }
            _ => "int64_t".to_string(), // fallback
        }
    } else {
        "int64_t".to_string() // fallback
    }
}

/// Format a struct field declaration as valid C.
///
/// Function pointer types need special syntax: `RetType (*name)(Params)` instead of
/// the standalone `RetType(*)(Params)` format.
fn format_field_decl(type_id: TypeId, field_name: &str, registry: &TypeRegistry) -> String {
    if let Some(GirType::FnPtr { params, return_type }) = registry.get(type_id) {
        let ret = format_type(*return_type, registry);
        let params_str: Vec<String> = params.iter()
            .map(|p| format_type(*p, registry))
            .collect();
        format!("{ret} (*{field_name})({})", params_str.join(", "))
    } else {
        let c_type = format_type(type_id, registry);
        format!("{c_type} {field_name}")
    }
}

/// Format an operand as a C expression.
fn format_operand(operand: &Operand, func: &Function, registry: &TypeRegistry) -> String {
    match operand {
        Operand::Copy(place) | Operand::Move(place) => format_place(place, registry),

        Operand::Constant(constant) => format_constant(constant, func, registry),
    }
}

/// Format a place as a C lvalue.
fn format_place(place: &Place, _registry: &TypeRegistry) -> String {
    let mut s = format!("_{}", place.local.0);
    for proj in &place.projections {
        match proj {
            Projection::Field(idx) => {
                // Try to look up field name from registry
                // For now use positional fallback — field_load instruction handles named fields
                let _ = write!(s, ".f{idx}");
            }
            Projection::Index(local) => {
                let _ = write!(s, "[_{}]", local.0);
            }
            Projection::Deref => {
                s = format!("(*{s})");
            }
        }
    }
    s
}

/// Resolve a field name from its index, looking up the TypeDef.
fn resolve_field_name(func: &Function, base: &Place, field_idx: u32, registry: &TypeRegistry) -> String {
    let local_type_id = func.locals[base.local.0 as usize].type_id;

    // Walk through projections to find the innermost type
    let mut current_type_id = local_type_id;
    for proj in &base.projections {
        match proj {
            Projection::Deref => {
                // Dereference pointer: Ptr(T) or MutPtr(T) → T
                if let Some(gir_type) = registry.get(current_type_id) {
                    match gir_type {
                        GirType::Ptr(inner) | GirType::MutPtr(inner) => {
                            current_type_id = *inner;
                        }
                        _ => {}
                    }
                }
            }
            Projection::Field(idx) => {
                if let Some(gir_type) = registry.get(current_type_id) {
                    if let GirType::Named(name) = gir_type {
                        if let Some(type_def) = registry.get_type_def(name) {
                            if let TypeDefKind::Struct(ref s) = type_def.kind {
                                if let Some(field) = s.fields.get(*idx as usize) {
                                    current_type_id = field.type_id;
                                }
                            }
                        }
                    }
                }
            }
            Projection::Index(_) => {}
        }
    }

    // Now resolve the final field name
    if let Some(gir_type) = registry.get(current_type_id) {
        if let GirType::Named(name) = gir_type {
            if let Some(type_def) = registry.get_type_def(name) {
                if let TypeDefKind::Struct(ref s) = type_def.kind {
                    if let Some(field) = s.fields.get(field_idx as usize) {
                        return field.name.clone();
                    }
                }
            }
        }
    }

    // Fallback to positional
    format!("f{field_idx}")
}

/// Look up a type's DropStrategy from the registry.
fn lookup_drop_strategy(type_id: TypeId, registry: &TypeRegistry) -> DropStrategy {
    if let Some(GirType::Named(name)) = registry.get(type_id) {
        if let Some(type_def) = registry.get_type_def(name) {
            return type_def.metadata.drop_strategy.clone();
        }
    }
    DropStrategy::None
}

/// Format a constant as a C literal.
fn format_constant(constant: &Constant, _func: &Function, _registry: &TypeRegistry) -> String {
    match constant {
        Constant::Bool(b) => {
            if *b { "true".to_string() } else { "false".to_string() }
        }
        Constant::I8(n) => format!("(int8_t){n}"),
        Constant::I16(n) => format!("(int16_t){n}"),
        Constant::I32(n) => format!("{n}"),
        Constant::I64(n) => {
            if *n > i32::MAX as i64 || *n < i32::MIN as i64 {
                format!("{n}LL")
            } else {
                format!("{n}")
            }
        }
        Constant::U8(n) => format!("(uint8_t){n}"),
        Constant::U16(n) => format!("(uint16_t){n}"),
        Constant::U32(n) => format!("{n}u"),
        Constant::U64(n) => format!("{n}ULL"),
        Constant::F32(n) => format_float(*n as f64),
        Constant::F64(n) => format_float(*n),
        Constant::Str(s) => format!("\"{}\"", escape_c_string(s)),
        Constant::Null => "NULL".to_string(),
        Constant::Unit => "/* unit */".to_string(),
        Constant::SizeOf(type_id) => {
            let c_type = format_type(*type_id, _registry);
            format!("sizeof({c_type})")
        }
    }
}

/// Format a float with a guaranteed decimal point.
fn format_float(n: f64) -> String {
    let s = format!("{n}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

/// Escape a string for C string literal context.
fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c => out.push(c),
        }
    }
    out
}

/// Format function call arguments.
fn format_args(args: &[Operand], func: &Function, registry: &TypeRegistry) -> String {
    let mut parts = Vec::new();
    for (i, arg) in args.iter().enumerate() {
        let mut arg_str = format_operand(arg, func, registry);

        // Special handling for bool args in printf: need "true"/"false" conversion
        // Check if this is a printf call arg (not the format string) and the arg is a bool local
        if i > 0 {
            if let Operand::Copy(place) | Operand::Move(place) = arg {
                let local_idx = place.local.0 as usize;
                if local_idx < func.locals.len() && func.locals[local_idx].type_id == BOOL_TYPE {
                    arg_str = format!("({arg_str} ? \"true\" : \"false\")");
                }
            }
        }

        parts.push(arg_str);
    }
    parts.join(", ")
}

/// Look up a local's type and format it.
fn format_local_type(func: &Function, local_idx: usize, registry: &TypeRegistry) -> String {
    if local_idx < func.locals.len() {
        format_type(func.locals[local_idx].type_id, registry)
    } else {
        "int64_t".to_string()
    }
}

/// Format a binary operator as its C symbol.
fn format_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Pow => "/* pow */",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

/// Format a comparison operator as its C symbol.
fn format_cmpop(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Ne => "!=",
        CmpOp::Lt => "<",
        CmpOp::Le => "<=",
        CmpOp::Gt => ">",
        CmpOp::Ge => ">=",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::builder::FunctionBuilder;

    #[test]
    fn emit_empty_main() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new("main", I32_TYPE, &[]);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::const_i32(0));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("int main(int argc, char** argv)"));
        assert!(c_code.contains("return _0;"));
    }

    #[test]
    fn emit_arithmetic() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new(
            "add",
            I64_TYPE,
            &[(I64_TYPE, Some("a")), (I64_TYPE, Some("b"))],
        );
        let sum = b.bin_op(
            BinOp::Add,
            I64_TYPE,
            FunctionBuilder::copy(LocalId(1)),
            FunctionBuilder::copy(LocalId(2)),
        );
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(sum));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("int64_t add(int64_t _1, int64_t _2)"));
        assert!(c_code.contains("+"));
        assert!(c_code.contains("return _0;"));
    }

    #[test]
    fn emit_basic_blocks() {
        let mut module = Module::new();
        let mut b = FunctionBuilder::new(
            "f",
            I64_TYPE,
            &[(I64_TYPE, Some("x"))],
        );

        let then_bb = b.new_block();
        let else_bb = b.new_block();
        let merge_bb = b.new_block();

        let cond = b.cmp(
            CmpOp::Gt,
            I64_TYPE,
            FunctionBuilder::copy(LocalId(1)),
            FunctionBuilder::const_i64(0),
        );
        b.branch(FunctionBuilder::copy(cond), then_bb, else_bb);

        b.switch_to(then_bb);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(LocalId(1)));
        b.jump(merge_bb);

        b.switch_to(else_bb);
        let neg = b.un_op(UnOp::Neg, I64_TYPE, FunctionBuilder::copy(LocalId(1)));
        b.assign(Place::local(LocalId(0)), FunctionBuilder::copy(neg));
        b.jump(merge_bb);

        b.switch_to(merge_bb);
        b.ret(FunctionBuilder::copy(LocalId(0)));

        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("bb0:"));
        assert!(c_code.contains("bb1:"));
        assert!(c_code.contains("bb2:"));
        assert!(c_code.contains("bb3:"));
        assert!(c_code.contains("goto bb"));
        assert!(c_code.contains("if ("));
    }

    #[test]
    fn emit_struct_typedef() {
        let mut module = Module::new();
        module.type_registry.add_type_def(TypeDef {
            name: "Point".into(),
            kind: TypeDefKind::Struct(StructDef {
                fields: vec![
                    StructField { name: "x".into(), type_id: F64_TYPE },
                    StructField { name: "y".into(), type_id: F64_TYPE },
                ],
            }),
            metadata: TypeMetadata::default(),
        });
        let point_id = module.type_registry.insert(GirType::Named("Point".into()));

        // Add a main function that uses the struct
        let mut b = FunctionBuilder::new("main", I32_TYPE, &[]);
        let _ = b.struct_init("Point", point_id, vec![
            FunctionBuilder::const_f64(1.0),
            FunctionBuilder::const_f64(2.0),
        ]);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::const_i32(0));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("typedef struct Point Point;"));
        assert!(c_code.contains("struct Point {"));
        assert!(c_code.contains("double x;"));
        assert!(c_code.contains("double y;"));
        assert!(c_code.contains("Point _1 = (Point){.x = 1.0, .y = 2.0}"));
    }

    #[test]
    fn emit_enum_typedef() {
        let mut module = Module::new();
        module.type_registry.add_type_def(TypeDef {
            name: "Shape".into(),
            kind: TypeDefKind::Enum(EnumDef {
                variants: vec![
                    EnumVariant {
                        name: "Circle".into(),
                        fields: vec![StructField { name: "_0".into(), type_id: F64_TYPE }],
                    },
                    EnumVariant {
                        name: "Rect".into(),
                        fields: vec![
                            StructField { name: "_0".into(), type_id: F64_TYPE },
                            StructField { name: "_1".into(), type_id: F64_TYPE },
                        ],
                    },
                    EnumVariant { name: "Empty".into(), fields: vec![] },
                ],
            }),
            metadata: TypeMetadata::default(),
        });

        // Need a function for valid module
        let mut b = FunctionBuilder::new("main", I32_TYPE, &[]);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::const_i32(0));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("typedef struct Shape Shape;"));
        assert!(c_code.contains("struct Shape {"));
        assert!(c_code.contains("int tag;"));
        assert!(c_code.contains("union {"));
        assert!(c_code.contains("} Circle;"));
        assert!(c_code.contains("} Rect;"));
    }

    #[test]
    fn emit_global_constant() {
        let mut module = Module::new();
        module.globals.push(Global {
            name: "my_vtable".into(),
            type_id: I64_TYPE,
            init: GlobalInit::Zeroed,
        });

        let mut b = FunctionBuilder::new("main", I32_TYPE, &[]);
        b.assign(Place::local(LocalId(0)), FunctionBuilder::const_i32(0));
        b.ret(FunctionBuilder::copy(LocalId(0)));
        module.functions.push(b.build());

        let c_code = generate_c(&module);
        assert!(c_code.contains("static int64_t my_vtable = {0};"));
    }
}
