// Generated by Gorget compiler v0.1.0
#define _POSIX_C_SOURCE 200809L
#ifdef __APPLE__
#define _DARWIN_C_SOURCE
#else
// glibc gates strptime() behind __USE_XOPEN (i.e. _XOPEN_SOURCE / _GNU_SOURCE),
// NOT __USE_MISC — so _DEFAULT_SOURCE alone leaves it implicitly declared, and an
// implicit decl is assumed to return `int`, truncating its 64-bit char* result to
// 32 bits (garbage `rest` in gorget_parse_time). macOS declares it unconditionally,
// which is why this only bites on Linux. _XOPEN_SOURCE 700 is the standards-based
// (non-_GNU_SOURCE) fix; kept alongside _DEFAULT_SOURCE so we get the union of both.
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 700
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif
#endif
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <string.h>
#include <inttypes.h>
#include <stdarg.h>
#include <setjmp.h>
#include <dirent.h>
#include <sys/stat.h>
#include <ctype.h>
#include <sys/wait.h>
#include <unistd.h>
#include <time.h>
#include <math.h>
#include <errno.h>
#include <sys/ioctl.h>
// Unconditional: the Task/async scheduler, spawn, and the sync runtime
// (Mutex/Channel/WaitGroup/etc.) all use pthreads, so every hosted binary
// links pthread regardless of whether the program spawns. `main` itself
// now runs the user body on thread 0 (a plain `int main`), not a secondary
// thread. The freestanding target never reaches this preamble
// (emit_types.rs early-returns onto lib/freestanding/runtime.c).
#include <pthread.h>
#include <signal.h>

// ── D11 trap codes (shared single-source) ───────────────────
// The `T_` code for the index/bounds trap class (out-of-bounds index on
// Vector / String / shared array / bytes buffer). Single-sourced here so a
// future `TrapKind::Bounds` rename can't PARTIALLY drift across the ~30
// span-less bounds sites in runtime_array.c / runtime_string.c /
// shared_runtime.c / bytes*_runtime.c. Mirrors `TrapKind::Bounds.code()`
// (src/trap.rs) / ggdef's `TrapKind::Bounds` — the `trap_bounds.gg`
// conformance fixture is the executable guard for the `gorget_array_get`
// path. The Layer-B `gorget_array_get_at` reroute threads the code as DATA
// from `TrapKind::Bounds.code()` at the emit boundary; this define is the
// span-less fallback used by the runtime-internal callers + the self-host.
#define GG_T_BOUNDS "T_Bounds"

// ── Allocator ───────────────────────────────────────────────
typedef struct GorgetAllocator {
    void* (*alloc)(void* ctx, size_t size);
    void* (*realloc)(void* ctx, void* ptr, size_t old_size, size_t new_size);
    void  (*dealloc)(void* ctx, void* ptr, size_t size);
    void* ctx;
} GorgetAllocator;

static _Atomic size_t __gorget_total_allocated = 0;
static _Atomic size_t __gorget_total_freed = 0;
static _Atomic size_t __gorget_alloc_count = 0;
static _Atomic size_t __gorget_free_count = 0;
static _Atomic size_t __gorget_size_buckets[16] = {0}; // [0]=1-15, [1]=16-31, ..., [14]=224-239, [15]=240+
static _Atomic size_t __gorget_array_new_count = 0;
static _Atomic size_t __gorget_array_free_count = 0;
static _Atomic size_t __gorget_array_clone_count = 0;
static _Atomic size_t __gorget_str_cat_count = 0;
static _Atomic size_t __gorget_string_free_count = 0;
static _Atomic size_t __gorget_string_new_count = 0;
// --clone-stats counters — always compiled in (counter is ~1 ns per call).
// Only the atexit report is gated, so zero-cost when --clone-stats isn't set.
static _Atomic size_t __gorget_map_clone_count = 0;
static _Atomic size_t __gorget_set_clone_count = 0;
static _Atomic size_t __gorget_string_cow_count = 0;
// Deep string clones via gorget_string_clone_to_owned — the compiler-emitted
// boundary-clone entry point. Also counts runtime-INTERNAL per-element clones
// (gorget_string_clone_inplace in the array/map element-clone paths route
// through clone_to_owned), so this legitimately EXCEEDS the per-site
// attributed hits from the [clone-site] report. gorget_string_clone (the
// un-attributed LIR-path entry point) is deliberately NOT counted here.
static _Atomic size_t __gorget_string_clone_count = 0;
static _Atomic size_t __gorget_box_alloc_count = 0;
static _Atomic size_t __gorget_closure_clone_count = 0;
// Forward declaration — definition is later in the file so that
// __gorget_write_mem_stats (which it calls) can be defined alongside
// the atexit handler.
static void __gorget_snapshot_mem_stats(void);

static void* __gorget_global_alloc_fn(void* ctx, size_t size) {
    (void)ctx;
    __gorget_total_allocated += size;
    size_t new_count = ++__gorget_alloc_count;
    size_t bucket = size / 16;
    if (bucket > 15) bucket = 15;
    __gorget_size_buckets[bucket]++;
    // Periodic snapshot so stats survive SIGKILL (OOM killer skips
    // atexit). Every 1,000,000 allocs — cheap enough to not skew
    // timings, frequent enough to catch the last megabyte before OOM.
    if ((new_count & ((1u << 20) - 1)) == 0) {
        __gorget_snapshot_mem_stats();
    }
    return malloc(size);
}
static void* __gorget_global_realloc_fn(void* ctx, void* ptr, size_t old_size, size_t new_size) {
    (void)ctx;
    __gorget_total_allocated += (new_size > old_size ? new_size - old_size : 0);
    if (old_size > new_size) __gorget_total_freed += (old_size - new_size);
    return realloc(ptr, new_size);
}
static void __gorget_global_dealloc_fn(void* ctx, void* ptr, size_t size) {
    (void)ctx;
    __gorget_total_freed += size;
    __gorget_free_count++;
    free(ptr);
}

static int64_t gorget_mem_allocated(void) {
    return (int64_t)__gorget_total_allocated;
}
static int64_t gorget_mem_freed(void) {
    return (int64_t)__gorget_total_freed;
}
static int64_t gorget_mem_live(void) {
    return (int64_t)(__gorget_total_allocated - __gorget_total_freed);
}
static int64_t gorget_mem_alloc_count(void) {
    return (int64_t)__gorget_alloc_count;
}

// Write allocator stats to a FILE* — used for both the atexit dump
// (stderr) and periodic snapshot to a file so the numbers survive
// SIGKILL from the OOM killer.
static void __gorget_write_mem_stats(FILE* out) {
    size_t alloc_bytes = __gorget_total_allocated;
    size_t freed_bytes = __gorget_total_freed;
    size_t live_bytes  = alloc_bytes - freed_bytes;
    size_t alloc_calls = __gorget_alloc_count;
    size_t free_calls  = __gorget_free_count;
    fprintf(out, "=== gorget memory stats ===\n");
    fprintf(out, "  total allocated: %12zu bytes (%zu MiB)\n",
            alloc_bytes, alloc_bytes / (1024 * 1024));
    fprintf(out, "  total freed:     %12zu bytes (%zu MiB)\n",
            freed_bytes, freed_bytes / (1024 * 1024));
    fprintf(out, "  live at exit:    %12zu bytes (%zu MiB)\n",
            live_bytes, live_bytes / (1024 * 1024));
    fprintf(out, "  alloc calls:     %12zu\n", alloc_calls);
    fprintf(out, "  free  calls:     %12zu\n", free_calls);
    fprintf(out, "  str_cat calls:   %12zu\n", (size_t)__gorget_str_cat_count);
    fprintf(out, "  string_new:      %12zu\n", (size_t)__gorget_string_new_count);
    fprintf(out, "  string_free:     %12zu\n", (size_t)__gorget_string_free_count);
    fprintf(out, "  array_new:       %12zu\n", (size_t)__gorget_array_new_count);
    fprintf(out, "  array_clone:     %12zu\n", (size_t)__gorget_array_clone_count);
    fprintf(out, "  array_free:      %12zu\n", (size_t)__gorget_array_free_count);
    fprintf(out, "  alloc size histogram (buckets of 16 bytes):\n");
    for (int b = 0; b < 16; b++) {
        size_t count = __gorget_size_buckets[b];
        if (count == 0) continue;
        if (b < 15) {
            fprintf(out, "    %4d - %4d : %12zu allocations\n",
                    b * 16, b * 16 + 15, count);
        } else {
            fprintf(out, "    %4d +      : %12zu allocations\n",
                    b * 16, count);
        }
    }
    fflush(out);
}

// atexit handler (stderr, gated by GG_MEM_STATS).
static void __gorget_dump_mem_stats(void) {
    const char* envv = getenv("GG_MEM_STATS");
    if (!envv || envv[0] != '1') return;
    fprintf(stderr, "\n");
    __gorget_write_mem_stats(stderr);
}

// Snapshot to a file path (GG_MEM_STATS_FILE), called periodically
// from the allocator hook. Rewrites the file each time so the final
// snapshot is always visible — needed because SIGKILL (OOM) skips
// atexit handlers.
static _Atomic size_t __gorget_snapshot_counter = 0;
static void __gorget_snapshot_mem_stats(void) {
    const char* path = getenv("GG_MEM_STATS_FILE");
    if (!path) return;
    FILE* f = fopen(path, "w");
    if (!f) return;
    __gorget_write_mem_stats(f);
    fclose(f);
}

// Register at first allocation so the handler is up before main exits
// without requiring explicit init.
static _Atomic int __gorget_stats_registered = 0;
static inline void __gorget_register_mem_stats(void) {
    int expected = 0;
    if (atomic_compare_exchange_strong(&__gorget_stats_registered,
                                       &expected, 1)) {
        atexit(__gorget_dump_mem_stats);
    }
}

static GorgetAllocator __gorget_global_alloc = {
    __gorget_global_alloc_fn,
    __gorget_global_realloc_fn,
    __gorget_global_dealloc_fn,
    NULL
};

static _Thread_local GorgetAllocator* __gorget_current_alloc = &__gorget_global_alloc;

#define GORGET_ALLOC(size) \
    __gorget_current_alloc->alloc(__gorget_current_alloc->ctx, (size))
#define GORGET_REALLOC(ptr, old_size, new_size) \
    __gorget_current_alloc->realloc(__gorget_current_alloc->ctx, (ptr), (old_size), (new_size))
#define GORGET_FREE(ptr, size) \
    __gorget_current_alloc->dealloc(__gorget_current_alloc->ctx, (ptr), (size))
#define GORGET_CALLOC(count, elem_size) \
    ({ void* __p = GORGET_ALLOC((count) * (elem_size)); memset(__p, 0, (count) * (elem_size)); __p; })

// ── Scoped allocator push/pop (stub for LIR backend) ──
// The old C backend manages scoped allocators inline. These stubs allow
// the LIR backend to emit push/pop calls without generating link errors.
#define GORGET_ALLOC_STACK_MAX 16
static _Thread_local GorgetAllocator* __gorget_alloc_stack[GORGET_ALLOC_STACK_MAX];
static _Thread_local int __gorget_alloc_stack_top = 0;

static inline void __gorget_push_allocator(void* alloc) {
    if (__gorget_alloc_stack_top < GORGET_ALLOC_STACK_MAX) {
        __gorget_alloc_stack[__gorget_alloc_stack_top++] = __gorget_current_alloc;
    }
    __gorget_current_alloc = (GorgetAllocator*)alloc;
}
static inline void __gorget_pop_allocator(void) {
    if (__gorget_alloc_stack_top > 0) {
        __gorget_current_alloc = __gorget_alloc_stack[--__gorget_alloc_stack_top];
    }
}

// ── Hash utilities (wyhash-final3, public-domain) ────────────
// Replaces the previous FNV-1a (one byte/multiply per input byte). wyhash mixes
// 8 bytes per round and avalanches better, cutting both hash cost and probe
// clustering for short keys (the Dict/Set common case).
//
// MEMORY SAFETY: the block readers read EXACTLY the bytes covered by `len` and
// never past `data+len`. `__gorget_wyr8` is only called on full 8-byte spans;
// the tail (1..7 bytes) is read via `__gorget_wyr3`, which reads byte 0, byte
// len>>1, and byte len-1 — all strictly inside [data, data+len). The 8-byte
// int-key path reads exactly its 8 bytes. (ASan-clean: no over-read.)
#define __GORGET_WY0 0xa0761d6478bd642fULL
#define __GORGET_WY1 0xe7037ed1a0b428dbULL
#define __GORGET_WY2 0x8ebc6af09c88c6e3ULL
static inline uint64_t __gorget_wyr8(const uint8_t* p) {
    uint64_t v; memcpy(&v, p, 8); return v;
}
static inline uint64_t __gorget_wyr4(const uint8_t* p) {
    uint32_t v; memcpy(&v, p, 4); return (uint64_t)v;
}
// Reads exactly `k` bytes (1..3) from p without over-reading: bytes 0, k>>1, k-1.
static inline uint64_t __gorget_wyr3(const uint8_t* p, size_t k) {
    return ((uint64_t)p[0] << 16) | ((uint64_t)p[k >> 1] << 8) | (uint64_t)p[k - 1];
}
static inline uint64_t __gorget_wymix(uint64_t a, uint64_t b) {
    __uint128_t r = (__uint128_t)(a ^ __GORGET_WY0) * (uint64_t)(b ^ __GORGET_WY1);
    return (uint64_t)r ^ (uint64_t)(r >> 64);
}
static inline uint64_t __gorget_wyhash(const void* data, size_t len) {
    const uint8_t* p = (const uint8_t*)data;
    uint64_t seed = __GORGET_WY0 ^ __gorget_wymix(len, __GORGET_WY1);
    uint64_t a, b;
    if (len <= 16) {
        if (len >= 4) {
            // 4..16 bytes: read first 4 and last 4 (overlapping is fine).
            a = (__gorget_wyr4(p) << 32) | __gorget_wyr4(p + ((len >> 3) << 2));
            b = (__gorget_wyr4(p + len - 4) << 32) | __gorget_wyr4(p + len - 4 - ((len >> 3) << 2));
        } else if (len > 0) {
            a = __gorget_wyr3(p, len);  // 1..3 bytes, no over-read
            b = 0;
        } else {
            a = 0; b = 0;
        }
    } else {
        size_t i = len;
        const uint8_t* q = p;
        uint64_t see1 = seed;
        // 48-byte unrolled body for long keys.
        while (i > 48) {
            seed = __gorget_wymix(__gorget_wyr8(q)      ^ __GORGET_WY1, __gorget_wyr8(q + 8)  ^ seed);
            see1 = __gorget_wymix(__gorget_wyr8(q + 16) ^ __GORGET_WY2, __gorget_wyr8(q + 24) ^ see1);
            seed = __gorget_wymix(__gorget_wyr8(q + 32) ^ __GORGET_WY1, __gorget_wyr8(q + 40) ^ seed);
            q += 48; i -= 48;
        }
        seed ^= see1;
        while (i > 16) {
            seed = __gorget_wymix(__gorget_wyr8(q) ^ __GORGET_WY1, __gorget_wyr8(q + 8) ^ seed);
            q += 16; i -= 16;
        }
        // Final 16 bytes (overlap with what we consumed is fine).
        a = __gorget_wyr8(q + i - 16);
        b = __gorget_wyr8(q + i - 8);
    }
    return __gorget_wymix(__GORGET_WY1 ^ len, __gorget_wymix(a ^ __GORGET_WY1, b ^ seed));
}
// splitmix64 finalizer — 2 multiplies + 2 xorshifts, excellent avalanche on a
// single 64-bit word. Far cheaper than the general wyhash for the dominant
// 8-byte integer-key case (wyhash spends 3 128-bit multiplies even on 8 bytes).
static inline uint64_t __gorget_splitmix64(uint64_t x) {
    x ^= x >> 30; x *= 0xbf58476d1ce4e5b9ULL;
    x ^= x >> 27; x *= 0x94d049bb133111ebULL;
    x ^= x >> 31;
    return x;
}
// Generic-key entry point (default int/byte path; signature unchanged so the
// __GORGET_MAP_HASH fallback call site is untouched). The dominant case is an
// 8-byte integer key — fast-pathed through splitmix64; other widths fall back
// to wyhash. Reads exactly `len` bytes (no over-read).
static inline uint64_t __gorget_fnv1a(const void* data, size_t len) {
    if (len == 8) {
        uint64_t k; memcpy(&k, data, 8);
        return __gorget_splitmix64(k);
    }
    if (len == 4) {
        uint32_t k; memcpy(&k, data, 4);
        return __gorget_splitmix64((uint64_t)k);
    }
    return __gorget_wyhash(data, len);
}
static inline uint64_t __gorget_hash_str(const char* s) {
    return __gorget_wyhash(s, strlen(s));
}
// String-key path: reads EXACTLY `len` bytes (byte-exact contract preserved).
static inline uint64_t __gorget_hash_str_len(const char* s, size_t len) {
    return __gorget_wyhash(s, len);
}

// ── Collection struct typedefs (always available for field references) ──
typedef void (*__gorget_drop_fn)(void*);
typedef struct {
    void* data;
    size_t cap;              // offset +8: generic view discriminator (0 = view)
    size_t len;
    size_t elem_size;
    GorgetAllocator* alloc;
    __gorget_drop_fn elem_drop;  // drop function for resource-type elements (NULL if trivial)
    __gorget_drop_fn elem_clone; // clone function for resource-type elements (NULL if trivial)
    __gorget_drop_fn elem_materialize; // CoW materialize: view→owned only (NULL if not needed)
} GorgetArray;

typedef uint64_t (*__gorget_hash_fn)(const void*);
typedef bool (*__gorget_eq_fn)(const void*, const void*);
typedef struct {
    void* keys;
    size_t cap;              // offset +8: generic view discriminator (0 = view)
    void* values;
    uint8_t* states;
    size_t count;
    size_t key_size;
    size_t val_size;
    GorgetAllocator* alloc;
    size_t* order;
    size_t order_len;
    size_t tombstones;
    __gorget_hash_fn hash_fn;
    __gorget_eq_fn eq_fn;
    __gorget_drop_fn val_drop;
    __gorget_drop_fn val_clone;         // Full clone (always-clone). Used by dict.clone() and gorget_map_put_cloned() for intentional aliasing.
    __gorget_drop_fn key_drop;
    __gorget_drop_fn key_clone;         // Full clone (always-clone). Same as val_clone but for keys.
    __gorget_drop_fn val_materialize;   // CoW materialize on insert (cap==0-only for strings). NULL = no-op.
    __gorget_drop_fn key_materialize;   // CoW materialize on insert. Symmetric with gorget_array's elem_materialize.
} GorgetMap;

typedef GorgetMap GorgetSet;

typedef struct {
    void* fn_ptr;
    void* env;
} GorgetClosure;

// ── CLI init (always needed — main() calls gorget_init_args) ──
static int gorget_argc = 0;
static char** gorget_argv = NULL;

static inline void gorget_init_args(int argc, char** argv) {
    gorget_argc = argc;
    gorget_argv = argv;
    __gorget_register_mem_stats();
}

// ── Print capture layer ──
// Always available; capture state is toggled by the test runner.
static int    __gorget_capturing = 0;
static char  *__gorget_capture_buf = NULL;
static size_t __gorget_capture_len = 0;
static size_t __gorget_capture_cap = 0;

static void __gorget_capture_ensure(size_t extra) {
    size_t needed = __gorget_capture_len + extra + 1;
    if (needed > __gorget_capture_cap) {
        __gorget_capture_cap = needed * 2;
        __gorget_capture_buf = (char *)realloc(__gorget_capture_buf, __gorget_capture_cap);
    }
}

__attribute__((format(printf, 1, 2)))
static int __gorget_printf(const char *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int ret;
    if (__gorget_capturing) {
        va_list args_copy;
        va_copy(args_copy, args);
        int needed = vsnprintf(NULL, 0, fmt, args_copy);
        va_end(args_copy);
        if (needed > 0) {
            __gorget_capture_ensure((size_t)needed);
            vsnprintf(__gorget_capture_buf + __gorget_capture_len,
                      (size_t)needed + 1, fmt, args);
            __gorget_capture_len += (size_t)needed;
        }
        ret = needed;
    } else {
        ret = vprintf(fmt, args);
    }
    va_end(args);
    return ret;
}

