// Generated by Gorget compiler v0.1.0
#define _POSIX_C_SOURCE 200809L
#ifdef __APPLE__
#define _DARWIN_C_SOURCE
#else
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif
#endif
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include <stdarg.h>
#include <setjmp.h>
#include <dirent.h>
#include <sys/stat.h>
#include <ctype.h>
#include <sys/wait.h>
#include <unistd.h>
#include <time.h>
#include <math.h>
#include <errno.h>
#include <sys/ioctl.h>

// ── Allocator ───────────────────────────────────────────────
typedef struct GorgetAllocator {
    void* (*alloc)(void* ctx, size_t size);
    void* (*realloc)(void* ctx, void* ptr, size_t old_size, size_t new_size);
    void  (*dealloc)(void* ctx, void* ptr, size_t size);
    void* ctx;
} GorgetAllocator;

static _Atomic size_t __gorget_total_allocated = 0;
static _Atomic size_t __gorget_total_freed = 0;
static _Atomic size_t __gorget_alloc_count = 0;
static _Atomic size_t __gorget_free_count = 0;
static _Atomic size_t __gorget_size_buckets[16] = {0}; // [0]=1-15, [1]=16-31, ..., [14]=224-239, [15]=240+
static _Atomic size_t __gorget_array_new_count = 0;
static _Atomic size_t __gorget_array_free_count = 0;
static _Atomic size_t __gorget_array_clone_count = 0;
static _Atomic size_t __gorget_str_cat_count = 0;
static _Atomic size_t __gorget_string_free_count = 0;
static _Atomic size_t __gorget_string_new_count = 0;
static void* __gorget_global_alloc_fn(void* ctx, size_t size) {
    (void)ctx;
    __gorget_total_allocated += size;
    __gorget_alloc_count++;
    size_t bucket = size / 16;
    if (bucket > 15) bucket = 15;
    __gorget_size_buckets[bucket]++;
    return malloc(size);
}
static void* __gorget_global_realloc_fn(void* ctx, void* ptr, size_t old_size, size_t new_size) {
    (void)ctx;
    __gorget_total_allocated += (new_size > old_size ? new_size - old_size : 0);
    if (old_size > new_size) __gorget_total_freed += (old_size - new_size);
    return realloc(ptr, new_size);
}
static void __gorget_global_dealloc_fn(void* ctx, void* ptr, size_t size) {
    (void)ctx;
    __gorget_total_freed += size;
    __gorget_free_count++;
    free(ptr);
}

static int64_t gorget_mem_allocated(void) {
    return (int64_t)__gorget_total_allocated;
}
static int64_t gorget_mem_freed(void) {
    return (int64_t)__gorget_total_freed;
}
static int64_t gorget_mem_live(void) {
    return (int64_t)(__gorget_total_allocated - __gorget_total_freed);
}
static int64_t gorget_mem_alloc_count(void) {
    return (int64_t)__gorget_alloc_count;
}

static GorgetAllocator __gorget_global_alloc = {
    __gorget_global_alloc_fn,
    __gorget_global_realloc_fn,
    __gorget_global_dealloc_fn,
    NULL
};

static _Thread_local GorgetAllocator* __gorget_current_alloc = &__gorget_global_alloc;

#define GORGET_ALLOC(size) \
    __gorget_current_alloc->alloc(__gorget_current_alloc->ctx, (size))
#define GORGET_REALLOC(ptr, old_size, new_size) \
    __gorget_current_alloc->realloc(__gorget_current_alloc->ctx, (ptr), (old_size), (new_size))
#define GORGET_FREE(ptr, size) \
    __gorget_current_alloc->dealloc(__gorget_current_alloc->ctx, (ptr), (size))
#define GORGET_CALLOC(count, elem_size) \
    ({ void* __p = GORGET_ALLOC((count) * (elem_size)); memset(__p, 0, (count) * (elem_size)); __p; })

// ── Scoped allocator push/pop (stub for LIR backend) ──
// The old C backend manages scoped allocators inline. These stubs allow
// the LIR backend to emit push/pop calls without generating link errors.
#define GORGET_ALLOC_STACK_MAX 16
static _Thread_local GorgetAllocator* __gorget_alloc_stack[GORGET_ALLOC_STACK_MAX];
static _Thread_local int __gorget_alloc_stack_top = 0;

static inline void __gorget_push_allocator(void* alloc) {
    if (__gorget_alloc_stack_top < GORGET_ALLOC_STACK_MAX) {
        __gorget_alloc_stack[__gorget_alloc_stack_top++] = __gorget_current_alloc;
    }
    __gorget_current_alloc = (GorgetAllocator*)alloc;
}
static inline void __gorget_pop_allocator(void) {
    if (__gorget_alloc_stack_top > 0) {
        __gorget_current_alloc = __gorget_alloc_stack[--__gorget_alloc_stack_top];
    }
}

// ── Hash utilities (FNV-1a) ─────────────────────────────────
static inline uint64_t __gorget_fnv1a(const void* data, size_t len) {
    uint64_t hash = 14695981039346656037ULL;
    const uint8_t* p = (const uint8_t*)data;
    for (size_t i = 0; i < len; i++) {
        hash ^= p[i];
        hash *= 1099511628211ULL;
    }
    return hash;
}
static inline uint64_t __gorget_hash_str(const char* s) {
    uint64_t hash = 14695981039346656037ULL;
    while (*s) { hash ^= (uint8_t)*s++; hash *= 1099511628211ULL; }
    return hash;
}
static inline uint64_t __gorget_hash_str_len(const char* s, size_t len) {
    uint64_t hash = 14695981039346656037ULL;
    for (size_t i = 0; i < len; i++) { hash ^= (uint8_t)s[i]; hash *= 1099511628211ULL; }
    return hash;
}

// ── Collection struct typedefs (always available for field references) ──
typedef void (*__gorget_drop_fn)(void*);
typedef struct {
    void* data;
    size_t len;
    size_t cap;
    size_t elem_size;
    GorgetAllocator* alloc;
    __gorget_drop_fn elem_drop;  // drop function for resource-type elements (NULL if trivial)
    __gorget_drop_fn elem_clone; // clone function for resource-type elements (NULL if trivial)
    __gorget_drop_fn elem_materialize; // CoW materialize: view→owned only (NULL if not needed)
} GorgetArray;

typedef uint64_t (*__gorget_hash_fn)(const void*);
typedef bool (*__gorget_eq_fn)(const void*, const void*);
typedef struct {
    void* keys;
    void* values;
    uint8_t* states;
    size_t count;
    size_t cap;
    size_t key_size;
    size_t val_size;
    GorgetAllocator* alloc;
    size_t* order;
    size_t order_len;
    size_t tombstones;
    __gorget_hash_fn hash_fn;
    __gorget_eq_fn eq_fn;
    __gorget_drop_fn val_drop;
    __gorget_drop_fn val_clone;         // Full clone (always-clone). Used by dict.clone() and gorget_map_put_cloned() for intentional aliasing.
    __gorget_drop_fn key_drop;
    __gorget_drop_fn key_clone;         // Full clone (always-clone). Same as val_clone but for keys.
    __gorget_drop_fn val_materialize;   // CoW materialize on insert (cap==0-only for strings). NULL = no-op.
    __gorget_drop_fn key_materialize;   // CoW materialize on insert. Symmetric with gorget_array's elem_materialize.
} GorgetMap;

typedef GorgetMap GorgetSet;

typedef struct {
    void* fn_ptr;
    void* env;
} GorgetClosure;

// ── CLI init (always needed — main() calls gorget_init_args) ──
static int gorget_argc = 0;
static char** gorget_argv = NULL;

static inline void gorget_init_args(int argc, char** argv) {
    gorget_argc = argc;
    gorget_argv = argv;
}

// ── Print capture layer ──
// Always available; capture state is toggled by the test runner.
static int    __gorget_capturing = 0;
static char  *__gorget_capture_buf = NULL;
static size_t __gorget_capture_len = 0;
static size_t __gorget_capture_cap = 0;

static void __gorget_capture_ensure(size_t extra) {
    size_t needed = __gorget_capture_len + extra + 1;
    if (needed > __gorget_capture_cap) {
        __gorget_capture_cap = needed * 2;
        __gorget_capture_buf = (char *)realloc(__gorget_capture_buf, __gorget_capture_cap);
    }
}

__attribute__((format(printf, 1, 2)))
static int __gorget_printf(const char *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int ret;
    if (__gorget_capturing) {
        va_list args_copy;
        va_copy(args_copy, args);
        int needed = vsnprintf(NULL, 0, fmt, args_copy);
        va_end(args_copy);
        if (needed > 0) {
            __gorget_capture_ensure((size_t)needed);
            vsnprintf(__gorget_capture_buf + __gorget_capture_len,
                      (size_t)needed + 1, fmt, args);
            __gorget_capture_len += (size_t)needed;
        }
        ret = needed;
    } else {
        ret = vprintf(fmt, args);
    }
    va_end(args);
    return ret;
}


// ── String (32-byte fat struct with generic view sentinel) ────
// Str is a 4-field struct, 32 bytes total:
//
//     struct Str {
//         void*            data;   // offset 0  — UTF-8 bytes (not NUL-terminated by contract)
//         size_t           cap;    // offset 8  — allocated bytes for data buffer (0 = VIEW)
//         size_t           len;    // offset 16 — byte length (authoritative)
//         GorgetAllocator* alloc;  // offset 24 — allocator for owned buffer (NULL for views)
//     };
//
// Invariants:
//   * cap == 0 ⟺ view  (borrowed buffer — may point into .rodata or another Str)
//   * cap >  0 ⟺ owned (we free `data` via `alloc->dealloc(data, cap)` at drop time)
//   * len is authoritative regardless of owned/view
//
// String literals are views into .rodata:
//   static const Str __slit_N = { .data = "hello", .cap = 0, .len = 5, .alloc = NULL };
//
// Field order `{data, cap, len, alloc}` puts `cap` at offset +8, matching the
// generic view-discriminator prefix shared with GorgetArray / GorgetMap / GorgetSet.

typedef struct {
    void*            data;
    size_t           cap;
    size_t           len;
    GorgetAllocator* alloc;
} Str;

typedef Str GorgetString;
typedef Str StringHeader;  // legacy alias: StringHeader* now means Str*

// Accessor macros — `s` is a Str value.
//   STR_LEN(s)  — rvalue byte length
//   STR_CAP(s)  — rvalue capacity (0 = view)
//   STR_HDR(s)  — pointer to the header (which IS the Str itself); used by
//                 legacy code written in the thin-pointer era
#define STR_LEN(s)  ((s).len)
#define STR_CAP(s)  ((s).cap)
#define STR_HDR(s)  (&(s))

// Generic view discriminator shared across resource types: the field at
// offset +8 is "cap"; 0 means the resource is a view, nonzero means owned.
static inline bool gorget_is_view(const void* resource) {
    return ((const size_t*)resource)[1] == 0;
}

// Internal view type — for temporary read-only access, never stored in Gorget types.
typedef struct { const char* data; size_t len; } StrView;
static inline StrView str_view(Str s) {
    return (StrView){ (const char*)s.data, s.len };
}
static inline StrView str_view_raw(const char* data, size_t len) {
    return (StrView){ data, len };
}

// Global empty string — static view into an empty rodata literal.
// Drop is a no-op because cap == 0.
static const Str GORGET_EMPTY_STR = { .data = (void*)"", .cap = 0, .len = 0, .alloc = NULL };

// Stack-allocated string literal — compound literal yielding a Str struct (C99).
// Zero allocation; data points at the C string literal in .rodata. cap = 0 = view.
#define GORGET_SLIT(lit) \
    ((Str){ .data = (void*)(lit), .cap = 0, .len = sizeof(lit) - 1, .alloc = NULL })

// ── Allocation helpers ─────────────────────────────────────────
// Under 32-byte layout we allocate just the data bytes. The Str struct lives
// on the caller's stack (passed by value). Compared to the thin-pointer design
// this saves a 24-byte StringHeader allocation per owned string.

static inline Str str_alloc_with(size_t cap, GorgetAllocator* a) {
    char* data = (char*)a->alloc(a->ctx, cap);
    if (cap > 0) data[0] = '\0';
    return (Str){ .data = data, .cap = cap, .len = 0, .alloc = a };
}

static inline Str str_alloc_copy(const char* src, size_t len, GorgetAllocator* a) {
    size_t cap = len + 1;
    char* data = (char*)a->alloc(a->ctx, cap);
    if (len > 0 && src) memcpy(data, src, len);
    data[len] = '\0';
    return (Str){ .data = data, .cap = cap, .len = len, .alloc = a };
}

// Adopt a raw char* buffer into a proper Str. Frees the raw buffer.
static inline Str str_adopt_buf(char* buf, size_t len, size_t buf_cap, GorgetAllocator* a) {
    if (len == 0) {
        if (buf) a->dealloc(a->ctx, buf, buf_cap);
        return GORGET_EMPTY_STR;
    }
    Str result = str_alloc_copy(buf, len, a);
    a->dealloc(a->ctx, buf, buf_cap);
    return result;
}

// ── Core string operations ─────────────────────────────────────

static inline GorgetString gorget_string_new(const char* s) {
    __gorget_string_new_count++;
    if (s == NULL || s[0] == '\0') return GORGET_EMPTY_STR;
    return str_alloc_copy(s, strlen(s), __gorget_current_alloc);
}

// Adopt a freshly-allocated char* into a String. Copies into header+data layout,
// frees original. Caller must have allocated with GORGET_ALLOC or similar.
static inline GorgetString gorget_string_adopt(char* s) {
    if (s == NULL) return GORGET_EMPTY_STR;
    size_t len = strlen(s);
    if (len == 0) { GORGET_FREE(s, 1); return GORGET_EMPTY_STR; }
    Str result = str_alloc_copy(s, len, __gorget_current_alloc);
    GORGET_FREE(s, len + 1);
    return result;
}

// Drop an owned string. Views (cap == 0) are no-ops — they borrow their buffer
// from .rodata, another Str, or an external source. Owned strings free `data`
// via the allocator that created them, then zero the struct so double-free is safe.
static inline void gorget_string_free(GorgetString* s) {
    if (s->cap == 0) { *s = (Str){0}; return; }  // view — nothing to free
    __gorget_string_free_count++;
    s->alloc->dealloc(s->alloc->ctx, s->data, s->cap);
    *s = (Str){0};
}

// Clone: produces an independently-owned copy. Under 32-byte this is
// view-aware — if src is already a view, we allocate a fresh owned buffer
// with the same contents. If src is owned, same thing (fresh buffer).
// Either way the result is cap > 0.
static inline GorgetString gorget_string_clone(const GorgetString* src) {
    if (src->len == 0) return GORGET_EMPTY_STR;
    return str_alloc_copy((const char*)src->data, src->len, __gorget_current_alloc);
}

// Same semantic as gorget_string_clone under 32-byte — kept as a distinct
// entry point because the GIR lowering emits this name for explicit .clone()
// calls and boundary materialization.
static inline GorgetString gorget_string_clone_to_owned(const GorgetString* src) {
    if (src->len == 0) return GORGET_EMPTY_STR;
    return str_alloc_copy((const char*)src->data, src->len, __gorget_current_alloc);
}

// Borrow: shallow struct copy. The caller promises not to drop the borrow;
// the compiler emits no free for Ref locals. If a borrow escapes to storage
// the compiler materializes (clones) it at the ownership boundary.
static inline GorgetString gorget_string_borrow(const GorgetString* src) {
    return *src;
}

// Materialize an in-slot Str value. If it's a view (cap == 0), clone it into
// an owned buffer so the enclosing container can safely outlive the original
// source. If already owned, no-op.
//
// Called by the elem_materialize / val_materialize / key_materialize hooks
// inside gorget_array_push / gorget_map_put after the caller memcpys the
// value into the slot. This is the runtime side of lazy CoW: views crossing
// into owning storage get upgraded on-the-fly.
static inline void gorget_string_materialize_inplace(void* p) {
    Str* s = (Str*)p;
    if (s->cap == 0 && s->len > 0) {
        *s = str_alloc_copy((const char*)s->data, s->len, __gorget_current_alloc);
    }
}

static inline GorgetString gorget_string_concat(const GorgetString* a, const GorgetString* b) {
    size_t la = a->len;
    size_t lb = b->len;
    if (la == 0 && lb == 0) return GORGET_EMPTY_STR;
    if (la == 0) return gorget_string_clone(b);
    if (lb == 0) return gorget_string_clone(a);
    GorgetAllocator* al = __gorget_current_alloc;
    size_t total = la + lb;
    size_t cap = total + 1;
    char* data = (char*)al->alloc(al->ctx, cap);
    memcpy(data, a->data, la);
    memcpy((char*)data + la, b->data, lb);
    data[total] = '\0';
    return (Str){ .data = data, .cap = cap, .len = total, .alloc = al };
}

static inline bool gorget_string_eq(const GorgetString* a, const GorgetString* b) {
    if (a->len != b->len) return false;
    if (a->len == 0) return true;
    if (a->data == b->data) return true;  // same buffer (aliased views)
    return memcmp(a->data, b->data, a->len) == 0;
}

// Return a NUL-terminated C string for FFI. Owned Strs have a '\0' byte at
// data[len] thanks to the +1 in cap (str_alloc_copy / str_alloc_with).
// Views into C string literals are naturally NUL-terminated too. Views into
// the middle of another buffer (from slice/char_at/...) are NOT NUL-terminated
// at len — but this plan keeps those functions allocating, so gorget_string_cstr
// only sees allocation-backed strings in practice.
static inline const char* gorget_string_cstr(const GorgetString* s) {
    return s->data ? (const char*)s->data : "";
}

static inline GorgetString gorget_string_format(const char* fmt, ...) {
    GorgetAllocator* a = __gorget_current_alloc;
    va_list args1, args2;
    va_start(args1, fmt);
    va_copy(args2, args1);
    int len = vsnprintf(NULL, 0, fmt, args1);
    va_end(args1);
    if (len < 0) { fprintf(stderr, "gorget: panic: format error\n"); exit(1); }
    size_t cap = (size_t)len + 1;
    char* data = (char*)a->alloc(a->ctx, cap);
    vsnprintf(data, cap, fmt, args2);
    va_end(args2);
    return (Str){ .data = data, .cap = cap, .len = (size_t)len, .alloc = a };
}

static inline const char* gorget_format(const char* fmt, ...) {
    va_list args1, args2;
    va_start(args1, fmt);
    va_copy(args2, args1);
    int len = vsnprintf(NULL, 0, fmt, args1);
    va_end(args1);
    if (len < 0) { fprintf(stderr, "gorget: panic: format error\n"); exit(1); }
    char* data = (char*)GORGET_ALLOC((size_t)len + 1);
    vsnprintf(data, (size_t)len + 1, fmt, args2);
    va_end(args2);
    return data;
}

static inline GorgetString gorget_string_from_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    if (la + lb == 0) return GORGET_EMPTY_STR;
    GorgetAllocator* al = __gorget_current_alloc;
    size_t cap = la + lb + 1;
    char* data = (char*)al->alloc(al->ctx, cap);
    memcpy(data, a, la);
    memcpy(data + la, b, lb + 1);  // includes trailing '\0'
    return (Str){ .data = data, .cap = cap, .len = la + lb, .alloc = al };
}

// Append the NUL-terminated C string `rhs` to `*s` in place.
// If `*s` is a view or uninitialized, allocates a fresh owned buffer first
// (CoW-on-mutation semantics for string builders).
static inline void gorget_string_append(GorgetString* s, const char* rhs) {
    size_t rlen = strlen(rhs);
    if (rlen == 0) return;
    if (s->cap == 0) {
        // View or empty — materialize into a freshly-owned buffer.
        GorgetAllocator* a = __gorget_current_alloc;
        size_t new_len = s->len + rlen;
        size_t new_cap = (new_len + 1) * 2;
        char* data = (char*)a->alloc(a->ctx, new_cap);
        if (s->len > 0 && s->data) memcpy(data, s->data, s->len);
        memcpy(data + s->len, rhs, rlen + 1);  // includes trailing '\0'
        *s = (Str){ .data = data, .cap = new_cap, .len = new_len, .alloc = a };
        return;
    }
    size_t new_len = s->len + rlen;
    if (new_len + 1 > s->cap) {
        size_t new_cap = (new_len + 1) * 2;
        s->data = s->alloc->realloc(s->alloc->ctx, s->data, s->cap, new_cap);
        s->cap = new_cap;
    }
    memcpy((char*)s->data + s->len, rhs, rlen + 1);  // includes trailing '\0'
    s->len = new_len;
}

static inline void gorget_string_push_byte(GorgetString* s, char c) {
    if (s->cap == 0) {
        // View or empty — materialize into a fresh owned buffer with room to grow.
        GorgetAllocator* a = __gorget_current_alloc;
        size_t new_cap = (s->len + 2) * 2;
        if (new_cap < 16) new_cap = 16;
        char* data = (char*)a->alloc(a->ctx, new_cap);
        if (s->len > 0 && s->data) memcpy(data, s->data, s->len);
        data[s->len] = c;
        data[s->len + 1] = '\0';
        *s = (Str){ .data = data, .cap = new_cap, .len = s->len + 1, .alloc = a };
        return;
    }
    if (s->len + 2 > s->cap) {
        size_t new_cap = (s->len + 2) * 2;
        s->data = s->alloc->realloc(s->alloc->ctx, s->data, s->cap, new_cap);
        s->cap = new_cap;
    }
    ((char*)s->data)[s->len] = c;
    s->len++;
    ((char*)s->data)[s->len] = '\0';
}

static inline GorgetString gorget_string_with_capacity(int64_t cap) {
    size_t c = (size_t)(cap > 0 ? cap : 16);
    return str_alloc_with(c, __gorget_current_alloc);
}

static inline void gorget_string_push_int(GorgetString* s, int64_t n) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%" PRId64, n);
    gorget_string_append(s, buf);
}

static inline void gorget_string_push_float(GorgetString* s, double d) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%g", d);
    gorget_string_append(s, buf);
}

static inline void gorget_string_push_bool(GorgetString* s, bool b) {
    gorget_string_append(s, b ? "true" : "false");
}

static inline void gorget_string_push_line(GorgetString* s, const char* rhs) {
    gorget_string_append(s, rhs);
    gorget_string_push_byte(s, '\n');
}

static inline void gorget_string_push_line_int(GorgetString* s, int64_t n) {
    gorget_string_push_int(s, n);
    gorget_string_push_byte(s, '\n');
}

static inline void gorget_string_push_line_float(GorgetString* s, double d) {
    gorget_string_push_float(s, d);
    gorget_string_push_byte(s, '\n');
}

static inline void gorget_string_push_line_bool(GorgetString* s, bool b) {
    gorget_string_push_bool(s, b);
    gorget_string_push_byte(s, '\n');
}

static inline void gorget_string_push_line_char(GorgetString* s, char c) {
    gorget_string_push_byte(s, c);
    gorget_string_push_byte(s, '\n');
}

// ── String concatenation ────────────────────────────────────
static inline const char* gorget_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)GORGET_ALLOC(la + lb + 1);
    memcpy(out, a, la);
    memcpy(out + la, b, lb + 1);
    return out;
}

// ── Str view functions ──────────────────────────────────────
// Forward declaration — defined in the panic handler section.
static void gorget_panic(const char* msg);

// Build a Str from a literal C string. Allocation helper used by the C
// backend when a string value must be materialized at runtime from a raw
// const char* (e.g., gorget_string_adopt fallbacks). String literals that
// the LIR StrLit path emits go through static `__slit_N` structs instead,
// which is free (no allocation, view into .rodata).
static inline Str gorget_str_from_literal(const char* data, size_t len) {
    if (len == 0) return GORGET_EMPTY_STR;
    return str_alloc_copy(data, len, __gorget_current_alloc);
}

// Push a Str (1+ bytes) onto a String builder — user-facing push_char.
// `c` is passed by value (32-byte struct copy).
static inline void gorget_string_push_char(GorgetString* s, Str c) {
    size_t clen = c.len;
    if (clen == 0) return;
    if (s->cap == 0) {
        GorgetAllocator* a = __gorget_current_alloc;
        size_t new_len = s->len + clen;
        size_t new_cap = (new_len + 1) * 2;
        if (new_cap < 16) new_cap = 16;
        char* data = (char*)a->alloc(a->ctx, new_cap);
        if (s->len > 0 && s->data) memcpy(data, s->data, s->len);
        memcpy(data + s->len, c.data, clen);
        data[new_len] = '\0';
        *s = (Str){ .data = data, .cap = new_cap, .len = new_len, .alloc = a };
        return;
    }
    if (s->len + clen + 1 > s->cap) {
        size_t new_cap = (s->len + clen + 1) * 2;
        s->data = s->alloc->realloc(s->alloc->ctx, s->data, s->cap, new_cap);
        s->cap = new_cap;
    }
    memcpy((char*)s->data + s->len, c.data, clen);
    s->len += clen;
    ((char*)s->data)[s->len] = '\0';
}

static inline Str gorget_str_from_cstr(const char* s) {
    if (s == NULL || s[0] == '\0') return GORGET_EMPTY_STR;
    return str_alloc_copy(s, strlen(s), __gorget_current_alloc);
}

static inline Str gorget_str_empty(void) {
    return GORGET_EMPTY_STR;
}

static inline Str gorget_int_to_binary(long long val, long long alt) {
    // Max 64 bits + "0b" prefix + null
    char buf[67];
    int pos = 66;
    buf[pos] = '\0';
    unsigned long long uval = (unsigned long long)val;
    if (uval == 0) {
        buf[--pos] = '0';
    } else {
        while (uval > 0) {
            buf[--pos] = '0' + (char)(uval & 1);
            uval >>= 1;
        }
    }
    if (alt) {
        buf[--pos] = 'b';
        buf[--pos] = '0';
    }
    size_t len = 66 - (size_t)pos;
    return str_alloc_copy(buf + pos, len, __gorget_current_alloc);
}

// ── Str field access + comparison ───────────────────────────
static inline size_t gorget_str_byte_len(Str s) {
    return s.len;
}
static inline bool gorget_str_is_empty(Str s) {
    return s.len == 0;
}

static inline bool gorget_str_eq(Str a, Str b) {
    if (a.len != b.len) return false;
    if (a.len == 0) return true;
    if (a.data == b.data) return true;
    return memcmp(a.data, b.data, a.len) == 0;
}

static inline int gorget_str_cmp(Str a, Str b) {
    size_t la = a.len;
    size_t lb = b.len;
    size_t min_len = la < lb ? la : lb;
    int r = min_len > 0 ? memcmp(a.data, b.data, min_len) : 0;
    if (r != 0) return r;
    if (la < lb) return -1;
    if (la > lb) return 1;
    return 0;
}

// ── UTF-8 utilities ─────────────────────────────────────────
// Byte count for a UTF-8 codepoint from its first byte (1-4, or 1 for invalid)
static inline int gorget_utf8_codepoint_len(unsigned char b) {
    if (b < 0x80) return 1;
    if ((b & 0xE0) == 0xC0) return 2;
    if ((b & 0xF0) == 0xE0) return 3;
    if ((b & 0xF8) == 0xF0) return 4;
    return 1;  // invalid lead byte — treat as single byte to advance
}

// Decode one codepoint starting at data[*pos]. Advances *pos past it.
// Returns the Unicode codepoint value, or 0xFFFD (replacement char) on error.
static inline int64_t gorget_utf8_decode(const char* data, size_t len, size_t* pos) {
    if (*pos >= len) return 0xFFFD;
    unsigned char b0 = (unsigned char)data[*pos];

    if (b0 < 0x80) {
        (*pos)++;
        return (int64_t)b0;
    }

    int expected;
    int64_t cp;
    if ((b0 & 0xE0) == 0xC0) {
        expected = 2; cp = b0 & 0x1F;
    } else if ((b0 & 0xF0) == 0xE0) {
        expected = 3; cp = b0 & 0x0F;
    } else if ((b0 & 0xF8) == 0xF0) {
        expected = 4; cp = b0 & 0x07;
    } else {
        // Invalid lead byte
        (*pos)++;
        return 0xFFFD;
    }

    if (*pos + (size_t)expected > len) {
        // Truncated sequence
        (*pos)++;
        return 0xFFFD;
    }

    for (int i = 1; i < expected; i++) {
        unsigned char cb = (unsigned char)data[*pos + (size_t)i];
        if ((cb & 0xC0) != 0x80) {
            // Invalid continuation byte
            (*pos)++;
            return 0xFFFD;
        }
        cp = (cp << 6) | (cb & 0x3F);
    }

    *pos += (size_t)expected;

    // Reject overlong encodings
    if (expected == 2 && cp < 0x80) return 0xFFFD;
    if (expected == 3 && cp < 0x800) return 0xFFFD;
    if (expected == 4 && cp < 0x10000) return 0xFFFD;

    // Reject surrogates and values > U+10FFFF
    if (cp >= 0xD800 && cp <= 0xDFFF) return 0xFFFD;
    if (cp > 0x10FFFF) return 0xFFFD;

    return cp;
}

// Validate entire byte sequence as valid UTF-8.
static inline bool gorget_utf8_validate(const char* data, size_t len) {
    size_t pos = 0;
    while (pos < len) {
        size_t saved = pos;
        int64_t cp = gorget_utf8_decode(data, len, &pos);
        if (cp == 0xFFFD && (pos - saved != 1 || (unsigned char)data[saved] != 0xFD)) {
            if (saved + 3 <= len &&
                (unsigned char)data[saved] == 0xEF &&
                (unsigned char)data[saved + 1] == 0xBF &&
                (unsigned char)data[saved + 2] == 0xBD) {
                continue;  // Legitimate U+FFFD in input
            }
            return false;
        }
    }
    return true;
}

// Validate String contents as UTF-8 (convenience wrapper for codegen).
static inline bool gorget_string_is_valid_utf8(const GorgetString* s) {
    if (s->len == 0) return true;
    return gorget_utf8_validate((const char*)s->data, s->len);
}

// ── Codepoint-level Str operations ──────────────────────────
// Count codepoints — O(n) UTF-8 walk
static inline int64_t gorget_str_codepoint_count(Str s) {
    if (s.len == 0) return 0;
    const char* d = (const char*)s.data;
    int64_t count = 0;
    size_t i = 0;
    while (i < s.len) {
        i += (size_t)gorget_utf8_codepoint_len((unsigned char)d[i]);
        count++;
    }
    return count;
}

// Forward declarations
static inline Str gorget_str_own_region(const char* data, size_t len);

// Return owned copy of ith codepoint (0-based). Supports negative indexing.
static inline Str gorget_str_index(Str s, int64_t idx) {
    int64_t cp_count = gorget_str_codepoint_count(s);
    if (idx < 0) idx += cp_count;
    if (idx < 0 || idx >= cp_count) {
        gorget_panic("str index out of bounds");
    }
    const char* d = (const char*)s.data;
    size_t byte_off = 0;
    int64_t i = 0;
    while (i < idx) {
        byte_off += (size_t)gorget_utf8_codepoint_len((unsigned char)d[byte_off]);
        i++;
    }
    int cplen = gorget_utf8_codepoint_len((unsigned char)d[byte_off]);
    return gorget_str_own_region(d + byte_off, (size_t)cplen);
}

// Return owned copy of codepoint range [start, end). Supports negative indices.
static inline Str gorget_str_slice(Str s, int64_t start, int64_t end) {
    int64_t cp_count = gorget_str_codepoint_count(s);
    if (start < 0) start += cp_count;
    if (end < 0) end += cp_count;
    if (start < 0) start = 0;
    if (end > cp_count) end = cp_count;
    if (start >= end) return GORGET_EMPTY_STR;
    if (start > cp_count || end < 0) {
        gorget_panic("str slice out of bounds");
    }
    const char* d = (const char*)s.data;
    // Walk to start byte offset
    size_t start_byte = 0;
    for (int64_t i = 0; i < start; i++) {
        start_byte += (size_t)gorget_utf8_codepoint_len((unsigned char)d[start_byte]);
    }
    // Walk from start to end byte offset
    size_t end_byte = start_byte;
    for (int64_t i = start; i < end; i++) {
        end_byte += (size_t)gorget_utf8_codepoint_len((unsigned char)d[end_byte]);
    }
    return gorget_str_own_region(d + start_byte, end_byte - start_byte);
}

// Clone a region of memory into an owned Str.
static inline Str gorget_str_own_region(const char* data, size_t len) {
    if (len == 0) return GORGET_EMPTY_STR;
    return str_alloc_copy(data, len, __gorget_current_alloc);
}

// Borrow region — returns StrView (internal use only, never stored).
static inline StrView gorget_str_borrow_region_view(const char* data, size_t len) {
    return str_view_raw(data, len);
}

// Return a byte-level owned copy of s[start..end].
static inline Str gorget_str_byte_slice(Str s, int64_t start, int64_t end) {
    if (start < 0 || end < 0 || (size_t)start > s.len || (size_t)end > s.len || start > end) {
        fprintf(stderr, "gorget: panic: string byte_slice out of bounds: [%" PRId64 "..%" PRId64 "], byte length %zu\n", start, end, s.len);
        exit(1);
    }
    return gorget_str_own_region((const char*)s.data + start, (size_t)(end - start));
}

// Return an owned copy of the character at the given byte index.
static inline Str gorget_str_char_at(Str s, int64_t index) {
    if (index < 0 || (size_t)index >= s.len) {
        return GORGET_EMPTY_STR;
    }
    return gorget_str_own_region((const char*)s.data + index, 1);
}

// Return the byte at index (byte-level). Bounds-checked against byte length.
static inline uint8_t gorget_str_byte_at(Str s, int64_t index) {
    if (index < 0 || (size_t)index >= s.len) {
        fprintf(stderr, "gorget: panic: string byte index out of bounds: index %" PRId64 ", byte length %zu\n", index, s.len);
        exit(1);
    }
    return (uint8_t)((const char*)s.data)[index];
}

// ── UTF-8 encode helper ─────────────────────────────────────
// Encode a Unicode codepoint to UTF-8. Writes 1-4 bytes to out[]. Returns bytes written.
static inline int gorget_utf8_encode(int64_t cp, char* out) {
    if (cp < 0x80) {
        out[0] = (char)cp;
        return 1;
    }
    if (cp < 0x800) {
        out[0] = (char)(0xC0 | (cp >> 6));
        out[1] = (char)(0x80 | (cp & 0x3F));
        return 2;
    }
    if (cp < 0x10000) {
        out[0] = (char)(0xE0 | (cp >> 12));
        out[1] = (char)(0x80 | ((cp >> 6) & 0x3F));
        out[2] = (char)(0x80 | (cp & 0x3F));
        return 3;
    }
    if (cp <= 0x10FFFF) {
        out[0] = (char)(0xF0 | (cp >> 18));
        out[1] = (char)(0x80 | ((cp >> 12) & 0x3F));
        out[2] = (char)(0x80 | ((cp >> 6) & 0x3F));
        out[3] = (char)(0x80 | (cp & 0x3F));
        return 4;
    }
    // Invalid codepoint — emit U+FFFD
    out[0] = (char)0xEF; out[1] = (char)0xBF; out[2] = (char)0xBD;
    return 3;
}

// ── Str-native search primitive ─────────────────────────────
// memmem implementation (always available, no _GNU_SOURCE dependency).
static inline const char* gorget_memmem(const char* h, size_t hlen, const char* n, size_t nlen) {
    if (nlen == 0) return h;
    if (nlen > hlen) return NULL;
    const char first = n[0];
    const char* end = h + hlen - nlen + 1;
    for (const char* p = h; p < end; p++) {
        p = (const char*)memchr(p, first, (size_t)(end - p));
        if (!p) return NULL;
        if (memcmp(p, n, nlen) == 0) return p;
    }
    return NULL;
}



// ── Str-aware String operations ───────────────────────

// Str concatenation — both args are 32-byte Str structs by value.
static inline GorgetString gorget_str_cat(Str a, Str b) {
    __gorget_str_cat_count++;
    size_t la = a.len;
    size_t lb = b.len;
    if (la + lb == 0) return GORGET_EMPTY_STR;
    GorgetAllocator* al = __gorget_current_alloc;
    size_t total = la + lb;
    size_t cap = total + 1;
    char* data = (char*)al->alloc(al->ctx, cap);
    if (la > 0) memcpy(data, a.data, la);
    if (lb > 0) memcpy(data + la, b.data, lb);
    data[total] = '\0';
    return (Str){ .data = data, .cap = cap, .len = total, .alloc = al };
}

// Str-aware append to a String builder.
static inline void gorget_string_append_str(GorgetString* s, Str rhs) {
    size_t rlen = rhs.len;
    if (rlen == 0) return;
    if (s->cap == 0) {
        // View or empty — materialize into a fresh owned buffer.
        GorgetAllocator* a = __gorget_current_alloc;
        size_t new_len = s->len + rlen;
        size_t new_cap = (new_len + 1) * 2;
        char* data = (char*)a->alloc(a->ctx, new_cap);
        if (s->len > 0 && s->data) memcpy(data, s->data, s->len);
        memcpy(data + s->len, rhs.data, rlen);
        data[new_len] = '\0';
        *s = (Str){ .data = data, .cap = new_cap, .len = new_len, .alloc = a };
        return;
    }
    size_t new_len = s->len + rlen;
    if (new_len + 1 > s->cap) {
        size_t new_cap = (new_len + 1) * 2;
        s->data = s->alloc->realloc(s->alloc->ctx, s->data, s->cap, new_cap);
        s->cap = new_cap;
    }
    memcpy((char*)s->data + s->len, rhs.data, rlen);
    ((char*)s->data)[new_len] = '\0';
    s->len = new_len;
}

// Create a String from a Str (deep clone — always an owned copy).
static inline GorgetString gorget_string_from_str(Str s) {
    if (s.len == 0) return GORGET_EMPTY_STR;
    return str_alloc_copy((const char*)s.data, s.len, __gorget_current_alloc);
}

// ── cstr ↔ Str conversion ───────────────────────────────────
// Str's data pointer is NUL-terminated for owned strings (we +1 the cap in
// str_alloc_*) and for literal views (they point at C string literals).
// Views from slice/char_at/... are NOT NUL-terminated — callers of cstr
// should not be passing those (this plan keeps slice/char_at allocating).
static inline const char* gorget_str_to_cstr(Str s) {
    return s.data ? (const char*)s.data : "";
}

// Check for embedded null bytes.
static inline bool gorget_str_has_null(Str s) {
    if (s.len == 0) return false;
    return memchr(s.data, '\0', s.len) != NULL;
}


// ── Panic helper ─────────────────────────────────────────────
static inline void gorget_panic(const char* msg) {
    fprintf(stderr, "gorget: panic: %s\n", msg);
    exit(1);
}

// ── LIR helpers ──
static inline Str gorget_str_default(void) { return GORGET_EMPTY_STR; }
static inline int64_t int64_t__default(void) { return 0; }
static inline int64_t int__default(void) { return 0; }
static inline int8_t int8_t__default(void) { return 0; }
static inline int16_t int16_t__default(void) { return 0; }
static inline int32_t int32_t__default(void) { return 0; }
static inline uint8_t uint8_t__default(void) { return 0; }
static inline uint16_t uint16_t__default(void) { return 0; }
static inline uint32_t uint32_t__default(void) { return 0; }
static inline uint64_t uint64_t__default(void) { return 0; }
static inline double double__default(void) { return 0.0; }
static inline double float__default(void) { return 0.0; }
static inline bool bool__default(void) { return false; }
static inline int64_t __gorget_hash_int(int64_t v) { return (int64_t)__gorget_fnv1a(&v, sizeof(v)); }
static inline int64_t gorget_str_hash(Str s) { return (int64_t)__gorget_hash_str_len((const char*)s.data, s.len); }
#ifndef _WIN32
#include <signal.h>
#endif
static int gorget_generic_compare(const void* a, const void* b) { return memcmp(a, b, sizeof(int64_t)); }
static int gorget_int_compare(const void* a, const void* b) { int64_t va = *(const int64_t*)a, vb = *(const int64_t*)b; return (va > vb) - (va < vb); }
static int gorget_float_compare(const void* a, const void* b) { double da = *(const double*)a, db = *(const double*)b; return (da > db) - (da < db); }
static int gorget_str_compare(const void* a, const void* b) { Str sa = *(const Str*)a, sb = *(const Str*)b; size_t la = sa.len, lb = sb.len; size_t ml = la < lb ? la : lb; int r = ml > 0 ? memcmp(sa.data, sb.data, ml) : 0; if (r) return r; return (la > lb) - (la < lb); }
static inline int64_t int64_t__one(void) { return 1; }
static inline int64_t int__one(void) { return 1; }
static inline double double__one(void) { return 1.0; }
static inline double float__one(void) { return 1.0; }

typedef struct TaskHandle TaskHandle;
typedef struct GorgetRange GorgetRange;

// TaskHandle
struct TaskHandle {
    void* task_ptr;
    void* drop_fn;
};

// GorgetRange
struct GorgetRange {
    int64_t start;
    int64_t end;
    int64_t step;
};



// ── Static string literals (views into .rodata, cap=0) ──
static const Str __slit_0 = { .data = (void*)"Fibonacci sequence:\n", .cap = 0, .len = 20, .alloc = NULL };
static const Str __slit_1 = { .data = (void*)"  fib(%lld) = %lld\n", .cap = 0, .len = 19, .alloc = NULL };
static const Str __slit_2 = { .data = (void*)"Recursive check:\n", .cap = 0, .len = 17, .alloc = NULL };
static const Str __slit_3 = { .data = (void*)"All checks passed.\n", .cap = 0, .len = 19, .alloc = NULL };
static const Str __slit_4 = { .data = (void*)"mismatch!", .cap = 0, .len = 9, .alloc = NULL };

int64_t fib_recursive(int64_t __p0);
int64_t fib_iterative(int64_t __p0);
int main(int argc, char** argv);

// ── Function Definitions ──
int64_t fib_recursive(int64_t __p0) {
    int64_t __s0 = 0;
    int64_t __s1 = 0;
    bool __s2 = 0;
    int64_t __s3 = 0;
    int64_t __s4 = 0;
    int64_t __s5 = 0;
    int64_t __s6 = 0;
    int64_t __s7 = 0;
    int64_t __v0;
    void* __v1;
    int64_t __v2;
    bool __v3;
    void* __v4;
    void* __v5;
    int64_t __v6;
    int64_t __v7;
    void* __v8;
    int64_t __v9;
    void* __v10;
    int64_t __v11;
    int64_t __v12;
    void* __v13;
    int64_t __v14;
    void* __v15;
    void* __v16;
    int64_t __v17;

__bb0:
    __v0 = __p0;
    __v2 = (int64_t)1LL;
    __v3 = __v0 <= __v2;
    if (__v3) {
        goto __bb2;
    } else {
        goto __bb1;
    }
__bb1:
    __v6 = (int64_t)1LL;
    if (__builtin_sub_overflow((int64_t)__v0, (int64_t)__v6, &__v7)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __v9 = fib_recursive(__v7);
    __v11 = (int64_t)2LL;
    if (__builtin_sub_overflow((int64_t)__v0, (int64_t)__v11, &__v12)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __v14 = fib_recursive(__v12);
    if (__builtin_add_overflow((int64_t)__v9, (int64_t)__v14, &__v17)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    return __v17;
__bb2:
    return __v0;
}

int64_t fib_iterative(int64_t __p0) {
    int64_t __s0 = 0;
    int64_t __s1 = 0;
    int64_t __s2 = 0;
    int64_t __s3 = 0;
    int64_t __s4 = 0;
    bool __s5 = 0;
    int64_t __s6 = 0;
    int64_t __s7 = 0;
    int64_t __s8 = 0;
    int64_t __v0;
    int64_t __v1;
    int64_t __v2;
    int64_t __v3;
    void* __v4;
    void* __v5;
    bool __v6;
    void* __v7;
    void* __v8;
    void* __v9;
    void* __v10;
    int64_t __v11;
    void* __v12;
    void* __v13;
    void* __v14;
    int64_t __v15;
    int64_t __v16;
    void* __v17;
    void* __v18;
    void* __v19;
    int64_t __v20;
    int64_t __v21;
    int64_t __v22;
    int64_t __v23;
    int64_t __bp20;
    int64_t __bp21;
    int64_t __bp22;
    int64_t __bp23;

__bb0:
    __v0 = __p0;
    __v1 = (int64_t)0LL;
    __v2 = (int64_t)1LL;
    __v3 = (int64_t)0LL;
    __bp20 = __v3; __bp21 = __v0; __bp22 = __v2; __bp23 = __v1; goto __bb1;
__bb1:
    __v20 = __bp20;
    __v21 = __bp21;
    __v22 = __bp22;
    __v23 = __bp23;
    __v6 = __v20 < __v21;
    if (__v6) {
        goto __bb2;
    } else {
        goto __bb3;
    }
__bb2:
    if (__builtin_add_overflow((int64_t)__v23, (int64_t)__v22, &__v11)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __v15 = (int64_t)1LL;
    if (__builtin_add_overflow((int64_t)__v20, (int64_t)__v15, &__v16)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __bp20 = __v16; __bp21 = __v21; __bp22 = __v11; __bp23 = __v22; goto __bb1;
__bb3:
    return __v23;
}

int main(int argc, char** argv) {
    gorget_init_args(argc, argv);
    int32_t __s0 = 0;
    int32_t __s1 = 0;
    int64_t __s2 = 0;
    bool __s3 = 0;
    int64_t __s4 = 0;
    int64_t __s5 = 0;
    int32_t __s6 = 0;
    int64_t __s7 = 0;
    int32_t __s8 = 0;
    int64_t __s9 = 0;
    bool __s10 = 0;
    int64_t __s11 = 0;
    int64_t __s12 = 0;
    int64_t __s13 = 0;
    int64_t __s14 = 0;
    bool __s15 = 0;
    void* __s16 = {0};
    int32_t __s17 = 0;
    int64_t __s18 = 0;
    int32_t __s19 = 0;
    Str __v0;
    int32_t __v1;
    int64_t __v2;
    void* __v3;
    int64_t __v4;
    bool __v5;
    void* __v6;
    void* __v7;
    int64_t __v8;
    void* __v9;
    Str __v10;
    void* __v11;
    void* __v12;
    int32_t __v13;
    void* __v14;
    int64_t __v15;
    int64_t __v16;
    void* __v17;
    Str __v18;
    int32_t __v19;
    int64_t __v20;
    void* __v21;
    int64_t __v22;
    bool __v23;
    void* __v24;
    void* __v25;
    int64_t __v26;
    void* __v27;
    void* __v28;
    int64_t __v29;
    void* __v30;
    void* __v31;
    void* __v32;
    bool __v33;
    void* __v34;
    Str __v35;
    int32_t __v36;
    void* __v37;
    int32_t __v38;
    Str __v39;
    void* __v40;
    void* __v41;
    int32_t __v42;
    void* __v43;
    int64_t __v44;
    int64_t __v45;
    void* __v46;
    Str __v47;
    int64_t __v48;
    int64_t __v49;
    int64_t __bp48;
    int64_t __bp49;

__bb0:
    __v0 = __slit_0;
    __v1 = __gorget_printf("%.*s", (int)__v0.len, (const char*)__v0.data);

    __v2 = (int64_t)0LL;
    __bp48 = __v2; goto __bb1;
__bb1:
    __v48 = __bp48;
    __v4 = (int64_t)20LL;
    __v5 = __v48 < __v4;
    if (__v5) {
        goto __bb2;
    } else {
        goto __bb3;
    }
__bb2:
    __v8 = fib_iterative(__v48);
    __v10 = __slit_1;
    __v13 = __gorget_printf((const char*)__v10.data, __v48, __v8);
    __v15 = (int64_t)1LL;
    if (__builtin_add_overflow((int64_t)__v48, (int64_t)__v15, &__v16)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __bp48 = __v16; goto __bb1;
__bb3:
    __v18 = __slit_2;
    __v19 = __gorget_printf("%.*s", (int)__v18.len, (const char*)__v18.data);

    __v20 = (int64_t)0LL;
    __bp49 = __v20; goto __bb4;
__bb4:
    __v49 = __bp49;
    __v22 = (int64_t)15LL;
    __v23 = __v49 < __v22;
    if (__v23) {
        goto __bb5;
    } else {
        goto __bb6;
    }
__bb5:
    __v26 = fib_recursive(__v49);
    __v29 = fib_iterative(__v49);
    __v33 = __v26 == __v29;
    if (__v33) {
        goto __bb7;
    } else {
        goto __bb8;
    }
__bb6:
    __v35 = __slit_3;
    __v36 = __gorget_printf("%.*s", (int)__v35.len, (const char*)__v35.data);

    __v38 = (int32_t)0LL;
    return __v38;
__bb7:
    __v39 = __slit_1;
    __v42 = __gorget_printf((const char*)__v39.data, __v49, __v26);
    __v44 = (int64_t)1LL;
    if (__builtin_add_overflow((int64_t)__v49, (int64_t)__v44, &__v45)) { fprintf(stderr, "gorget: integer overflow\n"); exit(1); }
    __bp49 = __v45; goto __bb4;
__bb8:
    __v47 = __slit_4;
    gorget_panic(__v47);
    __builtin_unreachable();
}

