/// Embedded runtime header included at the top of every generated C file.
pub const RUNTIME: &str = r#"// Generated by Vyper compiler v0.1.0
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include <stdarg.h>

"#;
