//! `ggdef` — the definitional interpreter for Gorget Core (GGC).
//!
//! `ggdef` IS the meaning of Gorget's dynamic semantics (RFC §1): a small
//! eager-value-semantics interpreter whose behaviour defines what a program
//! means. Production stays borrows + lazy CoW — an optimisation with an
//! observational-equivalence obligation (D1). This crate shares the production
//! **lexer + parser + AST only**; the fence against `ir`/`semantic`/`lir`/
//! `bir`/`backend` is the import ratchet in `tests/lints.rs`.
//!
//! Increment A is the walking skeleton: the elaborator + evaluator for the
//! honest subset the first ~20 `cow_*` fixtures use (int/bool/float scalars,
//! `String`, `Vector`, structs, tuples; bare/`&`/`!` modes; materialize-on-
//! write). See `docs/plans/define-gorget/phase0-brief.md`.

pub mod classify;
pub mod elaborate;
pub mod eval;
pub mod frontmatter;
pub mod ggc;
pub mod trace;

pub use classify::{
    classifiable_fixture_names, classify_fixture, Classification, CLASSIFY_EXCLUDE, CLASSIFY_FUEL,
};
pub use elaborate::{elaborate, ElabError};
pub use eval::{run, Fault, Outcome, Run, EXIT_FUEL, EXIT_ILLFORMED, EXIT_TRAP, EXIT_VALUE};
pub use frontmatter::{parse_frontmatter, Expect, Frontmatter, FrontmatterError};

use std::collections::BTreeMap;
use std::path::Path;

use gorget::parser::Parser;

/// The default fuel bound for CLI runs — generous; every phase-0 fixture
/// terminates in far fewer steps. Non-termination surfaces as `FuelExhausted`.
pub const DEFAULT_FUEL: u64 = 50_000_000;

/// A frontend (parse + elaborate) failure, distinct from an evaluation
/// outcome. Parse errors reclassify a program to the `parse-error` tier;
/// elaboration errors are the stop-and-report signal (a construct outside the
/// A subset, or a shape the elaborator will not fake).
#[derive(Debug)]
pub enum FrontendError {
    Parse(Vec<String>),
    Elaborate(ElabError),
}

impl std::fmt::Display for FrontendError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FrontendError::Parse(errs) => {
                writeln!(f, "{} parse error(s):", errs.len())?;
                for e in errs {
                    writeln!(f, "  {e}")?;
                }
                Ok(())
            }
            FrontendError::Elaborate(e) => {
                write!(f, "elaboration error @ {}..{}: {}", e.span.start, e.span.end, e.message)
            }
        }
    }
}

/// Parse + elaborate a source string into a GGC program.
pub fn frontend(source: &str) -> Result<ggc::Program, FrontendError> {
    let mut parser = Parser::new(source);
    let module = parser.parse_module();
    if !parser.errors.is_empty() {
        return Err(FrontendError::Parse(parser.errors.iter().map(|e| e.to_string()).collect()));
    }
    elaborate(&module).map_err(FrontendError::Elaborate)
}

/// Parse, elaborate, and run a source string, bounded by `fuel`.
pub fn run_source(source: &str, fuel: u64) -> Result<Run, FrontendError> {
    Ok(run(&frontend(source)?, fuel))
}

// ── `ggdef -- gen` — expectation generation for `spectests/` fixtures ──────────
//
// A `spectests/` fixture is an ordinary `.gg` program carrying a frontmatter
// block in leading `#` comments (invisible to the lexer, so `run`/`trace` work
// unchanged). `gen` RUNS the program and writes the observed outcome back into
// the frontmatter's `expect:` block, in place. This is how conformance
// expectations "flow FROM the definition" (RFC §4) rather than being copied off
// whichever backend came first. It is idempotent: running it twice is a no-op,
// which is what the `gen_idempotent` gate asserts.
//
// Frontmatter shape (the fence markers are themselves comments):
//
//   #!spectest
//   # mode: run
//   # adjudicator: ggdef
//   # expect:                 <- this block is REGENERATED by `gen`; keep it last
//   #   exit: 0
//   #   stdout: "9\n"
//   #!end

/// The opening / closing fence lines of a spectest frontmatter block.
pub const FENCE_OPEN: &str = "#!spectest";
pub const FENCE_CLOSE: &str = "#!end";

/// A `gen` failure: either the program did not run cleanly (a `mode: run`
/// fixture whose body traps at the frontend is itself invalid), or the file has
/// no frontmatter fence to write into.
#[derive(Debug)]
pub enum GenError {
    Frontend(FrontendError),
    NoFrontmatter,
}

impl std::fmt::Display for GenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GenError::Frontend(e) => write!(f, "{e}"),
            GenError::NoFrontmatter => write!(
                f,
                "no `{FENCE_OPEN}` … `{FENCE_CLOSE}` frontmatter fence — cannot write `expect:`"
            ),
        }
    }
}

/// Run `source` and return it with the frontmatter `expect:` block regenerated
/// from the observed outcome. Pure (no I/O) so it is trivially testable; the CLI
/// wraps it with a read + write-back. Idempotent: `gen(gen(x)) == gen(x)`.
pub fn gen_frontmatter(source: &str, fuel: u64) -> Result<String, GenError> {
    let run = run_source(source, fuel).map_err(GenError::Frontend)?;
    let block = render_expect_block(&run);
    splice_expect(source, &block)
}

/// The canonical `expect:` block for a run outcome — `exit:` (the outcome code)
/// plus `stdout:` as a JSON-escaped string (a canonical, unambiguous, and thus
/// idempotent serialisation of arbitrary bytes, incl. newlines).
fn render_expect_block(run: &Run) -> Vec<String> {
    render_expect_block_from(run.outcome.exit_code(), &run.stdout)
}

/// The `expect:` block from a bare `(exit, stdout)` pair — the same
/// serialisation `render_expect_block` uses, factored out so a future
/// serializer (D2) can produce a block WITHOUT reconstructing a `Run`, on the
/// SAME `json_escape` the frontmatter reader inverts. The round-trip
/// (`json_escape` ⇄ `parse_json_string`) is unit-tested (`src/tests.rs`).
pub fn render_expect_block_from(exit: i32, stdout: &str) -> Vec<String> {
    vec![
        "# expect:".to_string(),
        format!("#   exit: {exit}"),
        format!("#   stdout: \"{}\"", json_escape(stdout)),
    ]
}

/// Replace the `# expect:` sub-block (everything from the `# expect:` line up to
/// the closing fence) with `block`. If no `# expect:` line exists yet, `block`
/// is inserted just before the closing fence. `expect:` is required to be the
/// LAST key in the frontmatter (documented convention; keeps the splice a single
/// contiguous range and the round-trip byte-exact).
fn splice_expect(source: &str, block: &[String]) -> Result<String, GenError> {
    let lines: Vec<&str> = source.lines().collect();
    let open = lines.iter().position(|l| l.trim_end() == FENCE_OPEN);
    let close = lines.iter().position(|l| l.trim_end() == FENCE_CLOSE);
    let (open, close) = match (open, close) {
        (Some(o), Some(c)) if o < c => (o, c),
        _ => return Err(GenError::NoFrontmatter),
    };

    // The `# expect:` line inside the fence, if any.
    let expect_start = (open + 1..close).find(|&i| {
        let t = lines[i].trim_start();
        t.strip_prefix('#').map(str::trim_start).is_some_and(|k| k.starts_with("expect:"))
    });

    let mut out: Vec<String> = Vec::with_capacity(lines.len() + block.len());
    match expect_start {
        Some(es) => {
            // Keep [.. expect_start), drop [expect_start .. close), insert block,
            // keep [close ..].
            out.extend(lines[..es].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
        None => {
            // Insert the block just before the closing fence.
            out.extend(lines[..close].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
    }

    let mut joined = out.join("\n");
    joined.push('\n'); // fixtures end with exactly one trailing newline
    Ok(joined)
}

/// Escape a string for embedding in a JSON string literal (hand-rolled — no
/// deps, per the interpreter-discipline rule; mirrors `trace::escape_json`).
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

// ── `ggdef -- migrate` — populate `spectests/run/` from the AGREE set (D1) ─────
//
// The migration copies every ggdef-adjudicated AGREE fixture (`classify_fixture`
// == `Agree`) out of `tests/fixtures/` into `spectests/run/`, prepends a
// `#!spectest` frontmatter block (`mode: run`, `adjudicator: ggdef`), and fills
// the `expect:` block IN-PROCESS via `gen_frontmatter` — the expectation flows
// FROM the definition (RFC §4), never copied off a backend. Selection is EXACTLY
// the `Agree` bucket the `converter_agreement` gate asserts on (the SAME
// predicate), so the migrated set and the agreement floor can never diverge.

/// The outcome of a `migrate` run: the fixtures written, and a census of the
/// non-`Agree` verdicts (for the CLI report — they are NOT migrated).
#[derive(Debug, Default)]
pub struct MigrateReport {
    /// Fixture file names written into `spectests/run/`, sorted.
    pub migrated: Vec<String>,
    /// Count of each non-`Agree` verdict encountered in the walk.
    pub skipped: BTreeMap<&'static str, usize>,
}

/// A `migrate` failure. `NonzeroExit` is the tripwire the brief mandates: an
/// `Agree` fixture is a `run_gg` pair, so its ggdef outcome is a `Value` (exit
/// 0) by construction — a nonzero exit would silently activate a filed dormant
/// hazard in the C/LLVM lanes, so we STOP and report instead of writing it.
#[derive(Debug)]
pub enum MigrateError {
    Io(std::io::Error),
    Gen(String, GenError),
    Frontmatter(String, FrontmatterError),
    NonzeroExit { name: String, exit: i32 },
}

impl std::fmt::Display for MigrateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MigrateError::Io(e) => write!(f, "I/O error: {e}"),
            MigrateError::Gen(name, e) => write!(f, "gen `{name}`: {e}"),
            MigrateError::Frontmatter(name, e) => write!(f, "re-parse `{name}`: {e}"),
            MigrateError::NonzeroExit { name, exit } => write!(
                f,
                "`{name}` generated a NONZERO exit ({exit}) — an AGREE fixture must be exit-0 by \
                 construction. STOP: this would activate the filed dormant exit≠0 branch in the \
                 C/LLVM run lanes. Triage before migrating."
            ),
        }
    }
}

impl std::error::Error for MigrateError {}

/// Run the D1 migration. `ws_root` is the workspace root; the tool reads
/// `tests/fixtures/` + `tests/integration.rs` and writes `spectests/run/`.
/// Runs the whole walk in a 2 GiB-stack thread (ggdef's big-step eval recurses
/// on the native stack).
pub fn migrate(ws_root: &Path) -> Result<MigrateReport, MigrateError> {
    let ws = ws_root.to_path_buf();
    std::thread::Builder::new()
        .stack_size(2 * 1024 * 1024 * 1024)
        .name("ggdef-migrate".to_string())
        .spawn(move || migrate_body(&ws))
        .unwrap()
        .join()
        .unwrap()
}

fn migrate_body(ws_root: &Path) -> Result<MigrateReport, MigrateError> {
    let fixtures_dir = ws_root.join("tests/fixtures");
    let run_dir = ws_root.join("spectests/run");
    let integ =
        std::fs::read_to_string(ws_root.join("tests/integration.rs")).map_err(MigrateError::Io)?;

    let mut report = MigrateReport::default();
    for name in classify::classifiable_fixture_names(&fixtures_dir) {
        let src = std::fs::read_to_string(fixtures_dir.join(&name)).map_err(MigrateError::Io)?;
        match classify::classify_fixture(&name, &src, &integ) {
            Classification::Agree => {
                // Frame the body with a run-tier `#!spectest` block, then let
                // `gen_frontmatter` splice the `expect:` (kept LAST) from a
                // fresh definitional run.
                let framed = prepend_frontmatter(&src, &name);
                let generated = gen_frontmatter(&framed, DEFAULT_FUEL)
                    .map_err(|e| MigrateError::Gen(name.clone(), e))?;
                // Exit-0 tripwire (brief): re-read the just-written expectation.
                let fm = parse_frontmatter(&generated)
                    .map_err(|e| MigrateError::Frontmatter(name.clone(), e))?;
                if fm.expect.exit != 0 {
                    return Err(MigrateError::NonzeroExit { name, exit: fm.expect.exit });
                }
                std::fs::write(run_dir.join(&name), &generated).map_err(MigrateError::Io)?;
                report.migrated.push(name);
            }
            Classification::Float => *report.skipped.entry("float-hold").or_default() += 1,
            Classification::Other { .. } => *report.skipped.entry("other-mismatch").or_default() += 1,
            Classification::NotValue => *report.skipped.entry("not-value").or_default() += 1,
            Classification::NoPair => *report.skipped.entry("no-run_gg-pair").or_default() += 1,
            Classification::FrontendError => {
                *report.skipped.entry("frontend-error").or_default() += 1
            }
        }
    }
    Ok(report)
}

/// Frame a fixture body with a run-tier `#!spectest` frontmatter block. The
/// `expect:` line is intentionally ABSENT — `gen_frontmatter` inserts it just
/// before the closing fence (`splice_expect`), keeping it LAST per the fence
/// convention. `doc:` records the legacy-harness provenance (inline scalar).
fn prepend_frontmatter(src: &str, name: &str) -> String {
    let mut out = String::new();
    out.push_str(FENCE_OPEN);
    out.push('\n');
    out.push_str("# mode: run\n");
    out.push_str("# adjudicator: ggdef\n");
    out.push_str(&format!("# doc: migrated from tests/fixtures/{name} (run_gg pair)\n"));
    out.push_str(FENCE_CLOSE);
    out.push('\n');
    out.push_str(src);
    out
}

#[cfg(test)]
mod tests;
