//! `ggdef` — the definitional interpreter for Gorget Core (GGC).
//!
//! `ggdef` IS the meaning of Gorget's dynamic semantics (RFC §1): a small
//! eager-value-semantics interpreter whose behaviour defines what a program
//! means. Production stays borrows + lazy CoW — an optimisation with an
//! observational-equivalence obligation (D1). This crate shares the production
//! **lexer + parser + AST only**; the fence against `ir`/`semantic`/`lir`/
//! `bir`/`backend` is the import ratchet in `tests/lints.rs`.
//!
//! Increment A is the walking skeleton: the elaborator + evaluator for the
//! honest subset the first ~20 `cow_*` fixtures use (int/bool/float scalars,
//! `String`, `Vector`, structs, tuples; bare/`&`/`!` modes; materialize-on-
//! write). See `docs/plans/define-gorget/phase0-brief.md`.

pub mod classify;
pub mod elaborate;
pub mod eval;
pub mod frontmatter;
pub mod ggc;
pub mod trace;

pub use classify::{
    classifiable_fixture_names, classify_fixture, Classification, CLASSIFY_EXCLUDE, CLASSIFY_FUEL,
};
pub use elaborate::{elaborate, ElabError};
pub use eval::{run, Outcome, Run, TrapKind, EXIT_FUEL, EXIT_ILLFORMED, EXIT_TRAP, EXIT_VALUE};
pub use frontmatter::{parse_frontmatter, Expect, Frontmatter, FrontmatterError};

use std::collections::BTreeMap;
use std::path::Path;

use gorget::parser::Parser;

/// The default fuel bound for CLI runs — generous; every phase-0 fixture
/// terminates in far fewer steps. Non-termination surfaces as `FuelExhausted`.
pub const DEFAULT_FUEL: u64 = 50_000_000;

/// A frontend (parse + elaborate) failure, distinct from an evaluation
/// outcome. Parse errors reclassify a program to the `parse-error` tier;
/// elaboration errors are the stop-and-report signal (a construct outside the
/// A subset, or a shape the elaborator will not fake).
#[derive(Debug)]
pub enum FrontendError {
    Parse(Vec<String>),
    Elaborate(ElabError),
}

impl std::fmt::Display for FrontendError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FrontendError::Parse(errs) => {
                writeln!(f, "{} parse error(s):", errs.len())?;
                for e in errs {
                    writeln!(f, "  {e}")?;
                }
                Ok(())
            }
            FrontendError::Elaborate(e) => {
                write!(f, "elaboration error @ {}..{}: {}", e.span.start, e.span.end, e.message)
            }
        }
    }
}

/// Parse + elaborate a source string into a GGC program.
pub fn frontend(source: &str) -> Result<ggc::Program, FrontendError> {
    let mut parser = Parser::new(source);
    let module = parser.parse_module();
    if !parser.errors.is_empty() {
        return Err(FrontendError::Parse(parser.errors.iter().map(|e| e.to_string()).collect()));
    }
    elaborate(&module).map_err(FrontendError::Elaborate)
}

/// Parse, elaborate, and run a source string, bounded by `fuel`.
pub fn run_source(source: &str, fuel: u64) -> Result<Run, FrontendError> {
    Ok(run(&frontend(source)?, fuel))
}

// ── `ggdef -- gen` — expectation generation for `spectests/` fixtures ──────────
//
// A `spectests/` fixture is an ordinary `.gg` program carrying a frontmatter
// block in leading `#` comments (invisible to the lexer, so `run`/`trace` work
// unchanged). `gen` RUNS the program and writes the observed outcome back into
// the frontmatter's `expect:` block, in place. This is how conformance
// expectations "flow FROM the definition" (RFC §4) rather than being copied off
// whichever backend came first. It is idempotent: running it twice is a no-op,
// which is what the `gen_idempotent` gate asserts.
//
// Frontmatter shape (the fence markers are themselves comments):
//
//   #!spectest
//   # mode: run
//   # adjudicator: ggdef
//   # expect:                 <- this block is REGENERATED by `gen`; keep it last
//   #   exit: 0
//   #   stdout: "9\n"
//   #!end

/// The opening / closing fence lines of a spectest frontmatter block.
pub const FENCE_OPEN: &str = "#!spectest";
pub const FENCE_CLOSE: &str = "#!end";

/// A `gen` failure: either the program did not run cleanly (a `mode: run`
/// fixture whose body traps at the frontend is itself invalid), the file has
/// no frontmatter fence to write into, or the program evaluated to a CODELESS
/// eval-internal `IllFormed` (see `CodelessIllFormed`).
#[derive(Debug)]
pub enum GenError {
    Frontend(FrontendError),
    NoFrontmatter,
    /// The program evaluated to an eval-internal `IllFormed` carrying NO ratified
    /// `E_` reject code (no `main`; or eval's defense-in-depth read-of-moved that
    /// the static may-move gate did not catch). Such an outcome renders as
    /// `exit: 1` with no `reject:` line, which the frontmatter READER rejects
    /// (`RejectExitWithoutCode`, `frontmatter.rs`) — so writing it would brick
    /// EVERY conformance lane. The writer⇄reader biconditional is the contract:
    /// ELABORATE owns every ratified static rejection (`verdict = elaborate ∘
    /// eval`, decisions.md), so a codeless `IllFormed` is not a generatable
    /// conformance outcome. `gen` REFUSES instead of emitting an unparseable
    /// block — keeping the missing-gate / no-`main` hole VISIBLE. The `String` is
    /// the eval-internal `IllFormed` message, for the report.
    CodelessIllFormed(String),
    /// The block `gen` was about to write does NOT parse back cleanly — the
    /// writer⇄reader biconditional (`frontmatter.rs`) would be violated by the
    /// file we were about to commit. This is the CLASS backstop: `gen`
    /// self-validates its SPLICED would-be output through `parse_frontmatter`
    /// before returning (the same idiom `migrate` uses, `lib.rs`), so ANY future
    /// `Outcome` whose rendered block the reader refuses is caught by
    /// construction — not just today's codeless `IllFormed` (which the specific
    /// `CodelessIllFormed` guard names first). For the current taxonomy this is
    /// UNREACHABLE (the round-trip test transitively pins it); it fires only if a
    /// new outcome/render path ever emits a block the reader rejects.
    UnparseableRender(FrontmatterError),
}

impl std::fmt::Display for GenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GenError::Frontend(e) => write!(f, "{e}"),
            GenError::NoFrontmatter => write!(
                f,
                "no `{FENCE_OPEN}` … `{FENCE_CLOSE}` frontmatter fence — cannot write `expect:`"
            ),
            GenError::CodelessIllFormed(msg) => write!(
                f,
                "program is an eval-internal `IllFormed` with no ratified `E_` reject code \
                 ({msg}) — not a generatable conformance outcome. Every ratified static \
                 rejection is owned by elaborate and carries an `E_` code (`verdict = elaborate \
                 ∘ eval`); a codeless `IllFormed` means the program has no `main`, or the static \
                 may-move gate missed a move eval caught defensively. Fix the program (add \
                 `main`) or the gate (file/fix the liveness hole) — do NOT commit an `exit: 1` \
                 block with no `reject:` code (the frontmatter reader refuses it, bricking every \
                 conformance lane)."
            ),
            GenError::UnparseableRender(e) => write!(
                f,
                "the `expect:` block `gen` was about to write does NOT parse back \
                 ({e}) — writing it would violate the writer⇄reader biconditional and \
                 brick every conformance lane. This is the class backstop: `gen` \
                 self-validates its spliced output before committing. A render path \
                 produced a block the frontmatter reader refuses — fix the renderer or \
                 the reader so they agree."
            ),
        }
    }
}

/// Run `source` and return it with the frontmatter `expect:` block regenerated
/// from the observed outcome. Pure (no I/O) so it is trivially testable; the CLI
/// wraps it with a read + write-back. Idempotent: `gen(gen(x)) == gen(x)`.
pub fn gen_frontmatter(source: &str, fuel: u64) -> Result<String, GenError> {
    let run = run_source(source, fuel).map_err(GenError::Frontend)?;
    // Writer⇄reader biconditional (frontmatter.rs `RejectExitWithoutCode`): an
    // exit-1 static rejection MUST carry an `E_` reject code. ELABORATE owns every
    // ratified static rejection, so a CODELESS `IllFormed` here is eval-internal
    // (no `main`, or a defense-in-depth read-of-moved the static gate missed) — NOT
    // a generatable conformance outcome. Refuse rather than emit an unparseable
    // `exit: 1`/no-`reject:` block that would brick every lane. (Belt-and-suspenders
    // with `render_expect_block`'s keying: this is the LOUD, early stop.)
    if let Outcome::IllFormed(msg) = &run.outcome {
        if run.reject_code.is_none() {
            return Err(GenError::CodelessIllFormed(msg.clone()));
        }
    }
    let block = render_expect_block(&run);
    let spliced = splice_expect(source, &block)?;
    // Class backstop for the writer⇄reader biconditional: self-validate the
    // SPLICED would-be file through `parse_frontmatter` before returning it —
    // NOT the bare rendered block (`parse_frontmatter` requires the full
    // `#!spectest`…`#!end` fenced source; its first act is `fence_body`, so a
    // bare block would `NoFence`-fail on every call). This is the exact idiom
    // `migrate` uses (re-reads the just-generated file). The specific
    // `CodelessIllFormed` guard above owns the cause-naming for today's only
    // known offender; this check makes the biconditional hold BY CONSTRUCTION for
    // ANY future `Outcome`/render path — it stays UNREACHABLE for the current
    // taxonomy (the round-trip test transitively pins it).
    parse_frontmatter(&spliced).map_err(GenError::UnparseableRender)?;
    Ok(spliced)
}

/// The canonical `expect:` block for a run outcome — `exit:` (the outcome code)
/// plus `stdout:` as a JSON-escaped string (a canonical, unambiguous, and thus
/// idempotent serialisation of arbitrary bytes, incl. newlines), plus a `trap:`
/// `T_` code line when (and only when) the outcome is a Trap, OR a `reject:`
/// `E_` code line when (and only when) the outcome is a may-move static
/// rejection. `gen` records the CODE, not the human message (pin 3).
fn render_expect_block(run: &Run) -> Vec<String> {
    let trap = match &run.outcome {
        Outcome::Trap(kind) => Some(kind.code()),
        _ => None,
    };
    // The reject code is the typed metadata already resolved on `Run` (only
    // present for a may-move gate `IllFormed`); keyed on the outcome KIND so an
    // eval-internal codeless `IllFormed` records no `reject:` line.
    let reject = match &run.outcome {
        Outcome::IllFormed(_) => run.reject_code,
        _ => None,
    };
    render_expect_block_from(run.outcome.exit_code(), &run.stdout, trap, reject)
}

/// The `expect:` block from a bare `(exit, stdout, trap)` triple — the same
/// serialisation `render_expect_block` uses, factored out so a future
/// serializer (D2) can produce a block WITHOUT reconstructing a `Run`, on the
/// SAME `json_escape` the frontmatter reader inverts. The round-trip
/// (`json_escape` ⇄ `parse_json_string`) is unit-tested (`src/tests.rs`).
/// `trap` is the `TrapKind::code()` on a Trap outcome, `None` otherwise; the
/// `#   trap:` line is emitted (at index 3) ONLY when it is `Some`, so a no-trap
/// block stays exactly `exit` (index 1) + `stdout` (index 2). `reject` is the
/// `MoveErrorKind::code()` on a may-move static-rejection `IllFormed`, `None`
/// otherwise; its `#   reject:` line is emitted ONLY when `Some`. `trap` and
/// `reject` are mutually exclusive (a Trap is exit 101, a rejection is exit 1).
pub fn render_expect_block_from(
    exit: i32,
    stdout: &str,
    trap: Option<&str>,
    reject: Option<&str>,
) -> Vec<String> {
    let mut block = vec![
        "# expect:".to_string(),
        format!("#   exit: {exit}"),
        format!("#   stdout: \"{}\"", json_escape(stdout)),
    ];
    if let Some(code) = trap {
        block.push(format!("#   trap: {code}"));
    }
    if let Some(code) = reject {
        block.push(format!("#   reject: {code}"));
    }
    block
}

/// Replace the `# expect:` sub-block (everything from the `# expect:` line up to
/// the closing fence) with `block`. If no `# expect:` line exists yet, `block`
/// is inserted just before the closing fence. `expect:` is required to be the
/// LAST key in the frontmatter (documented convention; keeps the splice a single
/// contiguous range and the round-trip byte-exact).
fn splice_expect(source: &str, block: &[String]) -> Result<String, GenError> {
    let lines: Vec<&str> = source.lines().collect();
    let open = lines.iter().position(|l| l.trim_end() == FENCE_OPEN);
    let close = lines.iter().position(|l| l.trim_end() == FENCE_CLOSE);
    let (open, close) = match (open, close) {
        (Some(o), Some(c)) if o < c => (o, c),
        _ => return Err(GenError::NoFrontmatter),
    };

    // The `# expect:` line inside the fence, if any.
    let expect_start = (open + 1..close).find(|&i| {
        let t = lines[i].trim_start();
        t.strip_prefix('#').map(str::trim_start).is_some_and(|k| k.starts_with("expect:"))
    });

    let mut out: Vec<String> = Vec::with_capacity(lines.len() + block.len());
    match expect_start {
        Some(es) => {
            // Keep [.. expect_start), drop [expect_start .. close), insert block,
            // keep [close ..].
            out.extend(lines[..es].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
        None => {
            // Insert the block just before the closing fence.
            out.extend(lines[..close].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
    }

    let mut joined = out.join("\n");
    joined.push('\n'); // fixtures end with exactly one trailing newline
    Ok(joined)
}

/// Escape a string for embedding in a JSON string literal (hand-rolled — no
/// deps, per the interpreter-discipline rule; mirrors `trace::escape_json`).
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

// ── `ggdef -- migrate` — populate `spectests/run/` from the AGREE set (D1) ─────
//
// The migration copies every ggdef-adjudicated AGREE fixture (`classify_fixture`
// == `Agree`) out of `tests/fixtures/` into `spectests/run/`, prepends a
// `#!spectest` frontmatter block (`mode: run`, `adjudicator: ggdef`), and fills
// the `expect:` block IN-PROCESS via `gen_frontmatter` — the expectation flows
// FROM the definition (RFC §4), never copied off a backend. Selection is EXACTLY
// the `Agree` bucket the `converter_agreement` gate asserts on (the SAME
// predicate), so the migrated set and the agreement floor can never diverge.

/// The outcome of a `migrate` run: the fixtures written, and a census of the
/// non-`Agree` verdicts (for the CLI report — they are NOT migrated).
#[derive(Debug, Default)]
pub struct MigrateReport {
    /// Fixture file names written into `spectests/run/`, sorted.
    pub migrated: Vec<String>,
    /// Count of each non-`Agree` verdict encountered in the walk.
    pub skipped: BTreeMap<&'static str, usize>,
}

/// A `migrate` failure. `NonzeroExit` is the tripwire the brief mandates: an
/// `Agree` fixture is a `run_gg` pair, so its ggdef outcome is a `Value` (exit
/// 0) by construction — a nonzero exit would silently activate a filed dormant
/// hazard in the C/LLVM lanes, so we STOP and report instead of writing it.
#[derive(Debug)]
pub enum MigrateError {
    Io(std::io::Error),
    Gen(String, GenError),
    Frontmatter(String, FrontmatterError),
    NonzeroExit { name: String, exit: i32 },
}

impl std::fmt::Display for MigrateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MigrateError::Io(e) => write!(f, "I/O error: {e}"),
            MigrateError::Gen(name, e) => write!(f, "gen `{name}`: {e}"),
            MigrateError::Frontmatter(name, e) => write!(f, "re-parse `{name}`: {e}"),
            MigrateError::NonzeroExit { name, exit } => write!(
                f,
                "`{name}` generated a NONZERO exit ({exit}) — an AGREE fixture must be exit-0 by \
                 construction. STOP: this would activate the filed dormant exit≠0 branch in the \
                 C/LLVM run lanes. Triage before migrating."
            ),
        }
    }
}

impl std::error::Error for MigrateError {}

/// Run the D1 migration. `ws_root` is the workspace root; the tool reads
/// `tests/fixtures/` + `tests/integration.rs` and writes `spectests/run/`.
/// Runs the whole walk in a 2 GiB-stack thread (ggdef's big-step eval recurses
/// on the native stack).
pub fn migrate(ws_root: &Path) -> Result<MigrateReport, MigrateError> {
    let ws = ws_root.to_path_buf();
    std::thread::Builder::new()
        .stack_size(2 * 1024 * 1024 * 1024)
        .name("ggdef-migrate".to_string())
        .spawn(move || migrate_body(&ws))
        .unwrap()
        .join()
        .unwrap()
}

fn migrate_body(ws_root: &Path) -> Result<MigrateReport, MigrateError> {
    let fixtures_dir = ws_root.join("tests/fixtures");
    let run_dir = ws_root.join("spectests/run");
    let integ =
        std::fs::read_to_string(ws_root.join("tests/integration.rs")).map_err(MigrateError::Io)?;

    let mut report = MigrateReport::default();
    for name in classify::classifiable_fixture_names(&fixtures_dir) {
        let src = std::fs::read_to_string(fixtures_dir.join(&name)).map_err(MigrateError::Io)?;
        match classify::classify_fixture(&name, &src, &integ) {
            Classification::Agree => {
                // Frame the body with a run-tier `#!spectest` block, then let
                // `gen_frontmatter` splice the `expect:` (kept LAST) from a
                // fresh definitional run.
                let framed = prepend_frontmatter(&src, &name);
                let generated = gen_frontmatter(&framed, DEFAULT_FUEL)
                    .map_err(|e| MigrateError::Gen(name.clone(), e))?;
                // Exit-0 tripwire (brief): re-read the just-written expectation.
                let fm = parse_frontmatter(&generated)
                    .map_err(|e| MigrateError::Frontmatter(name.clone(), e))?;
                if fm.expect.exit != 0 {
                    return Err(MigrateError::NonzeroExit { name, exit: fm.expect.exit });
                }
                std::fs::write(run_dir.join(&name), &generated).map_err(MigrateError::Io)?;
                report.migrated.push(name);
            }
            Classification::Float => *report.skipped.entry("float-hold").or_default() += 1,
            Classification::Other { .. } => *report.skipped.entry("other-mismatch").or_default() += 1,
            Classification::NotValue => *report.skipped.entry("not-value").or_default() += 1,
            Classification::NoPair => *report.skipped.entry("no-run_gg-pair").or_default() += 1,
            Classification::FrontendError => {
                *report.skipped.entry("frontend-error").or_default() += 1
            }
        }
    }
    Ok(report)
}

/// Frame a fixture body with a run-tier `#!spectest` frontmatter block. The
/// `expect:` line is intentionally ABSENT — `gen_frontmatter` inserts it just
/// before the closing fence (`splice_expect`), keeping it LAST per the fence
/// convention. `doc:` records the legacy-harness provenance (inline scalar).
fn prepend_frontmatter(src: &str, name: &str) -> String {
    let mut out = String::new();
    out.push_str(FENCE_OPEN);
    out.push('\n');
    out.push_str("# mode: run\n");
    out.push_str("# adjudicator: ggdef\n");
    out.push_str(&format!("# doc: migrated from tests/fixtures/{name} (run_gg pair)\n"));
    out.push_str(FENCE_CLOSE);
    out.push('\n');
    out.push_str(src);
    out
}

#[cfg(test)]
mod tests;
