//! `ggdef` — the definitional interpreter for Gorget Core (GGC).
//!
//! `ggdef` IS the meaning of Gorget's dynamic semantics (RFC §1): a small
//! eager-value-semantics interpreter whose behaviour defines what a program
//! means. Production stays borrows + lazy CoW — an optimisation with an
//! observational-equivalence obligation (D1). This crate shares the production
//! **lexer + parser + AST only**; the fence against `ir`/`semantic`/`lir`/
//! `bir`/`backend` is the import ratchet in `tests/lints.rs`.
//!
//! Increment A is the walking skeleton: the elaborator + evaluator for the
//! honest subset the first ~20 `cow_*` fixtures use (int/bool/float scalars,
//! `String`, `Vector`, structs, tuples; bare/`&`/`!` modes; materialize-on-
//! write). See `docs/plans/define-gorget/phase0-brief.md`.

pub mod elaborate;
pub mod eval;
pub mod ggc;
pub mod trace;

pub use elaborate::{elaborate, ElabError};
pub use eval::{run, Fault, Outcome, Run, EXIT_FUEL, EXIT_ILLFORMED, EXIT_TRAP, EXIT_VALUE};

use gorget::parser::Parser;

/// The default fuel bound for CLI runs — generous; every phase-0 fixture
/// terminates in far fewer steps. Non-termination surfaces as `FuelExhausted`.
pub const DEFAULT_FUEL: u64 = 50_000_000;

/// A frontend (parse + elaborate) failure, distinct from an evaluation
/// outcome. Parse errors reclassify a program to the `parse-error` tier;
/// elaboration errors are the stop-and-report signal (a construct outside the
/// A subset, or a shape the elaborator will not fake).
#[derive(Debug)]
pub enum FrontendError {
    Parse(Vec<String>),
    Elaborate(ElabError),
}

impl std::fmt::Display for FrontendError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FrontendError::Parse(errs) => {
                writeln!(f, "{} parse error(s):", errs.len())?;
                for e in errs {
                    writeln!(f, "  {e}")?;
                }
                Ok(())
            }
            FrontendError::Elaborate(e) => {
                write!(f, "elaboration error @ {}..{}: {}", e.span.start, e.span.end, e.message)
            }
        }
    }
}

/// Parse + elaborate a source string into a GGC program.
pub fn frontend(source: &str) -> Result<ggc::Program, FrontendError> {
    let mut parser = Parser::new(source);
    let module = parser.parse_module();
    if !parser.errors.is_empty() {
        return Err(FrontendError::Parse(parser.errors.iter().map(|e| e.to_string()).collect()));
    }
    elaborate(&module).map_err(FrontendError::Elaborate)
}

/// Parse, elaborate, and run a source string, bounded by `fuel`.
pub fn run_source(source: &str, fuel: u64) -> Result<Run, FrontendError> {
    Ok(run(&frontend(source)?, fuel))
}

// ── `ggdef -- gen` — expectation generation for `spectests/` fixtures ──────────
//
// A `spectests/` fixture is an ordinary `.gg` program carrying a frontmatter
// block in leading `#` comments (invisible to the lexer, so `run`/`trace` work
// unchanged). `gen` RUNS the program and writes the observed outcome back into
// the frontmatter's `expect:` block, in place. This is how conformance
// expectations "flow FROM the definition" (RFC §4) rather than being copied off
// whichever backend came first. It is idempotent: running it twice is a no-op,
// which is what the `gen_idempotent` gate asserts.
//
// Frontmatter shape (the fence markers are themselves comments):
//
//   #!spectest
//   # mode: run
//   # adjudicator: ggdef
//   # expect:                 <- this block is REGENERATED by `gen`; keep it last
//   #   exit: 0
//   #   stdout: "9\n"
//   #!end

/// The opening / closing fence lines of a spectest frontmatter block.
pub const FENCE_OPEN: &str = "#!spectest";
pub const FENCE_CLOSE: &str = "#!end";

/// A `gen` failure: either the program did not run cleanly (a `mode: run`
/// fixture whose body traps at the frontend is itself invalid), or the file has
/// no frontmatter fence to write into.
#[derive(Debug)]
pub enum GenError {
    Frontend(FrontendError),
    NoFrontmatter,
}

impl std::fmt::Display for GenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GenError::Frontend(e) => write!(f, "{e}"),
            GenError::NoFrontmatter => write!(
                f,
                "no `{FENCE_OPEN}` … `{FENCE_CLOSE}` frontmatter fence — cannot write `expect:`"
            ),
        }
    }
}

/// Run `source` and return it with the frontmatter `expect:` block regenerated
/// from the observed outcome. Pure (no I/O) so it is trivially testable; the CLI
/// wraps it with a read + write-back. Idempotent: `gen(gen(x)) == gen(x)`.
pub fn gen_frontmatter(source: &str, fuel: u64) -> Result<String, GenError> {
    let run = run_source(source, fuel).map_err(GenError::Frontend)?;
    let block = render_expect_block(&run);
    splice_expect(source, &block)
}

/// The canonical `expect:` block for a run outcome — `exit:` (the outcome code)
/// plus `stdout:` as a JSON-escaped string (a canonical, unambiguous, and thus
/// idempotent serialisation of arbitrary bytes, incl. newlines).
fn render_expect_block(run: &Run) -> Vec<String> {
    vec![
        "# expect:".to_string(),
        format!("#   exit: {}", run.outcome.exit_code()),
        format!("#   stdout: \"{}\"", json_escape(&run.stdout)),
    ]
}

/// Replace the `# expect:` sub-block (everything from the `# expect:` line up to
/// the closing fence) with `block`. If no `# expect:` line exists yet, `block`
/// is inserted just before the closing fence. `expect:` is required to be the
/// LAST key in the frontmatter (documented convention; keeps the splice a single
/// contiguous range and the round-trip byte-exact).
fn splice_expect(source: &str, block: &[String]) -> Result<String, GenError> {
    let lines: Vec<&str> = source.lines().collect();
    let open = lines.iter().position(|l| l.trim_end() == FENCE_OPEN);
    let close = lines.iter().position(|l| l.trim_end() == FENCE_CLOSE);
    let (open, close) = match (open, close) {
        (Some(o), Some(c)) if o < c => (o, c),
        _ => return Err(GenError::NoFrontmatter),
    };

    // The `# expect:` line inside the fence, if any.
    let expect_start = (open + 1..close).find(|&i| {
        let t = lines[i].trim_start();
        t.strip_prefix('#').map(str::trim_start).is_some_and(|k| k.starts_with("expect:"))
    });

    let mut out: Vec<String> = Vec::with_capacity(lines.len() + block.len());
    match expect_start {
        Some(es) => {
            // Keep [.. expect_start), drop [expect_start .. close), insert block,
            // keep [close ..].
            out.extend(lines[..es].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
        None => {
            // Insert the block just before the closing fence.
            out.extend(lines[..close].iter().map(|s| s.to_string()));
            out.extend(block.iter().cloned());
            out.extend(lines[close..].iter().map(|s| s.to_string()));
        }
    }

    let mut joined = out.join("\n");
    joined.push('\n'); // fixtures end with exactly one trailing newline
    Ok(joined)
}

/// Escape a string for embedding in a JSON string literal (hand-rolled — no
/// deps, per the interpreter-discipline rule; mirrors `trace::escape_json`).
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests;
