//! gorget-smith program generator — seeded, byte-reproducible from
//! `(GENERATOR_VERSION, seed)`.
//!
//! Rust port of the scout prototype `ggsmith.py`. Programs are well-typed and
//! in-bounds BY CONSTRUCTION: a symbol table (`Local`) tracks every live name
//! and its type, and vectors carry a statically tracked element count so every
//! generated index is provably in range. Output is deterministic at runtime
//! (prints of computed values only): no unbounded loops, no input, no
//! time/random.
//!
//! The PRNG is a PINNED in-file splitmix64 — NEVER swap it for rand::StdRng
//! (unstable across rand versions) or the platform RNG. Any change to the
//! PRNG, the grammar, or the weights is a new generator version: bump
//! [`GENERATOR_VERSION`] so old seed numbers are not misread as reproducible.
//!
//! ## Tier-0 grammar (this round)
//!
//! int / String / Vector[int] / Vector[String] locals; bare-assign aliases
//! (CoW borrow); view binds from collection reads (`w0[i]`); push / index-set
//! mutations after aliases/views; helper fns with bare/`&`/`!` params; moves
//! at consuming positions (`v.push(!s)`, `f(!s)`); `.clone()`; if/elif/else
//! including never-taken branches; for-over-vector; for-over-range; string
//! concat-reassign (alias sever).
//!
//! ## Deliberately EXCLUDED shapes
//!
//! Known filed divergences / both-compiler bugs stay un-generated so a smith
//! run measures NEW signal instead of rediscovering the backlog:
//!
//!   - move-binds `T w = !v`        — Rust EMove value-bug (devbook/11
//!     "oracle exception")
//!   - `for c in &v` loops          — both-compiler write-through hole
//!     (TODO round-34)
//!   - structs / equip `&self` named-receiver mutators — R37-T1 self-host
//!     named-receiver divergence
//!   - `select:` blocks             — self-host `SSelect` lowering is
//!     unimplemented, the whole block is silently dropped (TODO.md:127 item
//!     (c), TODO.md:169)
//!   - `shared(...)` facades        — self-host lowers the facade as a PLAIN
//!     value: no sync-handle alloc, no guard slot; affects every strategy
//!     (TODO.md:127 item (d))
//!   - `spawn` / async / Channel    — spawn-opaque-param keystone + Channel
//!     ctor/drop cluster (TODO.md:127 item (a), TODO.md:169)
//!   - method-generics              — deep multi-root cluster, partitioned
//!     but not fully landed (TODO.md:339 "method-generic cluster")
//!
//! ## Tier 1 — the throws-position REJECTION tier (T3b)
//!
//! [`TIER_THROWS`] is a DIFFERENT SHAPE than tier 0's differential: it emits a
//! program well-formed EXCEPT for ONE unhandled `throws` call placed in a
//! fuzzed expression POSITION (binop operand / call arg / plain bind / match
//! scrutinee / bare statement / match-arm tail), optionally nested in an
//! `if`/`elif`/`for` context. Production MUST reject it with
//! `E_MissingFallibleMark` (D29); the harness runs an INVERTED oracle (see `classify` in
//! `main.rs`) — a check-SUCCESS is a real T3a hole, not a PASS. This tier is
//! CHECK-ONLY (no ggdef / build / self-host / LLVM lane). The call is NEVER
//! placed inside a `throws` fn / `catch` / match-Ok/Error / `Result`-typed dest
//! (all LEGAL), so the ONLY defect is the single unhandled `throws`.
//!
//! Further differential-widening tiers (per devbook/11's mutation-route class
//! table; traits/equip) are future rounds; the tier flag is plumbed through
//! [`generate`].

/// Version of the generator grammar + PRNG + weights. Seed numbers are only
/// comparable within one version: `(GENERATOR_VERSION, seed)` is the
/// reproducibility key. Bump on ANY change that can alter generated bytes.
pub const GENERATOR_VERSION: u32 = 1;

/// The throws-position REJECTION tier (T3b). Distinct from tier 0's
/// differential shape: this tier emits a program that is well-formed EXCEPT for
/// ONE unhandled `throws` call placed in a fuzzed expression position, and the
/// harness asserts production REJECTS it with `E_MissingFallibleMark` (an INVERTED
/// oracle — see `classify` in `main.rs`). Single source of truth for the tier
/// number; `main.rs` refers to it as `generator::TIER_THROWS`.
pub const TIER_THROWS: u32 = 1;

const INT: Ty = Ty::Int;
const STR: Ty = Ty::Str;
const VINT: Ty = Ty::VInt;
const VSTR: Ty = Ty::VStr;

const WORDS: [&str; 20] = [
    "ash", "bay", "cod", "dew", "elm", "fog", "gem", "hay", "ice", "jet", "kit", "log", "mud",
    "nap", "oak", "pod", "rye", "sap", "tin", "urn",
];

/// Pinned splitmix64 PRNG. All draws go through integer arithmetic only, so
/// the stream is byte-identical on every platform and toolchain.
struct Rng {
    state: u64,
}

impl Rng {
    fn new(seed: u64) -> Self {
        // Fold GENERATOR_VERSION into the initial state so a version bump
        // decorrelates every seed's stream (old seed numbers stop "almost
        // working" and get regenerated instead of half-matching).
        let mut rng = Rng {
            state: seed ^ ((GENERATOR_VERSION as u64).wrapping_mul(0x9E3779B97F4A7C15)),
        };
        // Warm up: the first outputs of splitmix64 from small raw seeds are
        // well distributed already, but discard a couple anyway so seed=0 and
        // version-folding start from a mixed state.
        rng.next_u64();
        rng.next_u64();
        rng
    }

    /// splitmix64 step (Steele, Lea, Flood 2014). Pinned; do not replace.
    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }

    /// Uniform integer in `lo..=hi` (inclusive), mirroring Python's
    /// `randint`. Modulo bias is irrelevant at fuzzing ranges (< 2^6).
    fn randint(&mut self, lo: i64, hi: i64) -> i64 {
        debug_assert!(lo <= hi);
        let span = (hi - lo + 1) as u64;
        lo + (self.next_u64() % span) as i64
    }

    /// True with probability `num`/`den` (integer arithmetic — no floats in
    /// the stream). Mirrors the prototype's `random() < p` weight points.
    fn chance(&mut self, num: u64, den: u64) -> bool {
        self.next_u64() % den < num
    }

    fn choose<'a, T>(&mut self, xs: &'a [T]) -> &'a T {
        debug_assert!(!xs.is_empty());
        &xs[(self.next_u64() % xs.len() as u64) as usize]
    }
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
enum Ty {
    Int,
    Str,
    VInt,
    VStr,
}

impl Ty {
    fn decl(self) -> &'static str {
        match self {
            Ty::Int => "int",
            Ty::Str => "String",
            Ty::VInt => "Vector[int]",
            Ty::VStr => "Vector[String]",
        }
    }

    fn is_vec(self) -> bool {
        matches!(self, Ty::VInt | Ty::VStr)
    }
}

#[derive(Clone)]
struct Local {
    name: String,
    ty: Ty,
    /// Statically tracked element count for vectors (`None` for scalars).
    /// Only bumped at depth 0 (top level of main): inside a conditional block
    /// the static count is unreliable, and since pushes only grow, existing
    /// indices stay in bounds without the bump.
    length: Option<i64>,
}

#[derive(Copy, Clone, PartialEq, Eq)]
enum Mode {
    Bare,
    Amp,
    Bang,
}

struct HelperParam {
    ty: Ty,
    mode: Mode,
    /// Net pushes the helper body applies through an `&` param — the caller
    /// bumps its tracked length by this after a successful call.
    push_delta: i64,
}

struct Helper {
    name: String,
    params: Vec<HelperParam>,
    ret: Option<Ty>, // None (void) | Some(Int) | Some(Str)
    lines: Vec<String>,
}

struct Gen {
    rng: Rng,
    counter: u64,
    helpers: Vec<Helper>,
}

impl Gen {
    fn new(seed: u64) -> Self {
        Gen { rng: Rng::new(seed), counter: 0, helpers: Vec::new() }
    }

    fn fresh(&mut self, prefix: &str) -> String {
        self.counter += 1;
        format!("{prefix}{}", self.counter)
    }

    fn word(&mut self) -> &'static str {
        *self.rng.choose(&WORDS)
    }

    fn ilit(&mut self) -> String {
        self.rng.randint(-9, 9).to_string()
    }

    // ---------- expressions ----------

    fn int_atom(&mut self, env: &[Local]) -> String {
        let ints: Vec<&Local> = env.iter().filter(|l| l.ty == INT).collect();
        let vecs: Vec<&Local> = env.iter().filter(|l| l.ty.is_vec()).collect();
        let vints: Vec<&Local> = env
            .iter()
            .filter(|l| l.ty == VINT && l.length.is_some_and(|n| n > 0))
            .collect();
        let mut opts: Vec<&str> = vec!["lit"];
        if !ints.is_empty() {
            opts.extend(["name", "name"]);
        }
        if !vecs.is_empty() {
            opts.push("len");
        }
        if !vints.is_empty() {
            opts.push("idx");
        }
        match *self.rng.choose(&opts) {
            "name" => self.rng.choose(&ints).name.clone(),
            "len" => format!("{}.len()", self.rng.choose(&vecs).name),
            "idx" => {
                let v = *self.rng.choose(&vints);
                let i = self.rng.randint(0, v.length.unwrap() - 1);
                format!("{}[{i}]", v.name)
            }
            _ => self.ilit(),
        }
    }

    fn int_expr(&mut self, env: &[Local]) -> String {
        if self.rng.chance(45, 100) {
            return self.int_atom(env);
        }
        let op = *self.rng.choose(&["+", "-", "*"]);
        let a = self.int_atom(env);
        let b = if op == "*" { self.rng.randint(-3, 3).to_string() } else { self.int_atom(env) };
        format!("{a} {op} {b}")
    }

    fn str_expr(&mut self, env: &[Local]) -> String {
        let strs: Vec<&Local> = env.iter().filter(|l| l.ty == STR).collect();
        let vstrs: Vec<&Local> = env
            .iter()
            .filter(|l| l.ty == VSTR && l.length.is_some_and(|n| n > 0))
            .collect();
        let mut opts: Vec<&str> = vec!["lit"];
        if !strs.is_empty() {
            opts.extend(["alias", "clone", "concat"]);
        }
        if !vstrs.is_empty() {
            // view binds are the CoW-sensitive shape — double weight
            opts.extend(["view", "view"]);
        }
        match *self.rng.choose(&opts) {
            "alias" => self.rng.choose(&strs).name.clone(),
            "clone" => format!("{}.clone()", self.rng.choose(&strs).name),
            "concat" => {
                let name = self.rng.choose(&strs).name.clone();
                let w = self.word();
                format!("{name} + \"{w}\"")
            }
            "view" => {
                let v = *self.rng.choose(&vstrs);
                let i = self.rng.randint(0, v.length.unwrap() - 1);
                format!("{}[{i}]", v.name)
            }
            _ => format!("\"{}\"", self.word()),
        }
    }

    fn cond(&mut self, env: &[Local]) -> String {
        let mut parts: Vec<String> = Vec::new();
        let n = self.rng.randint(1, 2);
        for _ in 0..n {
            let ints: Vec<&Local> = env.iter().filter(|l| l.ty == INT).collect();
            let vecs: Vec<&Local> = env.iter().filter(|l| l.ty.is_vec()).collect();
            if self.rng.chance(50, 100) && !ints.is_empty() {
                let name = self.rng.choose(&ints).name.clone();
                let op = *self.rng.choose(&["<", ">", "==", "!=", "<=", ">="]);
                let lit = self.ilit();
                parts.push(format!("{name} {op} {lit}"));
            } else if !vecs.is_empty() {
                let name = self.rng.choose(&vecs).name.clone();
                let op = *self.rng.choose(&["<", ">", "=="]);
                let k = self.rng.randint(0, 6);
                parts.push(format!("{name}.len() {op} {k}"));
            } else {
                let a = self.ilit();
                let b = self.rng.randint(0, 9);
                parts.push(format!("{a} < {b}"));
            }
        }
        let joiner = *self.rng.choose(&["and", "or"]);
        parts.join(&format!(" {joiner} "))
    }

    // ---------- helpers ----------

    fn gen_helper(&mut self, idx: usize) -> Helper {
        let nparams = self.rng.randint(1, 3);
        let mut params: Vec<HelperParam> = Vec::new();
        for _ in 0..nparams {
            let ty = *self.rng.choose(&[INT, STR, VINT, VSTR]);
            let mode = if ty.is_vec() {
                *self.rng.choose(&[Mode::Bare, Mode::Bare, Mode::Amp, Mode::Bang])
            } else if ty == STR {
                *self.rng.choose(&[Mode::Bare, Mode::Bare, Mode::Bang])
            } else {
                Mode::Bare
            };
            params.push(HelperParam { ty, mode, push_delta: 0 });
        }
        let ret = *self.rng.choose(&[None, None, Some(INT), Some(STR)]);
        let mut body: Vec<String> = Vec::new();
        for i in 0..params.len() {
            let pn = format!("p{i}");
            let roll = self.rng.next_u64() % 100;
            let (pty, pmode) = (params[i].ty, params[i].mode);
            if pty.is_vec() {
                if roll < 45 {
                    let lit =
                        if pty == VINT { self.ilit() } else { format!("\"{}\"", self.word()) };
                    body.push(format!("    {pn}.push({lit})"));
                    if pmode == Mode::Amp {
                        params[i].push_delta += 1;
                    }
                } else if roll < 75 {
                    body.push(format!("    print({pn}.len())"));
                } else {
                    body.push(format!("    print({pn}[0])"));
                }
            } else if pty == STR {
                if roll < 50 {
                    body.push(format!("    print({pn})"));
                } else {
                    body.push(format!("    print({pn}.len())"));
                }
            } else {
                let lit = self.ilit();
                body.push(format!("    print({pn} + {lit})"));
            }
        }
        match ret {
            Some(t) if t == INT => {
                let atoms: Vec<String> = params
                    .iter()
                    .enumerate()
                    .map(|(i, p)| if p.ty == INT { format!("p{i}") } else { format!("p{i}.len()") })
                    .collect();
                let atom = self.rng.choose(&atoms).clone();
                let lit = self.ilit();
                body.push(format!("    return {atom} + {lit}"));
            }
            Some(_) => {
                let strs: Vec<String> = params
                    .iter()
                    .enumerate()
                    .filter(|(_, p)| p.ty == STR)
                    .map(|(i, _)| format!("p{i}"))
                    .collect();
                let src = if strs.is_empty() {
                    format!("\"{}\"", self.word())
                } else {
                    self.rng.choose(&strs).clone()
                };
                let w = self.word();
                body.push(format!("    return {src} + \"{w}\""));
            }
            None => {}
        }
        let sig = params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                let sigil = match p.mode {
                    Mode::Amp => "&",
                    Mode::Bang => "!",
                    Mode::Bare => "",
                };
                format!("{} {sigil}p{i}", p.ty.decl())
            })
            .collect::<Vec<_>>()
            .join(", ");
        let rets = match ret {
            None => "void",
            Some(t) => t.decl(),
        };
        let name = format!("fn{idx}");
        let mut lines = vec![format!("{rets} {name}({sig}):")];
        lines.extend(body);
        Helper { name, params, ret, lines }
    }

    // ---------- statements ----------

    fn stmt(&mut self, env: &mut Vec<Local>, out: &mut Vec<String>, indent: usize, depth: usize) {
        let pad = "    ".repeat(indent);
        let mut menu: Vec<&str> = vec![
            "decl_int", "decl_str", "decl_vec", "print", "push", "compound", "str_grow",
            "idx_set", "call",
        ];
        if depth < 2 {
            menu.extend(["if", "for_vec", "for_range"]);
        }
        match *self.rng.choose(&menu) {
            "decl_int" => {
                let n = self.fresh("i");
                let e = self.int_expr(env);
                out.push(format!("{pad}int {n} = {e}"));
                env.push(Local { name: n, ty: INT, length: None });
            }
            "decl_str" => {
                let n = self.fresh("s");
                let e = self.str_expr(env);
                out.push(format!("{pad}String {n} = {e}"));
                env.push(Local { name: n, ty: STR, length: None });
            }
            "decl_vec" => {
                let ty = *self.rng.choose(&[VINT, VSTR]);
                let n = self.fresh(if ty == VINT { "v" } else { "w" });
                let sames: Vec<usize> = env
                    .iter()
                    .enumerate()
                    .filter(|(_, l)| l.ty == ty)
                    .map(|(i, _)| i)
                    .collect();
                let roll = self.rng.next_u64() % 100;
                if !sames.is_empty() && roll < 30 {
                    // bare-assign alias (CoW borrow)
                    let src = env[*self.rng.choose(&sames)].clone();
                    out.push(format!("{pad}{} {n} = {}", ty.decl(), src.name));
                    env.push(Local { name: n, ty, length: src.length });
                } else if !sames.is_empty() && roll < 45 {
                    let src = env[*self.rng.choose(&sames)].clone();
                    out.push(format!("{pad}{} {n} = {}.clone()", ty.decl(), src.name));
                    env.push(Local { name: n, ty, length: src.length });
                } else {
                    let cnt = self.rng.randint(1, 4);
                    let elems = (0..cnt)
                        .map(|_| {
                            if ty == VINT {
                                self.ilit()
                            } else {
                                format!("\"{}\"", self.word())
                            }
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    out.push(format!("{pad}{} {n} = [{elems}]", ty.decl()));
                    env.push(Local { name: n, ty, length: Some(cnt) });
                }
            }
            "print" => {
                let choice = self.rng.next_u64() % 100;
                let strs: Vec<&Local> = env.iter().filter(|l| l.ty == STR).collect();
                let vecs: Vec<&Local> = env
                    .iter()
                    .filter(|l| l.ty.is_vec() && l.length.is_some_and(|n| n > 0))
                    .collect();
                if choice < 40 || (strs.is_empty() && vecs.is_empty()) {
                    let e = self.int_expr(env);
                    out.push(format!("{pad}print({e})"));
                } else if choice < 70 && !strs.is_empty() {
                    let name = self.rng.choose(&strs).name.clone();
                    out.push(format!("{pad}print({name})"));
                } else if !vecs.is_empty() {
                    let v = *self.rng.choose(&vecs);
                    let i = self.rng.randint(0, v.length.unwrap() - 1);
                    out.push(format!("{pad}print({}[{i}])", v.name));
                } else {
                    let e = self.int_expr(env);
                    out.push(format!("{pad}print({e})"));
                }
            }
            "push" => {
                let vecs: Vec<usize> = env
                    .iter()
                    .enumerate()
                    .filter(|(_, l)| l.ty.is_vec())
                    .map(|(i, _)| i)
                    .collect();
                if vecs.is_empty() {
                    return;
                }
                let vi = *self.rng.choose(&vecs);
                let vname = env[vi].name.clone();
                if env[vi].ty == VINT {
                    let atom = self.int_atom(env);
                    out.push(format!("{pad}{vname}.push({atom})"));
                } else {
                    let strs: Vec<usize> = env
                        .iter()
                        .enumerate()
                        .filter(|(_, l)| l.ty == STR)
                        .map(|(i, _)| i)
                        .collect();
                    let roll = self.rng.next_u64() % 100;
                    if !strs.is_empty() && roll < 25 && indent == 1 {
                        // move at a consuming position — the source dies.
                        // NB: env.remove may invalidate vi (si < vi shifts
                        // it), so the length bump below re-finds by name.
                        let si = *self.rng.choose(&strs);
                        let sname = env[si].name.clone();
                        out.push(format!("{pad}{vname}.push(!{sname})"));
                        env.remove(si);
                    } else if !strs.is_empty() && roll < 60 {
                        let name = env[*self.rng.choose(&strs)].name.clone();
                        out.push(format!("{pad}{vname}.push({name})"));
                    } else {
                        let w = self.word();
                        out.push(format!("{pad}{vname}.push(\"{w}\")"));
                    }
                }
                // Inside a conditional block the static length is unreliable →
                // freeze indexing guarantees by NOT bumping. Pushes only grow,
                // so existing indices stay in bounds either way.
                if depth == 0 {
                    if let Some(v) = env.iter_mut().find(|l| l.name == vname) {
                        if let Some(len) = v.length.as_mut() {
                            *len += 1;
                        }
                    }
                }
            }
            "compound" => {
                let ints: Vec<&Local> = env.iter().filter(|l| l.ty == INT).collect();
                if ints.is_empty() {
                    return;
                }
                let n = self.rng.choose(&ints).name.clone();
                let op = *self.rng.choose(&["+=", "-=", "*="]);
                let k = self.rng.randint(-3, 3);
                out.push(format!("{pad}{n} {op} {k}"));
            }
            "str_grow" => {
                let strs: Vec<&Local> = env.iter().filter(|l| l.ty == STR).collect();
                if strs.is_empty() {
                    return;
                }
                let s = self.rng.choose(&strs).name.clone();
                let w = self.word();
                out.push(format!("{pad}{s} = {s} + \"{w}\""));
            }
            "idx_set" => {
                let vecs: Vec<&Local> = env
                    .iter()
                    .filter(|l| l.ty.is_vec() && l.length.is_some_and(|n| n > 0))
                    .collect();
                if vecs.is_empty() {
                    return;
                }
                let v = *self.rng.choose(&vecs);
                let vname = v.name.clone();
                let vty = v.ty;
                let i = self.rng.randint(0, v.length.unwrap() - 1);
                if vty == VINT {
                    let atom = self.int_atom(env);
                    out.push(format!("{pad}{vname}[{i}] = {atom}"));
                } else {
                    let w = self.word();
                    out.push(format!("{pad}{vname}[{i}] = \"{w}\""));
                }
            }
            "call" => {
                if self.helpers.is_empty() {
                    return;
                }
                let hi = (self.rng.next_u64() % self.helpers.len() as u64) as usize;
                // Two-phase arg construction (deliberate divergence from the
                // Python prototype, which mutated tracked lengths / removed
                // moved locals WHILE building args and could abort mid-way on
                // a later unsatisfiable param, leaving a phantom `&`-param
                // length bump with no call emitted — a latent in-bounds-
                // invariant hole). Here: collect args + deferred env effects
                // first; apply effects only when the whole call emits.
                enum Effect {
                    BumpLen { idx: usize, delta: i64 },
                    Remove { idx: usize },
                }
                let mut args: Vec<String> = Vec::new();
                let mut effects: Vec<Effect> = Vec::new();
                let mut used: Vec<String> = Vec::new();
                let nparams = self.helpers[hi].params.len();
                for pi in 0..nparams {
                    let (pty, pmode, pdelta) = {
                        let p = &self.helpers[hi].params[pi];
                        (p.ty, p.mode, p.push_delta)
                    };
                    let cands: Vec<usize> = env
                        .iter()
                        .enumerate()
                        .filter(|(_, l)| {
                            l.ty == pty
                                && !used.contains(&l.name)
                                && (!pty.is_vec() || l.length.is_some_and(|n| n > 0))
                        })
                        .map(|(i, _)| i)
                        .collect();
                    match pmode {
                        Mode::Bare => {
                            if pty == INT {
                                if !cands.is_empty() && self.rng.chance(60, 100) {
                                    args.push(env[*self.rng.choose(&cands)].name.clone());
                                } else {
                                    args.push(self.ilit());
                                }
                            } else if pty == STR {
                                if cands.is_empty() {
                                    args.push(format!("\"{}\"", self.word()));
                                } else {
                                    args.push(env[*self.rng.choose(&cands)].name.clone());
                                }
                            } else {
                                if cands.is_empty() {
                                    return; // no in-bounds vector to pass — abort stmt
                                }
                                let ci = *self.rng.choose(&cands);
                                args.push(env[ci].name.clone());
                                used.push(env[ci].name.clone());
                            }
                        }
                        Mode::Amp => {
                            if cands.is_empty() {
                                return;
                            }
                            let ci = *self.rng.choose(&cands);
                            args.push(format!("&{}", env[ci].name));
                            used.push(env[ci].name.clone());
                            if env[ci].length.is_some() && depth == 0 {
                                effects.push(Effect::BumpLen { idx: ci, delta: pdelta });
                            }
                        }
                        Mode::Bang => {
                            // move; only top-level so liveness stays simple
                            if cands.is_empty() || indent != 1 {
                                return;
                            }
                            let ci = *self.rng.choose(&cands);
                            args.push(format!("!{}", env[ci].name));
                            used.push(env[ci].name.clone());
                            effects.push(Effect::Remove { idx: ci });
                        }
                    }
                }
                // Whole call satisfiable — emit it and apply deferred effects.
                // Apply removals last, in descending index order, so earlier
                // BumpLen indices stay valid.
                let call =
                    format!("{}({})", self.helpers[hi].name, args.join(", "));
                match self.helpers[hi].ret {
                    None => out.push(format!("{pad}{call}")),
                    Some(rty) => {
                        let n = self.fresh("r");
                        out.push(format!("{pad}{} {n} = {call}", rty.decl()));
                        env.push(Local { name: n, ty: rty, length: None });
                    }
                }
                let mut removals: Vec<usize> = Vec::new();
                for e in &effects {
                    match e {
                        Effect::BumpLen { idx, delta } => {
                            if let Some(len) = env[*idx].length.as_mut() {
                                *len += delta;
                            }
                        }
                        Effect::Remove { idx } => removals.push(*idx),
                    }
                }
                removals.sort_unstable_by(|a, b| b.cmp(a));
                for idx in removals {
                    env.remove(idx);
                }
            }
            "if" => {
                let c = self.cond(env);
                out.push(format!("{pad}if {c}:"));
                // decls inside don't escape; length mutations are guarded by
                // depth > 0 inside, so a plain clone matches the prototype's
                // shallow-copy semantics observationally.
                let mut inner = env.clone();
                let n = self.rng.randint(1, 3);
                self.block(&mut inner, out, indent + 1, depth + 1, n);
                if self.rng.chance(40, 100) {
                    let c = self.cond(env);
                    out.push(format!("{pad}elif {c}:"));
                    let mut inner = env.clone();
                    let n = self.rng.randint(1, 2);
                    self.block(&mut inner, out, indent + 1, depth + 1, n);
                }
                if self.rng.chance(60, 100) {
                    out.push(format!("{pad}else:"));
                    let mut inner = env.clone();
                    let n = self.rng.randint(1, 2);
                    self.block(&mut inner, out, indent + 1, depth + 1, n);
                }
            }
            "for_vec" => {
                let vecs: Vec<&Local> = env
                    .iter()
                    .filter(|l| l.ty.is_vec() && l.length.is_some_and(|n| n > 0))
                    .collect();
                if vecs.is_empty() {
                    return;
                }
                let v = *self.rng.choose(&vecs);
                let vname = v.name.clone();
                let vty = v.ty;
                let x = self.fresh("e");
                out.push(format!("{pad}for {x} in {vname}:"));
                if vty == VINT {
                    let ints: Vec<&Local> = env.iter().filter(|l| l.ty == INT).collect();
                    if !ints.is_empty() && self.rng.chance(60, 100) {
                        let name = self.rng.choose(&ints).name.clone();
                        out.push(format!("{pad}    {name} += {x}"));
                    } else {
                        out.push(format!("{pad}    print({x})"));
                    }
                } else {
                    out.push(format!("{pad}    print({x})"));
                }
            }
            "for_range" => {
                let i = self.fresh("k");
                let hi = self.rng.randint(2, 4);
                out.push(format!("{pad}for {i} in 0..{hi}:"));
                let ints: Vec<&Local> = env.iter().filter(|l| l.ty == INT).collect();
                if !ints.is_empty() && self.rng.chance(50, 100) {
                    let name = self.rng.choose(&ints).name.clone();
                    out.push(format!("{pad}    {name} += {i}"));
                } else {
                    out.push(format!("{pad}    print({i} * 2)"));
                }
            }
            _ => unreachable!("menu entries are exhaustive"),
        }
    }

    fn block(
        &mut self,
        env: &mut Vec<Local>,
        out: &mut Vec<String>,
        indent: usize,
        depth: usize,
        n: i64,
    ) {
        let start = out.len();
        for _ in 0..n {
            self.stmt(env, out, indent, depth);
        }
        if out.len() == start {
            // never emit an empty block
            out.push(format!("{}print(0)", "    ".repeat(indent)));
        }
    }

    // ---------- tier 1: throws-position rejection tier (T3b) ----------

    /// Emit ONE unhandled-`throws` call in a fuzzed expression POSITION at the
    /// given `ind` indent level. The surrounding lines are well-formed by
    /// construction; the ONLY defect is the single unhandled `risky()` call, so
    /// production MUST reject with `E_MissingFallibleMark` (D29 bare-call code).
    /// The call is deliberately
    /// NEVER inside a `throws` fn / `catch` / match-Ok/Error / `Result`-typed
    /// destination — every one of those is LEGAL and would flip the verdict.
    fn emit_throws_position(
        &mut self,
        env: &[Local],
        ind: usize,
        position: i64,
        out: &mut Vec<String>,
    ) {
        let pad = "    ".repeat(ind);
        match position {
            0 => {
                // binop operand (either side) — pre-D23 this LEAKED `Result[`.
                let op = *self.rng.choose(&["+", "-", "*"]);
                let atom = self.int_atom(env);
                let x = self.fresh("x");
                let expr = if self.rng.chance(50, 100) {
                    format!("{atom} {op} risky()")
                } else {
                    format!("risky() {op} {atom}")
                };
                out.push(format!("{pad}int {x} = {expr}"));
                out.push(format!("{pad}print({x})"));
            }
            1 => {
                // call argument into a plain-`int` parameter.
                let n = self.fresh("n");
                out.push(format!("{pad}int {n} = id(risky())"));
                out.push(format!("{pad}print({n})"));
            }
            2 => {
                // plain bind to a plain `int` (not `Result[int, String]`).
                let x = self.fresh("x");
                out.push(format!("{pad}int {x} = risky()"));
                out.push(format!("{pad}print({x})"));
            }
            3 => {
                // match scrutinee with non-Result arms (bare match statement) —
                // pre-D23 this SILENTLY SWALLOWED the error.
                out.push(format!("{pad}match risky():"));
                out.push(format!("{pad}    case 0:"));
                out.push(format!("{pad}        print(\"zero\")"));
                out.push(format!("{pad}    else:"));
                out.push(format!("{pad}        print(\"other\")"));
            }
            4 => {
                // bare statement (discarded) — pre-D23 this SILENTLY SWALLOWED.
                out.push(format!("{pad}risky()"));
                out.push(format!("{pad}print(\"done\")"));
            }
            _ => {
                // match-arm TAIL value (match-as-expression).
                let n = self.fresh("n");
                let scrut = self.int_atom(env);
                out.push(format!("{pad}int {n} = match {scrut}:"));
                out.push(format!("{pad}    case 0:"));
                out.push(format!("{pad}        0"));
                out.push(format!("{pad}    else:"));
                out.push(format!("{pad}        risky()"));
                out.push(format!("{pad}print({n})"));
            }
        }
    }

    /// Tier-1 program: a well-formed skeleton with a free-fn `throws` helper and
    /// ONE unhandled call to it in a fuzzed position × context. Everything else
    /// compiles — the single unhandled `throws` is the only reason production
    /// rejects. (The `equip`-method receiver form is intentionally omitted: it
    /// needs a struct + in-scope instance + `equip` block to be well-formed, and
    /// the scout found a bare `int risky(self) …` WITHOUT `equip` is ACCEPTED —
    /// exactly the false-positive that would mis-fire the inverted oracle. T3a's
    /// `d23_unhandled_method*` fixtures already cover the method-reject; the
    /// free-fn core is kept solid instead.)
    fn program_throws_positions(&mut self, seed: u64) -> String {
        let mut out: Vec<String> = vec![format!(
            "# gorget-smith v{GENERATOR_VERSION} seed={seed} tier={TIER_THROWS} (throws-position)"
        )];

        // the throws helper (free-fn form): well-formed, always throws.
        out.push("int risky() throws String:".to_string());
        out.push("    throw \"boom\"".to_string());
        out.push(String::new());
        // a non-throws int->int helper for the call-argument position (unused in
        // other positions — an unused private fn is not an error, verified).
        out.push("int id(int x):".to_string());
        out.push("    return x".to_string());
        out.push(String::new());

        out.push("void main():".to_string());

        // anchor locals: material for int_atom / int_expr / cond, and a
        // well-typed surrounding for every position. `main` is `void` (never
        // `throws`), so the placed call is always in a non-`throws` scope.
        let env: Vec<Local> = vec![
            Local { name: "i0".into(), ty: INT, length: None },
            Local { name: "s0".into(), ty: STR, length: None },
            Local { name: "v0".into(), ty: VINT, length: Some(3) },
        ];
        out.push("    int i0 = 5".to_string());
        out.push("    String s0 = \"start\"".to_string());
        out.push("    Vector[int] v0 = [1, 2, 3]".to_string());

        // safe filler (well-formed by construction) to bury the position among
        // ordinary statements — combinatorial realism at zero false-positive
        // risk (int_expr uses only in-scope atoms + integer arithmetic).
        let pre = self.rng.randint(0, 2);
        for _ in 0..pre {
            let e = self.int_expr(&env);
            out.push(format!("    print({e})"));
        }

        let position = self.rng.randint(0, 5);
        match self.rng.randint(0, 3) {
            0 => {
                // top level of `main`.
                self.emit_throws_position(&env, 1, position, &mut out);
            }
            1 => {
                // nested in an `if` body.
                let c = self.cond(&env);
                out.push(format!("    if {c}:"));
                self.emit_throws_position(&env, 2, position, &mut out);
            }
            2 => {
                // nested in an `elif` body (an `if` with a filler then-body).
                let c1 = self.cond(&env);
                out.push(format!("    if {c1}:"));
                out.push("        print(0)".to_string());
                let c2 = self.cond(&env);
                out.push(format!("    elif {c2}:"));
                self.emit_throws_position(&env, 2, position, &mut out);
            }
            _ => {
                // nested in a `for` range-loop body.
                let k = self.fresh("k");
                out.push(format!("    for {k} in 0..3:"));
                self.emit_throws_position(&env, 2, position, &mut out);
            }
        }

        let post = self.rng.randint(0, 2);
        for _ in 0..post {
            let e = self.int_expr(&env);
            out.push(format!("    print({e})"));
        }

        out.push("    print(\"end\")".to_string());
        out.join("\n") + "\n"
    }

    fn program(&mut self, seed: u64) -> String {
        let nhelpers = self.rng.randint(0, 3);
        for i in 0..nhelpers {
            let h = self.gen_helper(i as usize);
            self.helpers.push(h);
        }
        let mut out: Vec<String> = vec![format!(
            "# gorget-smith v{GENERATOR_VERSION} seed={seed} tier=0"
        )];
        for i in 0..self.helpers.len() {
            out.extend(self.helpers[i].lines.iter().cloned());
            out.push(String::new());
        }
        out.push("void main():".to_string());
        let mut env: Vec<Local> = Vec::new();
        // guaranteed anchors so every menu arm has material
        env.push(Local { name: "v0".into(), ty: VINT, length: Some(3) });
        out.push("    Vector[int] v0 = [1, 2, 3]".to_string());
        env.push(Local { name: "w0".into(), ty: VSTR, length: Some(2) });
        out.push("    Vector[String] w0 = [\"red\", \"blue\"]".to_string());
        env.push(Local { name: "i0".into(), ty: INT, length: None });
        out.push("    int i0 = 5".to_string());
        env.push(Local { name: "s0".into(), ty: STR, length: None });
        out.push("    String s0 = \"start\"".to_string());
        let n = self.rng.randint(12, 26);
        self.block(&mut env, &mut out, 1, 0, n);
        out.push("    print(\"end\")".to_string());
        out.join("\n") + "\n"
    }
}

/// Generate the tier-`tier` program for `seed`. Byte-reproducible from
/// `(GENERATOR_VERSION, seed)`. Tier 0 is the differential CoW-core grammar;
/// [`TIER_THROWS`] is the throws-position rejection tier (T3b). The tier knob is
/// plumbed so future rounds can widen the grammar without changing call sites.
pub fn generate(seed: u64, tier: u32) -> String {
    match tier {
        0 => Gen::new(seed).program(seed),
        TIER_THROWS => Gen::new(seed).program_throws_positions(seed),
        _ => panic!(
            "gorget-smith: tier-{tier} grammar is not implemented \
             (tier 0 = differential CoW core; tier {TIER_THROWS} = throws-position \
             rejection tier; see the tier roadmap in tests/smith/main.rs)"
        ),
    }
}
