#!/usr/bin/env bash
# gg_impl.sh — GG_IMPL build-time compiler selector
#
# Usage:
#   GG_IMPL=rust      ./scripts/gg_impl.sh [install-dir]
#   GG_IMPL=selfhost  ./scripts/gg_impl.sh [install-dir]
#
# Produces a single `gg` binary in <install-dir> (default: ./bin) that IS the
# chosen implementation.
#
# GG_IMPL=rust:
#   1. cargo build --release
#   2. install target/release/gg as $INSTALL_DIR/gg
#
# GG_IMPL=selfhost:
#   1. cargo build --release        (seed: always needed to compile driver.gg)
#   2. seed `gg build driver.gg`    → gg-selfhost binary (seed owns cc+link)
#   3. install a thin `gg` wrapper → gg-selfhost (sets GG_RUNTIME_DIR/GG_LIB_DIR)
#
# The installed `gg` supports:
#   gg build <input.gg> [-o <output>] [--runtime-dir=<dir>] [--lib-dir=<dir>]
#   gg run   <input.gg>               [--runtime-dir=<dir>] [--lib-dir=<dir>]
#   (selfhost mode only; Rust gg has the full CLI surface)
#
# Environment variables honoured:
#   GG_IMPL          rust | selfhost  (required)
#   CC               C compiler (default: cc)
#   CARGO            cargo binary    (default: cargo)
#   GG_RUNTIME_DIR   set in wrapper to point at the C runtime (selfhost)
#   GG_LIB_DIR       set in wrapper to point at lib/std    (selfhost)
#
# The selfhost install also creates a thin wrapper script `gg` that pre-sets
# GG_RUNTIME_DIR and GG_LIB_DIR to the repo paths so the driver can locate
# the C runtime and stdlib without needing explicit --runtime-dir / --lib-dir
# flags on every invocation.

set -euo pipefail

# ── Resolve project root (directory containing this script's Cargo.toml) ────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Parse arguments ───────────────────────────────────────────────────────────
INSTALL_DIR="${1:-$REPO_ROOT/bin}"
GG_IMPL="${GG_IMPL:-rust}"
CARGO="${CARGO:-cargo}"
CC_BIN="${CC:-cc}"

echo "[gg_impl] GG_IMPL=$GG_IMPL  INSTALL_DIR=$INSTALL_DIR"

mkdir -p "$INSTALL_DIR"

# ── Stage 1: build the Rust gg (seed) ────────────────────────────────────────
echo "[gg_impl] Building Rust gg (cargo build --release)..."
cd "$REPO_ROOT"
"$CARGO" build --release 2>&1
SEED="$REPO_ROOT/target/release/gg"
if [[ ! -x "$SEED" ]]; then
    echo "[gg_impl] ERROR: cargo build did not produce $SEED" >&2
    exit 1
fi
echo "[gg_impl] Seed built: $SEED"

# ── GG_IMPL=rust: done ────────────────────────────────────────────────────────
if [[ "$GG_IMPL" == "rust" ]]; then
    cp "$SEED" "$INSTALL_DIR/gg"
    echo "[gg_impl] Installed Rust gg as $INSTALL_DIR/gg"
    echo "[gg_impl] Done (GG_IMPL=rust)."
    exit 0
fi

# ── GG_IMPL=selfhost ─────────────────────────────────────────────────────────
if [[ "$GG_IMPL" != "selfhost" ]]; then
    echo "[gg_impl] ERROR: unknown GG_IMPL=$GG_IMPL (must be rust or selfhost)" >&2
    exit 1
fi

DRIVER_SRC="$REPO_ROOT/tests/fixtures/self_host_lowerer/driver.gg"
RUNTIME_DIR="$REPO_ROOT/src/backend/c/runtime"
LIB_DIR="$REPO_ROOT/lib"
SELFHOST_BIN="$INSTALL_DIR/gg-selfhost"

if [[ ! -f "$DRIVER_SRC" ]]; then
    echo "[gg_impl] ERROR: driver.gg not found at $DRIVER_SRC" >&2
    exit 1
fi

# Stage 2: seed compiles driver.gg → gg-selfhost binary.
#
# The seed (Rust gg) `build` subcommand owns the full source→C→cc→link
# pipeline already (src/main.rs; it embeds the C runtime + lib/std and shells
# out to cc), so a single `gg build driver.gg -o gg-selfhost` produces the
# runnable self-host compiler directly. This is the standard compiler
# bootstrap: the seed builds the stage-1 binary, then its job is done.
echo "[gg_impl] Stage 2: seed compiles driver.gg → gg-selfhost binary..."
# The seed emits compile warnings on stderr; keep them out of the log but
# preserve the exit status (so a genuine build failure is caught).
if ! "$SEED" build "$DRIVER_SRC" -o "$SELFHOST_BIN" 2>/dev/null; then
    echo "[gg_impl] ERROR: seed failed to build driver.gg → $SELFHOST_BIN" >&2
    echo "[gg_impl]   re-run without 2>/dev/null suppression to see the diagnostics" >&2
    exit 1
fi
if [[ ! -x "$SELFHOST_BIN" ]]; then
    echo "[gg_impl] ERROR: $SELFHOST_BIN was not produced" >&2
    exit 1
fi
echo "[gg_impl] Compiled: $SELFHOST_BIN ($(du -h "$SELFHOST_BIN" | cut -f1))"

# Stage 3: create wrapper script that sets GG_RUNTIME_DIR + GG_LIB_DIR
# so the binary can locate the C runtime and stdlib on every invocation.
GG_WRAPPER="$INSTALL_DIR/gg"
cat > "$GG_WRAPPER" << WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by scripts/gg_impl.sh — GG_IMPL=selfhost wrapper.
# Sets GG_RUNTIME_DIR and GG_LIB_DIR so the self-host driver can locate
# the C runtime and stdlib without explicit --runtime-dir / --lib-dir flags.
export GG_RUNTIME_DIR="${RUNTIME_DIR}"
export GG_LIB_DIR="${LIB_DIR}"
exec "${SELFHOST_BIN}" "\$@"
WRAPPER_EOF
chmod +x "$GG_WRAPPER"

echo "[gg_impl] Installed self-host gg as $GG_WRAPPER (wrapper → $SELFHOST_BIN)"
echo "[gg_impl] Done (GG_IMPL=selfhost)."
echo ""
echo "Test with:"
echo "  $GG_WRAPPER build /tmp/hello.gg -o /tmp/hello && /tmp/hello"
